### ISSUE TITLE
Non-recoverable error while switching between items/m and belts after update.

### ISSUE THREAD

**Issue by karl0-dev** [ClaudeMetz/FactoryPlanner#106]
### Problem Description

While desiging my sandbox machine, i switched from belts to items/m (which i did many times in past hour), but suddenly got an error. I didn't change anything in recipe before changing from belts to items m. It's completely random.

https://i.imgur.com/ItBkp3d.png

`The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 459)
__factoryplanner__/ui/main/production_table.lua:331: attempt to perform arithmetic on field 'satisfied_amount' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_table.lua:331: in function 'fuel'
	__factoryplanner__/ui/main/production_table.lua:319: in function '?'
	__factoryplanner__/ui/main/production_table.lua:424: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:432: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:461: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:307: in function <__factoryplanner__/ui/event_handler.lua:287>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/base/view_state.lua:250: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/base/view_state.lua:250: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/ev
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/12198024/factorio-current.log)
ent_handler.lua:114>`

### Reproduction

1. Was working on my sandbox city block
2. Was doing some piping and belt work
3. Wanted to reference how much water do i need per minute
4. Switched from belts to items/m
5. Got error.

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/12198025/factorio-current.log)

**Comment by ClaudeMetz** [comment]
Hello, thanks so much for the super detailed report, and sorry for not getting back to you earlier!

I tried to reproduce this, but unfortunately I can't without the save (the link you posted expired because I was too slow). Any chance you could reupload it for me?

**Comment by ClaudeMetz** [comment]
Can't fix it without a repro unfortunately.

**Comment by karl0-dev** [comment]
> Hello, thanks so much for the super detailed report, and sorry for not getting back to you earlier!
> 
> I tried to reproduce this, but unfortunately I can't without the save (the link you posted expired because I was too slow). Any chance you could reupload it for me?

My apologies, I missed the replies. Uploading to weTransfer was bit shortsighted idea, I can't find the save now, because I don't remember the filename. The problem resolved itself anyway and haven't had an issue since. Appreciated. 

>Can't fix it without a repro unfortunately.
🖖

**Comment by ClaudeMetz** [comment]
No worries, thanks anyways!
