### ISSUE TITLE
Pipe throughout mode

### ISSUE THREAD

**Issue by Spook2U** [ClaudeMetz/FactoryPlanner#110]
### Suggestion

For fluids, it would be pretty handy to know the throughput required for the defined machines.

For example, 106 Refineries would require 1200/s crude oil (info from cheat sheet)

The throughput mode could be a button next tp items/s or belts.

**Comment by retep998** [comment]
That is *already* items/s. It tells you the amount of fluid per second, so exactly what you need to figure out what sort of pipe arrangement you need.
