### ISSUE TITLE
Mark recipe as done removes items from Utilities.

### ISSUE THREAD

**Issue by Leitk** [ClaudeMetz/FactoryPlanner#112]
### Suggestion

The 'Mark recipe as done' checkboxes could remove the items needed from the Utilities button that lists what items are needed.

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/26513358/fdbfe55f-42fe-4b6b-a7e6-c022ab80427c)

In this case the Oil Refineries and Chemical Plants should be 0 (and production modules should also be lower) because I've marked that as completed already.

**Comment by ClaudeMetz** [comment]
This idea makes quite a lot of sense, I think I'll make the change. Thanks.

**Comment by ClaudeMetz** [comment]
Actually, someone PRed this a while ago, I'll fold it in #35

**Comment by ClaudeMetz** [comment]
I implemented this for the next big release, thanks for bringing it up!
