### ISSUE TITLE
Non-Recoverable Error: Dataset count incorrect

### ISSUE THREAD

**Issue by dflor003** [ClaudeMetz/FactoryPlanner#113]
### Problem Description

I just started using the mod and built some sub-factories. I tweaked them quite a bit while I was learning how to use the UI and created subfactories for my existing base. After doing so, I went to start building out some of my factory and was just driving around when this error popped up and the game crashed:

```
The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_nth_tick(4314801)
__factoryplanner__/backend/classes/Collection.lua:69: Dataset count incorrect
stack traceback:
	[C]: in function 'error'
	__factoryplanner__/backend/classes/Collection.lua:69: in function 'remove'
	__factoryplanner__/backend/classes/Factory.lua:32: in function 'remove'
	__factoryplanner__/ui/main/subfactory_list.lua:35: in function 'handler'
	__factoryplanner__/util/nth_tick.lua:10: in function <__factoryplanner__/util/nth_tick.lua:7>
```

It autosaved right before it crashed so I'm able to reproduce this consistently in my save. I tried deleting all my factories from factory planner, but the game still crashes at the exact instant after I reload my save every time.

Here's the log:
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/12286551/factorio-current.log)

### Reproduction

I don't know exactly what I did to get this error to occur.

**Comment by dflor003** [comment]
I was able to get somewhat of a workaround for now. I basically did the following:

1. Exported my factory plan as a string
2. Uninstalled the mod
3. Loaded the game and saved
4. Reinstalled the mod
5. Imported my factory back from the string

Curiously... I saw the tutorial factory plan show up in my exported string even though I had deleted it before. I wonder if it might be related to the issue. Will post here if the issue creeps up again.

**Comment by ClaudeMetz** [comment]
Thank you, I'll look into it soon!

**Comment by edsandrof** [comment]
After using the "tutorial" and deleting the "example" entry, I got the same crash in the game minutes later.


```lua
O mod Factory Planner (1.1.72) causou um erro não recuperável.
Por favor, reporte este erro ao autor do mod.

Error while running event factoryplanner::on_nth_tick(5654259)
__factoryplanner__/backend/classes/Collection.lua:69: Dataset count incorrect
stack traceback:
	[C]: in function 'error'
	__factoryplanner__/backend/classes/Collection.lua:69: in function 'remove'
	__factoryplanner__/backend/classes/Factory.lua:32: in function 'remove'
	__factoryplanner__/ui/main/subfactory_list.lua:35: in function 'handler'
	__factoryplanner__/util/nth_tick.lua:10: in function <__factoryplanner__/util/nth_tick.lua:7>
```

**Comment by ClaudeMetz** [comment]
This looks like an issue with the tutorial subfactory, which is handled very differently in the upcoming rewrite. So I'll not look into this too deeply now, since the code will be obsolete soon anyways.

If the issue persists with the rewrite, I'll really look into it.
