### ISSUE TITLE
Crashing in the interface.

### ISSUE THREAD

**Issue by ProfounDisputes** [ClaudeMetz/FactoryPlanner#114]
### Problem Description

I am getting crashes that appear random. Just clicking on stuff will crash it:
![20230812164629_1](https://github.com/ClaudeMetz/FactoryPlanner/assets/110345786/3a5787d2-a692-4b7a-9521-7cee4405b080)

I was able to reproduce in a certain circumstance but its not the only time it has crash with the same error.

Factory Export String:
eNrtXelv2zgW/1cKf9oFKoH3McB+aLuZxWCng6LpzpdBEcgyHXMiSx4dabxB//d91BHLzrFt6iiKzQwwTSiKeiR/7+A7pOvJMpudXZq8sFk6+WmCQxxKMnk9MVerLC/P4GphyslP15NpVJi2g5LQ4eQy+9d/foEWFLJQIAxNv5uFjRNzmkarpqcKOTS/mf1ZFWU0TUzwAR6UpVESfMymmXtA8DFKz009ig6R61yV2T9NnKVFmVdxWV+hoYIr02xq08LkJYzRUdo0J3aaR/m6bRTQ+DYry8SkJr6oB8Bt1ypJTBmUeWSTor4gQjfXk5WN3+Slhav5+jSr0ln3ADcrc2nSYGaBHjutym6ZYFBH7snVKskKe2lenVzF0WVUbpbR0fwzjMneN/PDqJ7gHKht/iahdl1+O+lW0T1tYRJY864Ddj3+fXr2Ifti8rqR170S2Iw8sakp2gVyje+jq49Rad5FSVwlUZm5GygMyxwlp39VJrp49WmRZ9X5oiZR1ZMvyllDEYaurmdprsoV3G+6JaonWtqlOV0Z05BG6lvdXn3Ko8INxx0RtNkPWPilNUVvP1zjX5VdLU1abjdn+VbHdxUAJD9JF1EaG9fbXYR1qJfuvU1MUWZpewdtlud9NqsS80sLjZOPNTGkRt4HG1+Y/E25AIqqZX1Td2FlfrdFFSX2v/XCug11z79jAUnopvXRxHDP2yy7qBt5PYzD8hV0TAOYhYnyeBHAMlem3U/iduVTVFz8CujpOKWZ9s0C95aiNPGi1zKPYiBhDT3TtKWx5c3fohQWrixe/e0dMFa2/HtLZ70czZxPrkqTzurdAlyFrHlCVBRmOU3WOzuTmLjMs9TGOwQl2TkQfqt5aVObnm+3rVqA9rgyN5fRcrXd7UuUz6Pc7IxXb2D/IU4mJEVu5t2TamZgN1dWBuiNF2bZCg7iLv0apbM58NuHyKZldxuvgdrcFc1mIFYCWLE8amVOy8XN9WJpkpsbRbN7pl3HYGaKOLcrx99FCyR3Hfb9AqRSsBFBDqz8ZsypzVZAqimKbmDZUPvO5nFlyw/bF1l9azcorE3RG/HURG+TrBVpvOG2rmvztLaz6F2Is+UKpNLUJrbsyNOTr4DdatogrObUP64nabR0i/Ielu/VWyfsG6Yv4iiBdoFeT9KswazbtqQyq9zW/HkNo8E8ZrW4vp5k0z8BT82YMPcyc43t4BFIjGUtJIMitgZ4PFhFMKPXkxj44TyrV9CWsLGvJ7OojM7K9cq0TYVjOLtcJXZuHbBBPxh4crQEgQ0PxsRNGoRMbmZnXeP1ZOZABC1TN3LbvH0T4L88awmdR0nhBi2z1VkCgj9pHgPkgcR1U+/m+fX17cl17HKAU3O8ZgEIBzg1C5IvqMXxPubD0SPm427a31Zlq5XJD2lGjWwLwFKgQZxXxQKo3MPEHoO8RwPv86btXZY4hesMxfbWeZI5W+N68is8eleEdrfV1xzJzg5xnb5dtvYXprn/nqVZNeTCEF33pqUGUktHYwg50kF7gOHbTRl0q2lXBAYyeQzGW61mMQIwLKN40U7uFt2NUQIqMGh7BXh7f+M8mteKeXsqbe975jLPgISzxC5t2ZHYGBpn7YHmxuzorbdTZXfvU9faWJunptxqbGc3GkXYA2S7I9+KSMeA3wy5+zSeB9zoAPekxslAcLvPCvFwGx3cntRgHAhujd0BZgfuzI7g5og4dtDVbpJgXuVpFO+YgffM4bvRNq/cBtyx9SZJqiQr4PF2avIdqLe42Hm4G+v/bTwPJd+s2M/u6V9Hhfn9nySGBjr1QB8B0HXIKer9YEyFEopKSbDAAhEtqaZSK0UUJuPmiX2fRsVziv/RM8MU2ABWG2huSd4BpbvQeVWDEr8wxqBjVwAbRwXep6PCzfrZNIHH/LNinr0czO/VOaeHw3wxDb4AuXmwhJ55HRGcwVTWRRkl8EcT0h07F2zovYW9mysH5kHbCNsBhezD7ukRIP9eR3M7Hu5Jk9rt3NuE0y4kuK4n2s6vyT14gmBgUZpoGWDBt5dtnlR29gh3PljGjwlVtPc9s1vfRWP3EgWABcpchDvor+7INXhmk12pdR/1e9PXX7IMpPwiyuOs1sv7Obq548mIlfWTcNyAatrt2TS38UXR3zrvoHgI48167QvhKORC6K0fojTjkghGqFZaK8wwUUpySQkjWI3cfn1ADjzSQT2gi2J7g30YZHRG6r0c+DhsURLqLfZTkmnGmFQcCUIIFZIoIRQBDtTQwodF4sq4/FoPxfFCcbNDP+6J5aGmtIdFgKJSSnOJMHGYpKAVKAW1wGXjph4qSrztiQmi5DwyHpOjjBI/5DR7pIjUPBSoh0vFNOCUSkaQZCAbGfzDEFacM6GGdK06GAbnuTFpUNP/AjBZkzyP8uX2zkxtFvSymg/Ip7TZo734lDQOCVKbSJ4CBU05CENBMdJUSxCYWFGuqXxarw+55fW5A7sH7YPAx+KDQEfkgfDehyPzPhyXKwF5R4K3lJ/EkYC8Y8BD64kcA8if9D3IBjjpo+c4uvsz+4Gf2QfUjLtJR6PHVmL/qhwZO+zbNK8PTCvesTsv6sCaROc9hg/qg6BP5nzWZM6xu2acq2CPOZwDGoJRPnWVtGYV5U1RLfHCdETQOo+KoN2jmc2u7MyMQJp6n/lLzNsrssTOWjB5l/mohXJ2YYJVlQMd8ctIoj8mkXw/H41d2ftQjA/F+FCMd2X6UIwPxfhQjA/FeJAdZyjGZ1H6iMzDhbk1HdM8+zKCE84jvE1PVMr7Knj1R8Ml/2hUTeBO6p97zb0NhGZf+vt9pb/LqMzt1dkclu+sIb5eGV8RPHLPYscMe87HJdKXBD+RMdATX97UHKMl8CBLPfKtzSLcLj8WjLmiR0ow1pppjSSCJiqVEMQVWUjuPZNHV6KOJfyHldZSY8KkRlgiigEnRCNEMMOaE46ZYIrR4ytQRyHTSCDOiHRVmwwTkNsac44FVkQqRARXSGE0cImcd30eXTm74FpRRRDjGlgTM0qVVki6imFog/8LJBTGnFBGpS9n91B8wnJ2irWQgiGNFSBPIjAhOFISKQCh5pQRQQVGimo1KBa9a/W469lVSJxRq0EYAvoEFgxQyARiCAFMKQhQMH4HfcOCz4c/php2EXL3Tict3OucJKFEE4K0q2vHWBCJtQRzcdB3zfjE+aNLnMdEMvdadMAbdW89ku6NYxKUsnSyTwlEOR4UhD6/fnz59SKkThaBThRaU0lBdmnthJdECI65nCAqBAbzDow8TIUc/cvp9p6SD2wUsj4bCaI5LAMsi1JaM8QRIlxT+BWzQV8gNrN52b6HeZPGP37ronn3b/sF1WRd7IL55kulu30OJo8U5OBezl803OJdx7UAREWRZkxLQCXCxPEznMsQHfR9Yr645BiLSwaxOHxWgH8huA//+/C/D//78L8P/38LwqSP5h9ZNJ9JsP17P5zW/nA4thKEJJwY4NhKKaPwl7h5l+ZRBfSpD9F7mfs0IXrnL9rmP8xcGIoziTlBwHNUYskIYYoP7YL1QfpjC9JzFmq2pQyIckEppBlFzEVEJaNM1Q6job1EPkp/zFF6osOtD3NwMFGIpIBORMBQIZpoqsjmizi+XMoH7J8mYC+4Dre+y4EVZqCu3ZcPGBWMK66k2KS+vnTv5afl6il8kfv9mDt5lCPy0V7IO4rhkiidzW2SBAX8EtA9FcR995zwIXlW+xDxPoGHfAJ32oA/4hSQoEX7hxIpBeVw/NfMBbARiDfhkoiREO7rdI0lOGKfwP6lzdAfDL/54vn9Snp8bOHSXYB4B3+wOGKb2HJ9OyGm7XFAJkcNN5jangqyxNaP+xidRoxzLYAxwSoGa8PlmFApwQoe9ptLt9DpM7SeU2rTnR9NOOOESK3qjyMxBSclrqlQSr+E0qzeJ8j3maTF6c5CuU/qKaQx1s7fBsvGiUbUpSSAMT9sheNO1iMelp+a37+HneJ8XZRR4hJRd9MMb64c2HFyA8ojAyMcb0qTvwhYOlLbZLIqteVO8L2bxwGhss0HD4qkmp3vKUELwLeFTdAYGnOpqCCgSDCVRCs+eLnWLipntiiypBo+nfX7UXlU7z912wRozPP1IaOx3rtZUFQJHP5tHMAhZzZ2GLYarDM03bk4Le8wQouy3rtDQeQ9W/Xj0GQIhWgrg0IACBlWSiDlyriYEnAuGz7n32XuNtPtZe56CTmivOpbu/PjaBQ7aMQYzntCUSkJFlggoiUFM1KD0By0qLV5IXYzYS8hx6mzu8358ZSpHYn4bQ7kwepbi8WLOMV0hN4Bv91LhyQUF+tZnp27iDrgcV9ikewq6dFkttwUEDTVeZe2iLOqCJYVSEsT1aG0YFXVUdhRo3WX2H4M7IF5vPxa7N6O7Quq22ClAvS1VMq9pQJL7EpKhUDDJgP6+tHjrh8FTb0dh9JaEU6JBAWuQJ27yj0kOGGCK/LtAvT13Sogu1qf76brPJKb5GB+g2dM1/n89X/51aya

[SeaBlock Simpler.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/12328273/SeaBlock.Simpler.zip)

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/12328292/factorio-current.log)

### Reproduction

1) Load the save file
2) CTRL+ R
3) Go forth factory down:
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/110345786/a937c8a6-fee4-4e79-9b4c-6b984be76a39)

4) Right click the brown algae byproduct and it will crash:

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/110345786/d04de88b-59aa-4d24-a9ca-841c6c2e4aa8)

**Comment by ProfounDisputes** [comment]
I realized that if I used the export string in a new save file it doesn't cause any crashes so something must have happened in this save file. I tried to just delete the every factory and re-import but that just crash when I tried to delete any of the Power sub factories. Looks like I fixed it now by:

1) Going to each Power subfactory and changing the steam engines fuel to wood
2) Deleting all the subfactories
3) Importing from string the factory again.

I have not seen any errors now.

**Comment by ClaudeMetz** [comment]
Appreciate the report. That is indeed weird, the calculation must be getting updated incorrectly in some way. But that's very hard to figure out without a reproduction. Still, appreciate all the details, I'll see if I can dig anything up.

**Comment by pkoziol** [comment]
For the record, the stacktrace is the same as in #106 

I got the same error yesterday in my Space Exploration, but I was not able to trigger it second time.

**Comment by ProfounDisputes** [comment]
Ok, this time the error completely broke Factory Planner. I can't get into the menu without it crashing. I have the minimized display up and when I CTRL+Shift+R to get back to the full menu it crashes the game:
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/110345786/4a87a473-c755-4875-8d40-f4607888a53c)

[_autosave1.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/12386720/_autosave1.zip)

This save file in completely dependent on Factory Planner I have like 20 plans in there....How can I get this to work again? I have no save files that go back far enough where it doesn't crash.

**Comment by ProfounDisputes** [comment]
Only way to fix it was:

1) Disable Factory Planner in mods
2) Reload the save and save as a new file
3) Install [Debug Adapter for Factorio Mods](https://mods.factorio.com/mod/debugadapter)
4) Install VSCode
5) Install VSCode extension "Factorio Modding Tool Kit"
6) Configure extension for running Factorio.
7) Re-run Facotrio normally and re-enable Factory Planner mod and exit game
8) Run the debugger from VSCode and Reload the crashing file
9) CTRL+SHIFT+R to the edit Factory Planner interface
10) Now that we are in debugging mode the game will ignore the error and allow me to see the interface.
11) Export the subFactories to string.
12) Exit debugging Factorio mode
13) Run Factorio normally and load the new save file and import the Factory Planner string into the now blank Factory Planner interface.

Is there a way to ignore mod crash codes and not hard crash? If this happens again be nice if there was an easier way then what I described above.

Sucks I had to do this, I was trying to do a run through with Replay enabled but changing mods disables replay. I could have gone to Helmod but honestly like Factory Planner way more and would have cost me 5hrs of redoing all my plans . Overall Factory Planner is a great mod.

**Comment by PFQNiet** [comment]
Just popping in to say that I've had this crash in my own relatively new Angel+Bob playthrough.
If it is at all relevant, I did start the game, then save and back out to disable Bob's Enemies since I realised I was playing biter-less. Obviously this removed a number of prototypes from the game. *Maybe* Factory Planner was expecting something to still be there? Or maybe it's totally irrelevant.

For completeness, the error:
```
The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 247)
__factoryplanner__/ui/main/production_table.lua:331: attempt to perform arithmetic on field 'satisfied_amount' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_table.lua:331: in function 'fuel'
	__factoryplanner__/ui/main/production_table.lua:319: in function '?'
	__factoryplanner__/ui/main/production_table.lua:424: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:432: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:461: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:307: in function <__factoryplanner__/ui/event_handler.lua:287>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/subfactory_list.lua:126: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/subfactory_list.lua:126: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

I hope this helps!

**Comment by ClaudeMetz** [comment]
Thanks everyone, I'm sorry for not getting to this already. I'll definitely get to it this week.

**Comment by Atria1234** [comment]
Hi, I have been experiencing this in my multiplayer game, but when I tried to debug it with the debug adapter in singleplayer it never happened to me.

I doubt it isa correct solution but it can be worked around by adding fallback `fuel.satisfied_amount or 0` to https://github.com/ClaudeMetz/FactoryPlanner/blob/master/modfiles/ui/main/production_table.lua#L342 .

**Comment by ClaudeMetz** [comment]
Man I can't reproduce this one, even with all the very detailed reports (thanks for that guys!). I have a big update in the pipeline, so I guess I'll just release that one now, and if anyone runs into this again, let me know, hopefully we'll figure out a way to make this happen on my machine.

I don't really have an idea for how this could happen only very inconsistently, not sure what's going on. It's related to the ingredient satisfaction preference for sure, and those calculations not being run correctly in some very specific circumstances, but how that happens is very hard to find out without a reproduction.

Anyways, sorry for not getting to this earlier despite all the great reports, I'll be more on the ball going forward. Some specific replies below:


> Is there a way to ignore mod crash codes and not hard crash? If this happens again be nice if there was an easier way then what I described above.

Sucks I had to do this, I was trying to do a run through with Replay enabled but changing mods disables replay. I could have gone to Helmod but honestly like Factory Planner way more and would have cost me 5hrs of redoing all my plans . Overall Factory Planner is a great mod.

Sorry that you went through this. Unfortunately, I don't think there is a feasible way to avoid this kind of situation. Normally, the crash would set you back to the previous save, which is still issue-free, so you can continue as long as you avoid triggering the same bug again. In rare situations like these, one can end up in a bad spot like you did, but it should be pretty rare.

> If it is at all relevant, I did start the game, then save and back out to disable Bob's Enemies since I realised I was playing biter-less. Obviously this removed a number of prototypes from the game. Maybe Factory Planner was expecting something to still be there? Or maybe it's totally irrelevant.

I don't think this is related tbh, but good of you to bring it up. In this case, it's just an issue with the satisfaction calculations not being run before trying to show them in the UI. That normally shouldn't be possible, but it somehow is. I only do those calculations if that setting is enabled, to save performance for people that don't use it, but obviously doing that creates more surface area for bugs. Maybe if I can't ever figure this out, I'll try to simplify, but I'm not quite desperate enough lol.

> I doubt it is a correct solution but it can be worked around by adding fallback `fuel.satisfied_amount or 0`

That will indeed stop the crashing, but it's only fixing the symptom, not the cause, so I don't want to add this, since I won't ever find the real cause that way.

I'll leave the issue open in case someone finds anything that could help, or maybe the new release will shed some light on it.

**Comment by ClaudeMetz** [comment]
Oh wait, I did get the crash to happen by manipulating the code a bit! Let's see if it's the right crash or just the same one with a different cause.

**Comment by ClaudeMetz** [comment]
Update's been out for over a week, and no one said anything, so I'll consider this one resolved for now. If anyone has this issue again, please open up a new issue for it!
