### ISSUE TITLE
[IR3] Graphene recipe does not show helium as an ingredient

### ISSUE THREAD

**Issue by matthew-sharp** [ClaudeMetz/FactoryPlanner#120]
### Problem Description

I added the Graphene recipe to a subfactory, and the planner did not pick up helium as an ingredient or byproduct.

My guess is that this is due to the recipe having 2 catalysts, or due to the helium input and output being balanced.

### Reproduction

1. Start a game with IR3
2. Create a subfactory for Graphene
3. Ingredients show plastic and liquid nitrogen, with a byproduct of nitrogen. Helium should be both an ingredient and a byproduct, but isn't.

**Comment by matthew-sharp** [comment]
Actually there's a good chance this is "not a bug". The recipe uses net zero helium. I guess it depends on what the purpose of Factory planner is. Maybe this a feature request to show net zero ingredients in both the inputs and outputs, but with zero quantity, to show that it's necessary for bootstrapping.

**Comment by ClaudeMetz** [comment]
Yeah this is a known 'issue', the mod should really show the catalyst amounts in some way. It's on the todo list #91. I'll close this issue as duplicate in a while if there's no further comments :)

**Comment by matthew-sharp** [comment]
I agree it's a dupe. I'm happy for it to be closed as one.
