### ISSUE TITLE
Can't select Steam (165 degree Recipe)

### ISSUE THREAD

**Issue by danbopes** [ClaudeMetz/FactoryPlanner#124]
### Problem Description

Preface:
Using Industrial Revolution 3 and trying to use Electric Boiler

I have various buildings which need steam:
![](https://i.imgur.com/w8eyiVn.png)

When I click to add new recipe, it automatically adds one (Without letting me select a recipe), which is boilers/etc. However, there is a recipe in game, that produces 165° steam, that can be used provided by the electric boiler. I'm unable to add that recipe to provide steam for the factory block. Here's a new block showing the 165° steam:

![](https://i.imgur.com/eKk2kHC.png)

How do I have it choose this as a valid boiler to be used?

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report, and sorry for not getting to it earlier.

This is indeed kind of a bug, I've known about it for a long time, but it's very hard to rectify. It'll require a redo of a whole underlying system, which I haven't gotten to yet. I hope to get to it soon, but don't know when yet.
