### ISSUE TITLE
Bug: Cannot enter a value less than 1 in "Amount of Beacons" dialog

### ISSUE THREAD

**Issue by bonesbro** [ClaudeMetz/FactoryPlanner#128]
### Problem Description

I tried to add a beacon to a row of production with Amount = 0.75, indicating that I would only cover 3/4 of the assemblers with the beacon.  I was unable to hit Submit to apply that change - the Submit button was disabled with the error tooltip "Enter a beacon amount greater than 0".  

Entering 0.75 should be valid - this use case is supported by the tooltip on the Amount entry box which reads in part "You can put a decimal number here, which could be used to reflect that your machines might be covered by a different amount of beacons."

Maybe the code is checking, like, <1 instead of >0?

### Reproduction

1. Add a row to a factory plan.  I used Traditional solver if it matters.
2. Click the + to add a beacon
3. Select a beacon, enter 0.75 for the Amount and 1 for the total
4. Attempt to click Submit

Expected: I can add the effect and it would calculate that 3/4 of the machines are affected by the beacon.
Actual: The Submit button is disabled.

**Comment by ClaudeMetz** [comment]
Huh, that's a weird one, not sure why I made it that way. Fixed for the next release though, thanks for the great report!
