### ISSUE TITLE
Add stack size to item tooltip

### ISSUE THREAD

**Issue by apaksl** [ClaudeMetz/FactoryPlanner#129]
### Suggestion

I use your mod a ton (like seriously, a lot), thank you so much for developing and sharing it! 

I often have to go back and forth from the factory planner window to the crafting screen so I can see the stack size of various items. I think it would be super handy if you added a field for stack size to the tooltip in FP.

**Comment by ClaudeMetz** [comment]
Sorry for not getting back to you for so long, hopefully you'll still get notified about this.

Could you clarify a couple of things? By item tooltips, do you just mean every item button around? Or do you want a different view that you can toggle to that converts the raw item numbers to item stacks?
