### ISSUE TITLE
Crash in Space Exploration

### ISSUE THREAD

**Issue by TorbenSchoene** [ClaudeMetz/FactoryPlanner#130]
### Problem Description

I was playing Space Exploration with a friend and factory planer just started crashing. I am not sure how we got the game in this state but it is practically unplayable now.
I managed to fix this for now, by loading the save without factory planner, saving and then loading the save with factory planer again.

```
The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_nth_tick(578468)
__factoryplanner__/backend/classes/Collection.lua:69: Dataset count incorrect
stack traceback:
	[C]: in function 'error'
	__factoryplanner__/backend/classes/Collection.lua:69: in function 'remove'
	__factoryplanner__/backend/classes/Factory.lua:32: in function 'remove'
	__factoryplanner__/ui/main/subfactory_list.lua:35: in function 'handler'
	__factoryplanner__/util/nth_tick.lua:10: in function <__factoryplanner__/util/nth_tick.lua:7>
```

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/12640363/factorio-current.log)
[Space Exploration.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/12640366/Space.Exploration.zip)

### Reproduction

Load the save file and wait a few seconds.

**Comment by ClaudeMetz** [comment]
Thanks for the very detailed report, this is indeed a common error. It's fixed with the next release, which replaces the code that could be causing this, and which is due out soon!
