### ISSUE TITLE
Utilities -> Constant Combinator Blueprint should include modules/beacons

### ISSUE THREAD

**Issue by polski-g** [ClaudeMetz/FactoryPlanner#133]
### Suggestion

Currently, the Constant Combinator creation only includes the machines themselves, not the beacons and/or associated modules. Would be nice to include them as well.

**Comment by ClaudeMetz** [comment]
Hello, thanks and sorry for not getting to this earlier. The dialog actually does this, but it needs some more information than the basic ones to be able to do this. If you only set the amount/machine on the beacon, it can't know how you build those beacons, and thus not know how many in total are actually needed. Thus you need to put that in yourself in the beacon editor, and if you do that the utilities dialog will work as expected.

This did give me the idea to have the mod potentially calculate that number out itself, which would require a few assumptions, but sounds doable. I'll think about that, but for now you'll have to do it manually.
