### ISSUE TITLE
Matrix planner negative solutions not displayed in the UI

### ISSUE THREAD

**Issue by sylvia43** [ClaudeMetz/FactoryPlanner#134]
### Suggestion

I'm using Factory Planner on a new Nullius playthrough, and I've found a handful of cases where Factory Planner comes up with solutions that involves negative amounts of a factory building. This on its own is okay, but the UI can make it unclear that that's what's happening.

In this case, the solution is using a negative amount of chemical plants, which can be seen by checking the power usage but it isn't otherwise shown in the UI.
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/5544386/36f8ff8f-e0c3-449a-948f-b73800d6c9f7)

In this case, a venting recipe (100 hydrogen -> nothing) is being used a negative amount of times to generate the missing 2.8k of hydrogen. With no power consumption, 

there's no indication on the UI, aside from adding up the numbers and noticing the discrepancy.
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/5544386/4f6cbb3e-18ea-4f8e-a1ae-b9626e7f53d5)

Thank you for all your lovely work by the way!

Here's an export string for both recipes, in case it's useful. It'd require Nullius and no other mods. [factory_planner_negative_matrix_solutions.txt](https://github.com/ClaudeMetz/FactoryPlanner/files/12746935/factory_planner_negative_matrix_solutions.txt)

**Comment by ClaudeMetz** [comment]
Thanks for the report, and sorry for not getting to it earlier. There's a similar report in #127. I'm not sure how to deal with it yet, but it's on my radar. I'll close this one to centralize on the issue I named before.
