### ISSUE TITLE
SE+K2 crash

### ISSUE THREAD

**Issue by ctgPi** [ClaudeMetz/FactoryPlanner#137]
### Problem Description

```
271489.286 Error MainLoop.cpp:1395: Exception at tick 8780464: The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/util/clipboard.lua:14: attempt to index local 'object' (a nil value)
stack traceback:
        __factoryplanner__/util/clipboard.lua:14: in function 'copy'
        __factoryplanner__/ui/main/production_handler.lua:196: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
271489.286 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/util/clipboard.lua:14: attempt to index local 'object' (a nil value)
stack traceback:
        __factoryplanner__/util/clipboard.lua:14: in function 'copy'
        __factoryplanner__/ui/main/production_handler.lua:196: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>"
```

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/12778556/factorio-current.log)

### Reproduction

(sorry for not having more details; this was in a community server and I'll reach out to the relevant people to find out what was the issue, reproduction steps etc.)

**Comment by ctgPi** [comment]
Save file: https://discord.com/channels/600791114814980141/600791114831757416/1158193611414966353

**Comment by ctgPi** [comment]
mod list:

```
aai-containers_0.2.11.zip
aai-industry_0.5.20.zip
aai-signal-transmission_0.4.9.zip
aai-vehicles-ironclad_0.6.8.zip
alien-biomes_0.6.8.zip
BetterAlertArrows_1.0.0.zip
bullet-trails_0.6.2.zip
combat-mechanics-overhaul_0.6.24.zip
equipment-gantry_0.1.5.zip
factoryplanner_1.1.72.zip
FactorySearch_1.10.14.zip
flib_0.12.9.zip
grappling-gun_0.3.3.zip
informatron_0.3.4.zip
jetpack_0.3.14.zip
Krastorio2_1.3.22.zip
Krastorio2Assets_1.2.1.zip
Milestones_1.3.20.zip
mod-list.json
mod-settings.dat
ModuleInserterSimplified_1.1.4.zip
PipeVisualizer_1.0.6.zip
RateCalculator_3.2.3.zip
RecipeBook_3.5.6.zip
robot_attrition_0.5.15.zip
se-little-inferno_1.1.0.zip
shield-projector_0.1.6.zip
simhelper_1.1.5.zip
space-exploration_0.6.116.zip
space-exploration-graphics_0.6.15.zip
space-exploration-graphics-2_0.6.1.zip
space-exploration-graphics-3_0.6.2.zip
space-exploration-graphics-4_0.6.2.zip
space-exploration-graphics-5_0.6.1.zip
space-exploration-menu-simulations_0.6.8.zip
space-exploration-official-modpack_0.6.3.zip
space-exploration-postprocess_0.6.26.zip
StatsGui_1.4.1.zip
textplates_0.6.10.zip
Todo-List_19.3.0.zip
TrainGroups_1.4.2.zip
```

**Comment by ctgPi** [comment]
FWIW the SE Community Server was _made_ to find bugs with mods etc.; if tinkering with our current setup would help feel free to ask and I'll tweak the relevant server settings, upgrade mods etc.

**Comment by ctgPi** [comment]
According to the player online at the time, "I think I was shift right clicking or something like that to clear the modules out of something in fp.  Maybe a bit of lag and I clicked twice".

I figure that reproducing this might be hard, but how much code pollution would wrapping UI event handlers in `pcall` (and presumably log to console/`script-output`, instead of crashing the game) do you figure would cause?

**Comment by NotACliche** [comment]
Been having the same issue with K2SE on a MP server when messing with modules

**Comment by ctgPi** [comment]
Happened again, this time with SE+BZ (I can provide the full modlist); the user reports deleting a module from a factory plan.
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13200795/factorio-current.log)


```140642.265 Error MainLoop.cpp:1395: Exception at tick 6781770: The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/util/clipboard.lua:14: attempt to index local 'object' (a nil value)
stack traceback:
        __factoryplanner__/util/clipboard.lua:14: in function 'copy'
        __factoryplanner__/ui/main/production_handler.lua:196: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
140642.265 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.
```

**Comment by ClaudeMetz** [comment]
Thanks for all the details. I am unfortunately still unable to reproduce this, even though it's been reported half a dozen times. I have looked at the relevant code, and it has been changed with the coming rewrite, so I think I'll wait until that is out (soon!), and it might just be fixed. If anyone still runs into this issue, please let me know, I'll keep the thread open.

> I figure that reproducing this might be hard, but how much code pollution would wrapping UI event handlers in pcall (and presumably log to console/script-output, instead of crashing the game) do you figure would cause?

This is actually very simple, code-wise, but I don't like running it in production for a couple of reasons. First, pcall is bad for performance, so I would be adding that to every single action. Secondly, and more importantly, it would hide the bugs from me, since people would be reporting them less that way. And even worse, related to that, I can't even really use it at all, because of the potential to corrupt the data. Since my mod keeps data around, a crash can leave that in an inconsistent state, even if I completely reset the UI. That will then lead to incomprehensible bugs down the line, because of the corrupt data structures. The only way to make it work is to reset the mod completely, which is obviously not possible for Factory Planner. For simpler mods, it would be an option, but still not a great one.

**Comment by ClaudeMetz** [comment]
Update's been out for over a week, and no one said anything, so I'll consider this one resolved for now. If anyone has this issue again, please open up a new issue for it!
