### ISSUE TITLE
Non-recoverable error

### ISSUE THREAD

**Issue by mandydax** [ClaudeMetz/FactoryPlanner#139]
### Problem Description

I'm getting an error while playing Pyanodon's. I hadn't had any problems up until now. Save file here: [.....pY pY Again....zip](https://github.com/ClaudeMetz/FactoryPlanner/files/12841655/default.pY.pY.Again.zip)
```
The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 310)
__factoryplanner__/ui/main/production_table.lua:331: attempt to perform arithmetic on field 'satisfied_amount' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_table.lua:331: in function 'fuel'
	__factoryplanner__/ui/main/production_table.lua:319: in function '?'
	__factoryplanner__/ui/main/production_table.lua:424: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:432: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:461: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:307: in function <__factoryplanner__/ui/event_handler.lua:287>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/base/main_dialog.lua:243: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:307: in function <__factoryplanner__/ui/event_handler.lua:287>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/base/main_dialog.lua:243: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:307: in function <__factoryplanner__/ui/event_handler.lua:287>
```
[.....pY pY Again....zip](https://github.com/ClaudeMetz/FactoryPlanner/files/12841655/default.pY.pY.Again.zip)

### Reproduction

The crash does not happen when I use the shortcut keys or the button to open the main window, but using the shortcut keys for the mini-window or the button on the mini-window to switch to the main window, it crashes, giving the error log. This only occurs with this Shale Oil subfactory.

If I switch to another subfactory in my list make it so I can switch from main to mini without a problem. But then, if I switch back to the Shale Oil subfactory, the error occurs.

**Comment by ClaudeMetz** [comment]
Hello, appreciate the report! Unfortunately, your save zip seems corrupt in some way, it just unpacks to an empty folder for me. But that's okay, there's another thread with the same issue where people posted information as well. I'll close this one, so please everyone refer to #114
