### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AndiBOIS** [ClaudeMetz/FactoryPlanner#140]
### Problem Description

Hey!
Everytime i load into this save file
[last attempt.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/12866945/last.attempt.zip)
 it crashes with following Error Message:

The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_nth_tick(349856)
__factoryplanner__/backend/classes/Collection.lua:69: Dataset count incorrect
stack traceback:
	[C]: in function 'error'
	__factoryplanner__/backend/classes/Collection.lua:69: in function 'remove'
	__factoryplanner__/backend/classes/Factory.lua:32: in function 'remove'
	__factoryplanner__/ui/main/subfactory_list.lua:35: in function 'handler'
	__factoryplanner__/util/nth_tick.lua:10: in function <__factoryplanner__/util/nth_tick.lua:7>

### Reproduction

1. Load into save
2. Wait 2-3 minutes
3. Crash happens

**Comment by nwarford** [comment]
I wanted to confirm that I've experienced the exact same error message! I double-checked and this happened even only with Factorio Library and Factory Planner installed. I've been trying some new QoL mods, no game-changing ones on the level of Space Exploration or anything, but even so, they're all disabled.

Error message copied below:

Just wanted to 

The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_nth_tick(75656)
__factoryplanner__/backend/classes/Collection.lua:69: Dataset count incorrect
stack traceback:
	[C]: in function 'error'
	__factoryplanner__/backend/classes/Collection.lua:69: in function 'remove'
	__factoryplanner__/backend/classes/Factory.lua:32: in function 'remove'
	__factoryplanner__/ui/main/subfactory_list.lua:35: in function 'handler'
	__factoryplanner__/util/nth_tick.lua:10: in function <__factoryplanner__/util/nth_tick.lua:7>

My save file is attached to this comment - hope it helps!
 
[Mod Test.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/12974925/Mod.Test.zip)

**Comment by Barabasr** [comment]
Hey! Just wanted to add that i am having the same error crashing the save.

Sorry not sure how to link the save or add a screenshot as i am on steam deck and relatively new to it.

Also on 1.1.72 of factory planner and am also running K2 with a few other minor mods.

**Comment by VedaantAchuthan** [comment]
Similar issue, running latest version of factory planner on 1.1.87 alongside Freight Forwarding and a few other mods.

**Comment by ClaudeMetz** [comment]
Hello everyone, thanks for all your reports, and sorry for not addressing this earlier. This bug is an old one that I haven't been able to nail down yet, and it seems to have gotten more frequent. Either way, the next update will include a big rewrite that drops all the code that could be causing this, so it should all be fine when that is out. I'll try to release it very soon.
