### ISSUE TITLE
Typing in comment section during save time triggers hotkeys

### ISSUE THREAD

**Issue by TripleOmega** [ClaudeMetz/FactoryPlanner#144]
### Problem Description

While typing in a comment section an autosave triggered. I could keep typing no problem, but after the save was done Factory Planner closed and my informatron screen popped up. This was likely because I typed an "i" in the comment section(its hotkey).

### Reproduction

1. Type in comment section using a letter that is also a hotkey
2. Keep typing while autosave triggers
3. Note the comment section works as intended
4. Hotkey triggers after save ends

**Comment by ClaudeMetz** [comment]
Hello, that is unfortunate. I don't think this is specific to my mod though, it's just how the game works. As a mod, I can't even know when a save is happening so, I couldn't even try to work around this. So yeah, this is just how it is :)
