### ISSUE TITLE
Add ability to remove unrestricted items when there are linearly dependent recipes

### ISSUE THREAD

**Issue by radoslavkarlik** [ClaudeMetz/FactoryPlanner#147]
### Suggestion

I am not sure if this is a bug but I feel like it's just a behavior that was not considered.

I got into a situation in which I needed to remove a lot of recipes to continue because I couldn't get past the error. I got into this situation by choosing an unrestricted item. So it should be possible to undo this state by going back into the unrestricted item selection. Or by removing the previous recipe.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the suggestion. I changed the UI for the matrix solver configuration in a recent update which should help with this. Please have a look at that. If you still think it should be improved, please feel free to open a new issue, thanks!
