### ISSUE TITLE
FP 1.1.72 crash

### ISSUE THREAD

**Issue by RickJS2** [ClaudeMetz/FactoryPlanner#151]
### Problem Description

It was running fine for days.  Then I clicked in the left panel to switch to a different existing plan, and it popped up a window that said:
The mod Factory Planner (1.1.72) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 245)
__factoryplanner__/ui/main/production_table.lua:331: attempt to perform arithmetic on field 'satisfied_amount' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_table.lua:331: in function 'fuel'
	__factoryplanner__/ui/main/production_table.lua:319: in function '?'
	__factoryplanner__/ui/main/production_table.lua:424: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:432: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:461: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:307: in function <__factoryplanner__/ui/event_handler.lua:287>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/subfactory_list.lua:126: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/subfactory_list.lua:126: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

1. load saved game
2. switch to the atomic science plan
3. crash
4. profit! (no, wait)

**Comment by RickJS2** [comment]
I rebooted Windows 10.  Started Factorio and loaded a saved game.  Clicked on the Atomic science plan.  It crashed again.
[_autosave2.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13327114/_autosave2.zip)

**Comment by RickJS2** [comment]
I updated some mods (I don't think that included Factory Planner), and the crashing has stopped.

**Comment by ClaudeMetz** [comment]
I can confirm that the save you provided does not crash on the most recent versions. The issue you ran into has been reported before I'm pretty sure, but without a reproduction, it'll be hard to fix. Please feel free to open a new issue should you run into this again. Oh, and thanks for the report :)

**Comment by RickJS2** [comment]
Don't you just hate intermittent problems?  Thanks for investigating.

**Comment by RickJS2** [comment]
In the new version, it crashes every time try to change the specific quantity of an ingredient with this message:
The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 245)
__factoryplanner__/ui/main/production_handler.lua:203: attempt to index local 'item' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:203: in function '?'
	__factoryplanner__/ui/dialogs/generic_dialogs.lua:211: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
[SeaBlock-03.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13399029/SeaBlock-03.zip)

**Comment by RickJS2** [comment]
Also what is the recommended replacement for using the (now gone) percent field to split production between two recipes?

**Comment by ClaudeMetz** [comment]
New bug will be fixed with new version. Percentage column is still there, it's just an optional column now, disabled by default.

**Comment by RickJS2** [comment]
Oh.  I'll check settings.  Thanks!

**Comment by RickJS2** [comment]
I so much want a search function!
