### ISSUE TITLE
Change belt type on the fly without using preferences

### ISSUE THREAD

**Issue by ajklotz** [ClaudeMetz/FactoryPlanner#152]
### Suggestion

Ability to change the belt type on the fly with a keybind, at least on the compact view? Sometimes I want to use the appropriate belts depending how fast my floor needs supplies. If an item is consumed slowly, i dont need to use red or blue belts. I want to check if a yellow belt is sufficient, and then quickly switch back, without having to go to preferences.

**Comment by ClaudeMetz** [comment]
Hi, same idea as #153 funnily enough. I can see your issue, but I think the complexity would be too much, at least for how the system currently works.
