### ISSUE TITLE
SE+k2+BZ crash

### ISSUE THREAD

**Issue by Korvaz** [ClaudeMetz/FactoryPlanner#154]
### Problem Description

The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 438)
__factoryplanner__/ui/main/item_boxes.lua:229: attempt to index local 'item' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/item_boxes.lua:229: in function '?'
	__factoryplanner__/ui/dialogs/generic_dialogs.lua:211: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

Crash when setting limit on an ingredient

**Comment by ClaudeMetz** [comment]
Thanks a lot, fixed for the next release!
