### ISSUE TITLE
Migration shortcomings from 1.1.72 to 1.1.73 with BZ mods

### ISSUE THREAD

**Issue by gnemonix** [ClaudeMetz/FactoryPlanner#155]
### Problem Description

When testing the update for Factory Planner 1.1.72 to 1.1.73 today, I discovered a migration problem with a number of my "factories" (subfactories?). After reverting to 1.1.72 and inspecting what the failed entries had in common, I concluded that they all have "Exact machine Limits" enabled while set to the Traditional solver. I have the full BZ suite of mods, but I'm not sure if that is meaningful.

![broken_traditional_machine_exact_limits_enabled](https://github.com/ClaudeMetz/FactoryPlanner/assets/2272892/04204883-e00c-4f75-888f-d8811b819b49)

If I try to "Repair" the factory with the button at the bottom, all it seems to recover is the product amount and nothing else.

One work-around for this should be exporting all the factories and re-importing them on the newer version, but as of this post I'm currently running on Linux Wayland, and the clipboard is playing dumb. Switching to X11 should fix the clipboard issue.

One other very minor note: the list is displayed out-of-order from where they are in FP version 1.1.72

Thank you for your time.

--
Gnemonix

**Comment by ClaudeMetz** [comment]
Hello, thanks for the nice report. I tried to reproduce your issue with the exact machine limits, but to no success yet. It would be really helpful if you could upload your save for me to have a look at myself.

The list being in a different order is kind of hard to avoid with the migration, but it's a one-time thing, and will be stable going forward. Sorry about that!

**Comment by gnemonix** [comment]
Perhaps it's not as simple as I had hoped. If all else fails, I can just open a copy of the save in a second instance of Factorio and manually recreate everything.

Sorry for not providing the save file in the original post. It had exceeded the recommended maximum file size so I didn't try. Here's a google drive share link with a zip file containing both the Factorio save and the mod-settings.dat for a better reproduction chance.

https://drive.google.com/file/d/1I3QUW28T7mWXVuSAnDnkkp7sgKLeUsrc/view?usp=sharing

Thank you for your time.

--
Gnemonix

**Comment by ClaudeMetz** [comment]
Thanks for the very nice report, and sorry for not getting back to you earlier. I finally figured it out, more details in #169. Release out shortly.
