### ISSUE TITLE
Crash when trying to imput a specify number for the result of a recipe

### ISSUE THREAD

**Issue by Teneombre** [ClaudeMetz/FactoryPlanner#158]
### Problem Description

I'm making a KSE2 factory for core mining. So I set up a factory where the idea was to have 1 coal production per minute (just to have access to the recipe). I set the recipe up and then clicked on the ingredient to force it to consume 3600 core per minute. It crashed the game. I can't join the save game, it's too big.
The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 333)
__factoryplanner__/ui/main/production_handler.lua:203: attempt to index local 'item' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:203: in function '?'
	__factoryplanner__/ui/dialogs/generic_dialogs.lua:211: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/event_handler.lua:54: in function 'special_handler'
	__factoryplanner__/ui/event_handler.lua:133: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/event_handler.lua:54: in function 'special_handler'
	__factoryplanner__/ui/event_handler.lua:133: in function <__factoryplanner__/ui/event_handler.lua:114>
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13400093/factorio-current.log)

### Reproduction

1 set up a new factory
2 set up the recipe
3 click the ingredient on the line of the recipe you just made to modify the number
4 imput a number and validate
5 crash

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This one has been reported previously as #154 and #162, which has been fixed, with a release due soon.

**Comment by Teneombre** [comment]
Thanks. Sorry for the triple then. I'm not use to GitHub at all and I have yet to found how to see older report. Thanks for your works anyway :)

**Comment by ClaudeMetz** [comment]
Noo worries, appreciate reports nonetheless :)
