### ISSUE TITLE
Error after Alt-Rightclick on byproduct

### ISSUE THREAD

**Issue by Flurki** [ClaudeMetz/FactoryPlanner#159]
This error happened after I Alt-rightclicked on one of the byproducts (playing Pyanodons) at the top to open in Recipe Book. The error seems to be specific to the byproducts; I didn't have it happen for the ingredients for example. I also had just downloaded the latest update of Factory Planner. 
Log file: [factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13400292/factorio-current.log)

![Bild_2023-11-18_133446730](https://github.com/ClaudeMetz/FactoryPlanner/assets/45943427/a48ba205-941b-4244-aabf-42a4e7b968ac)

**Comment by ClaudeMetz** [comment]
I can't seem to be able to reproduce this easily unfortunately. Are you able to upload your save for me? Just drag it to a textfield on here and it should upload, if it's not too large.

**Comment by Flurki** [comment]
It seems to be resolved now, thank you! 
Weirdly when I first tried it with the new update both byproducts and ingredients at the top of the window either got linked to seemingly random other items in Recipe book or caused a crash again, but when I restarted the game it was all fine again.

**Comment by ClaudeMetz** [comment]
That one will be fixed in the next release as well, just for context. #191
