### ISSUE TITLE
Crash on adjusting ingredient to specific amount.

### ISSUE THREAD

**Issue by Windsinger1985** [ClaudeMetz/FactoryPlanner#162]
### Problem Description

Was trying to adjust the ingredients to specific amounts so i could make a separate production chain for the missing amounts. it seems it also happens on adjusting by products.

![FP-bug01](https://github.com/ClaudeMetz/FactoryPlanner/assets/13313548/fb498f82-060f-4345-b463-330428d4e52d)
![fp-bug02](https://github.com/ClaudeMetz/FactoryPlanner/assets/13313548/f974818d-6219-42ff-bcc9-551ab00fb6e0)
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13401234/factorio-current.log)

### Reproduction

Was trying to adjust the ingredients to specific amounts so i could make a separate production chain for the missing amounts. it seems it also happens on adjusting by products.

**Comment by ClaudeMetz** [comment]
Thanks for letting me know, there happens to be another report for the same issue, which I just fixed! #154
