### ISSUE TITLE
Repair Crash

### ISSUE THREAD

**Issue by diamondq** [ClaudeMetz/FactoryPlanner#166]
### Problem Description

Attempted to "Repair Factory" button on a recipe based on my SE-K2-248K run. 
Update: Repairing some plans did work fine, but attempting to repair my Oil Processing one fails (it's conceptually just a bunch of Oil Processing / Chemical Plants with beacons)

The mod Factory Planner (1.1.74) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 269)
__factoryplanner__/backend/calculation/matrix_engine.lua:825: attempt to get length of field '?' (a nil value)
stack traceback:
	__factoryplanner__/backend/calculation/matrix_engine.lua:825: in function 'find_linearly_dependent_cols'
	__factoryplanner__/backend/calculation/matrix_engine.lua:340: in function 'run_matrix_solver'
	__factoryplanner__/backend/calculation/matrix_engine.lua:232: in function 'get_linear_dependence_data'
	__factoryplanner__/ui/main/production_box.lua:30: in function 'refresh_solver_frame'
	__factoryplanner__/ui/main/production_box.lua:162: in function 'refresh_production_box'
	__factoryplanner__/ui/main/production_box.lua:305: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:308: in function <__factoryplanner__/ui/event_handler.lua:288>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/factory_info.lua:8: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/factory_info.lua:8: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13403462/factorio-current.log)

**Comment by ClaudeMetz** [comment]
Thanks for the report! For these kinds of bugs, a save file would be very helpful. If it's not too big, you can drop it in here to upload.

**Comment by diamondq** [comment]
Happy to. But unfortunately, it's 27 Megs. I can drop it anywhere you'd like.

**Comment by ClaudeMetz** [comment]
I don't have something setup for people to drop files into unfortunately, I'm looking into it but it's not very easy it seems. I'll get back to you should I figure something out.

**Comment by ClaudeMetz** [comment]
Hey so I setup a google drive folder, into which you can upload your save file, if you'd like.


https://drive.google.com/drive/folders/1JZErOFq7ibpk09dSeMV5BwPmG6xzhQNu?usp=sharing

**Comment by ClaudeMetz** [comment]
This is a dupe with #172, so let's make that one the main thread.
