### ISSUE TITLE
Crash when prioritizing output

### ISSUE THREAD

**Issue by fpvandoorn** [ClaudeMetz/FactoryPlanner#167]
### Problem Description

Crash when prioritizing a product

<img width="223" alt="image" src="https://github.com/ClaudeMetz/FactoryPlanner/assets/7376012/5f21eb1c-b0b5-462c-97a8-009a58695812">

```
The mod Factory Planner (1.1.74) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:233: attempt to index field 'Product' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:233: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:394: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

### Reproduction

1. Create any factory with a recipe with multiple outputs (e.g. `advanced oil processing`).
2. Left-click on the main output (e.g. `light oil`)
3. Crash!

**Comment by ClaudeMetz** [comment]
Thanks a lot for the detailed report, fixed for the next release!
