### ISSUE TITLE
Fewer steps to create a new factory

### ISSUE THREAD

**Issue by fpvandoorn** [ClaudeMetz/FactoryPlanner#168]
### Suggestion

In my opinion, it takes many steps to create a factory. 
In particular, I would like to make two mandatory steps optional:
* Requirement to give the factory a name
* Requirement to manually select the amount of the product.

Concrete suggestions:
* Allow empty name for a factory
* When the name of a factory is empty, and a product is chosen for that factory, automatically rename the factory to the product icon. For example, if I make a factory where the (first) output is water, the factory name becomes the icon `[fluid=water]`.
* When selecting a product of a factory, pre-fill the `amount` box with a reasonable number (e.g. 1 per second, or 10 per {current time unit}). Once the user has selected a product, automatically select the text in the `amount` (so that typing a number will cause the existing number to be removed - which makes this suggestion backwards-compatible with existing workflows).

**Comment by ClaudeMetz** [comment]
Hello, thanks for the suggestions! The first is actually a thing, you can get to it by shift-clicking the green '+' button, and you can make it the default action by enabling 'prefer product picker' in the pref pane (although that's a bad name, I'll change it soon).

I'm not so sure about pre-filling an amount. I guess it doesn't hurt. I'll think about it!

**Comment by fpvandoorn** [comment]
Oh, shift-click on the green + button is great! That already resolves most of this issue (and saves two clicks compared to my first two suggestions). 
I never considered reading the hover text of that button, since it didn't occur to me that could have any additional functionality.

**Comment by ClaudeMetz** [comment]
Yeah there's quite a lot of functionality hidden behind modifier-clicks, it's kind of how these 'power user' UIs tend to work. Not super discoverable, but quick to use once you got your bearings.

**Comment by ClaudeMetz** [comment]
I'll close this as most concerns are addressed or will be addressed.
