### ISSUE TITLE
crash on compact dialog

### ISSUE THREAD

**Issue by AndrewD22** [ClaudeMetz/FactoryPlanner#170]
### Problem Description

I'm playing with BZ mods + K2
This happens when I have compact view open and mouseover one of the ingredients.
Not always, but once in a while. Don't know why sometimes it works and sometimes it doesnt.

The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_hover (ID 178)
__factoryplanner__/ui/base/compact_dialog.lua:418: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/ui/base/compact_dialog.lua:418: in function 'handle_hover_change'
	__factoryplanner__/ui/base/compact_dialog.lua:496: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

**Comment by ClaudeMetz** [comment]
Hello, please try updating to the most recent version, released just today. It should address this issue. If not, please let me know.

**Comment by AndrewD22** [comment]
Thanks Will do. Just noticed there is new version and updating it now.
