### ISSUE TITLE
Crash selecting a floor 1.1.74

### ISSUE THREAD

**Issue by ajklotz** [ClaudeMetz/FactoryPlanner#172]
### Problem Description

The mod Factory Planner (1.1.74) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 367)
__factoryplanner__/backend/calculation/matrix_engine.lua:825: attempt to get length of field '?' (a nil value)
stack traceback:
	__factoryplanner__/backend/calculation/matrix_engine.lua:825: in function 'find_linearly_dependent_cols'
	__factoryplanner__/backend/calculation/matrix_engine.lua:340: in function 'run_matrix_solver'
	__factoryplanner__/backend/calculation/matrix_engine.lua:232: in function 'get_linear_dependence_data'
	__factoryplanner__/ui/main/production_box.lua:30: in function 'refresh_solver_frame'
	__factoryplanner__/ui/main/production_box.lua:162: in function 'refresh_production_box'
	__factoryplanner__/ui/main/production_box.lua:305: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:308: in function <__factoryplanner__/ui/event_handler.lua:288>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/factory_list.lua:88: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/factory_list.lua:88: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

Open FP and select an existing floor

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This is an issue that doesn't happen for everyone, so I'd love to be able to have a look at your save file to diagnose. You can upload it in here if it's not too big.

**Comment by ClaudeMetz** [comment]
(File `IR3 (1)`)

**Comment by ClaudeMetz** [comment]
Figured it out, thanks a lot for the report and patience. Fixed for the next release :)
