### ISSUE TITLE
Constant combinator crash K2 + SE

### ISSUE THREAD

**Issue by MaciekOle1** [ClaudeMetz/FactoryPlanner#174]
### Problem Description

Every time I am trying to create a blueprint with constant combinator with missing items the game throws following error at me:

Error while running event factoryplanner::on_gui_click (ID 1)
Key "type" not found in property tree at ROOT[0].control_behavior.filters[5].signal
stack traceback:
	[C]: in function 'set_blueprint_entities'
	__factoryplanner__/util/cursor.lua:10: in function 'set_cursor_blueprint'
	__factoryplanner__/util/cursor.lua:106: in function 'set_item_combinator'
	__factoryplanner__/ui/dialogs/utility_dialog.lua:398: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13416002/factorio-current.log)

**Comment by ClaudeMetz** [comment]
Thanks a lot, figured it out and fixed it for the next release! Only happens when there are modules involved.
