### ISSUE TITLE
Tutorial Click Crash

### ISSUE THREAD

**Issue by CelticFrog** [ClaudeMetz/FactoryPlanner#176]
### Problem Description

When attempting to click on the Tutorial button, it immediately crashes the game (I couldn't get a screenshot in time of the error messages, but they did pop up); then when I reconnected, the Tutorial screen did open.

### Reproduction

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13417919/factorio-current.log)
[Uploading world.zip…]()

**Comment by ClaudeMetz** [comment]
That's one weird crash, but your log file allowed me to figure it out. Thanks for the report! Fixed in the next release.

**Comment by CelticFrog** [comment]
I am nothing if not weird.
