### ISSUE TITLE
Crash on left clicking a product

### ISSUE THREAD

**Issue by theBurningVoid** [ClaudeMetz/FactoryPlanner#178]
### Problem Description

When I left click a product to set priority it causes a crash
57195.035 Error MainLoop.cpp:1391: Exception at tick 2790: The mod Factory Planner (1.1.74) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:233: attempt to index field 'Product' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:233: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:394: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

mostly just running the seablock pack and a couple helpers
Save File:
[1.1 SeaBlock winter 2023.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13418845/1.1.SeaBlock.winter.2023.zip)

### Reproduction

1. load save or start new game
2. open a factory
3. set a recipe
4. left click product as though you are trying to set priority

**Comment by mariusvn** [comment]
same here

**Comment by theBurningVoid** [comment]
I found a fix, not sure if this'll break anything else but I can't see why it would.
under the production handler file at line 233 
it seems that if you change line.Product.count to line.products.amount the error is removed and the desired behavior is restored
I have a picture of what is currently working for me, everything else is as factory planner version 1.1.74 came

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/12487960/1afeeb2e-3a4d-48a6-9558-695800fd6056)

**Comment by ClaudeMetz** [comment]
Yep, thanks everyone, that's an oversight on my end, fix will be out soon. Appreciate the nice report Void! Duplicate #167
