### ISSUE TITLE
Show ingredients in compact view

### ISSUE THREAD

**Issue by BlueOne** [ClaudeMetz/FactoryPlanner#180]
### Suggestion

I'd like to see in the compact view which ingredients I need for the total subfactory. The first part of building a subfactory for me is usually hunting down belts with the ingredients. Seeing which items I need in the compact view would make this more comfortable.

**Comment by ClaudeMetz** [comment]
Interesting idea, thanks for suggesting it. I would eat into the space you have for recipes, but I guess it'd be worth it.

**Comment by grossws** [comment]
You could also add checkbox to show/hide them in the compact view

**Comment by ClaudeMetz** [comment]
Yeah I think I'll do this with a checkbox, sounds reasonable enough.

**Comment by ClaudeMetz** [comment]
I implemented this for the next release, thanks again.
