### ISSUE TITLE
Crash after upgrading IR3 which removed many older items

### ISSUE THREAD

**Issue by ajklotz** [ClaudeMetz/FactoryPlanner#181]
### Problem Description

`The mod Factory Planner (1.1.74) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 384)
Unknown sprite "item/copper-foam"
stack traceback:
	[C]: in function 'add'
	__factoryplanner__/ui/main/production_table.lua:321: in function '?'
	__factoryplanner__/ui/main/production_table.lua:434: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:442: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:472: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:308: in function <__factoryplanner__/ui/event_handler.lua:288>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/factory_info.lua:8: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/factory_info.lua:8: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>`

### Reproduction

Clicked on Science Matrix floor and clicked on repair
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/9448682/07f4f723-ef68-4fb4-8244-530842f989a3)

**Comment by ClaudeMetz** [comment]
Thanks for the save, it's been invaluable. This is indeed an issue with the repair process not resetting everything fully in certain situations. Fixed for the next release, thanks for the patience!
