### ISSUE TITLE
Crash in 1.1.75 (after removing all items from subfloor)

### ISSUE THREAD

**Issue by kryojenik** [ClaudeMetz/FactoryPlanner#182]
### Problem Description

The mod Factory Planner (1.1.74) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 383)
__factoryplanner__/ui/main/production_table.lua:77: attempt to index field 'parent' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_table.lua:77: in function '?'
	__factoryplanner__/ui/main/production_table.lua:434: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:442: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:472: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:308: in function <__factoryplanner__/ui/event_handler.lua:288>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/production_box.lua:92: in function 'change_floor'
	__factoryplanner__/ui/main/production_box.lua:267: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/production_box.lua:92: in function 'change_floor'
	__factoryplanner__/ui/main/production_box.lua:267: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

If my memory is correct...

Was in a subfloor, deleted a bunch of recipes, then clicked to go up to the root level and it crashed.

I will attempt to reproduce again and report additional info if needed.

**Comment by ClaudeMetz** [comment]
Thanks for the report! I could not yet reproduce your particular issue, but I did notice a different, potentially related one. I'll fix that, and if you run into your issue again, please let me know :)

**Comment by kryojenik** [comment]
I was able to reproduce this 1.1.75.   Attached is a screen video of me triggering it in a new save file.  Only mod is FP.

The mod Factory Planner (1.1.75) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 206)
__factoryplanner__/ui/main/production_table.lua:77: attempt to index field 'parent' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_table.lua:77: in function '?'
	__factoryplanner__/ui/main/production_table.lua:434: in function 'render_lines'
	__factoryplanner__/ui/main/production_table.lua:442: in function 'refresh_production_table'
	__factoryplanner__/ui/main/production_table.lua:472: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:308: in function <__factoryplanner__/ui/event_handler.lua:288>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/production_box.lua:92: in function 'change_floor'
	__factoryplanner__/ui/main/production_box.lua:267: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:14: in function 'refresh'
	__factoryplanner__/ui/main/production_box.lua:92: in function 'change_floor'
	__factoryplanner__/ui/main/production_box.lua:267: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>



https://github.com/ClaudeMetz/FactoryPlanner/assets/845427/697a11f0-dd74-4b50-8adc-91440502c0f6

**Comment by kryojenik** [comment]
I meant to add description to the above addition.

While working in a subfloor and you remove the last line in that subfloor, all the lines in the parent floor (listed after the subfloor) are pulled into the display.  If you then remove the "added" lines, the subfloor identifier becomes "delete-able"

Either deleting the remaining subfloor heading, or going up to the parent results in a crash.

**Comment by ClaudeMetz** [comment]
Thanks for the further details, and yeah that is indeed what seems to be happening. I looked into it a bit already, but didn't find the cause yet. Will keep digging.

**Comment by ClaudeMetz** [comment]
This one took a bit of figuring out, but I did, so it'll work correctly with the next release, due out very soon. Thanks everyone for the reports.
