### ISSUE TITLE
Crash on hover

### ISSUE THREAD

**Issue by afwaltz** [ClaudeMetz/FactoryPlanner#183]
### Problem Description

Factorio crashes when I hover over the icons in the righthand column (ingredients list?) in the compact view.  It doesn't crash when I hover over the same column in regular view.
<img width="479" alt="factory planner" src="https://github.com/ClaudeMetz/FactoryPlanner/assets/151753910/714d9a09-d0f2-42c6-a09a-b26edcd17a62">

This is the error message:

The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_hover (ID 178)
__factoryplanner__/ui/base/compact_dialog.lua:418: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/ui/base/compact_dialog.lua:418: in function 'handle_hover_change'
	__factoryplanner__/ui/base/compact_dialog.lua:496: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report! This issue has been fixed with the most recent release (1.1.74), so please update and give that a go. If you still run into the issue, please let me know.

**Comment by afwaltz** [comment]
Thank you so much!  Fantastic mod, by the way.  Probably the greatest improvement to my gameplay in at least a year.

**Comment by ClaudeMetz** [comment]
Ha well happy to hear that :)
