### ISSUE TITLE
Space Exploration Crash

### ISSUE THREAD

**Issue by Nicolas050812** [ClaudeMetz/FactoryPlanner#185]
### Problem Description

Hello, I've been using the mod for quite a bit, and recently came across a lot of crashes in my sessions, my guess is that it has something to do with SE, since I've also used it in Krastorio 2 before and didn't have the slightest issue, this crashes happen when i try to do certain things, rather than by the mod just existing or just opening it, for example:

When i try to open the tutorial
Error while running event factoryplanner::Custom event (ID 272)
__factoryplanner__/backend/calculation/solver.lua:275: attempt to index local 'line' (a nil value)
stack traceback:
	__factoryplanner__/backend/calculation/solver.lua:275: in function 'set_line_result'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:157: in function 'update_line'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:241: in function 'update_floor'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:196: in function 'update_floor'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:269: in function 'update_factory'
	__factoryplanner__/backend/calculation/solver.lua:211: in function 'update'
	__factoryplanner__/ui/dialogs/tutorial_dialog.lua:24: in function 'dialog_open'
	__factoryplanner__/ui/base/modal_dialog.lua:171: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/title_bar.lua:113: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/title_bar.lua:113: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

When i tried to change the amount of iron plates i needed it also crashed, i don't have the crash log, but i also haven't managed to replicate it (unlike the one above, which seems to happen every time after i open a save file for a bit, but not when i just opened it, which is pretty weird) or anything, so its probably fine.

[Space Exploration Run 1.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13444974/Space.Exploration.Run.1.zip)

**Comment by ClaudeMetz** [comment]
Hello, appreciate the details and save file! This crash has been reported before (#176), and I think I have fixed it with version 1.1.75. Please try updating the mod and it should fix it for you. If not, feel free to open a new issue! The crash when editing amounts should also be fixed, btw.
