### ISSUE TITLE
You can paste more modules than the machine can accept if the receiving machine has no module set.

### ISSUE THREAD

**Issue by Kaimdrol** [ClaudeMetz/FactoryPlanner#187]
### Problem Description

When copy-pasting modules from one machine to another (via shift+rightclick and shift-leftclick) you can paste more modules than the machine can accept if the receiving machine has no module set.
See https://imgur.com/a/tqrU3LL for a screenshot.

Mod is Industrial Revolution 3.
2nd line is an advanced assembler, that can take 4 modules (here, 4 speed modules, 50% speed each = +200% speed).
3rd line is a small advanced assembler, a 1x1 assembler that can only accept one module.

Copy-pasting the 4 modules from the big assembler to the small one shows one module pasted but takes the 4 into account, for a 200% speed bonus on a small assembler. This works if the receiving machine has no module defined.

If you paste on a small assembler that has a module already set (any module) then the limit is taken into account and only one module is counted.

I just tested in the base game, with no mod other than factory planner, and you can copy 3 modules from a chemical plant and paste it on an electric furnace ; it will count all 3 modules.

**Comment by ClaudeMetz** [comment]
Oh good catch, I'll be sure to have a look at that. Looks like it just doesn't refresh the percentages when it should.

**Comment by ClaudeMetz** [comment]
Thanks again, fixed for the next release!
