### ISSUE TITLE
attempt to perform arithmetic on field 'module_limit' (a nil value)

### ISSUE THREAD

**Issue by GaretWebster** [ClaudeMetz/FactoryPlanner#189]
### Problem Description

Error while running event factoryplanner::on_configuration_changed
__factoryplanner__/backend/data/ModuleSet.lua:120: attempt to perform arithmetic on field 'module_limit' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/ModuleSet.lua:120: in function 'count_modules'
	__factoryplanner__/backend/data/ModuleSet.lua:47: in function 'insert'
	__factoryplanner__/backend/migrations/migration_1_1_73.lua:107: in function 'convert_floor'
	__factoryplanner__/backend/migrations/migration_1_1_73.lua:133: in function 'migration_function'
	__factoryplanner__/backend/handlers/migrator.lua:57: in function 'apply_migrations'
	__factoryplanner__/backend/handlers/migrator.lua:95: in function 'migrate_player_table'
	__factoryplanner__/backend/init.lua:243: in function <__factoryplanner__/backend/init.lua:228>

### Reproduction

All I need to do is attempt to load my save. Unfortunately I don't know what causes it but I am guessing the error report will make it clear how the value is nil.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This is a dupe with #173 actually, so we'll redirect there.
