### ISSUE TITLE
[1.1.75] Byproducts and ingredients linked to wrong items in Recipe Book

### ISSUE THREAD

**Issue by Flurki** [ClaudeMetz/FactoryPlanner#191]
### Problem Description

When Alt-rightclicking on the byproducts and ingredients at the top Recipe Book either opened the wrong items or the game crashed.
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13461692/factorio-current.log)
[save-flurki.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13461695/save-flurki.zip)

### Reproduction

1. Open FP with Ctrl+R
2. Alt-rightclick on byproducts or ingredients at the top. (Rightmost byproduct causes a crash.)

**Comment by ClaudeMetz** [comment]
Hi Flurki, thanks for letting me know! This is related to being on a subfloor, and my handling for that not being quite refined enough. Fixed for the next release.

**Comment by Flurki** [comment]
Very nice! :)
