### ISSUE TITLE
Crash while loading Space Exploration/K2 game

### ISSUE THREAD

**Issue by ajklotz** [ClaudeMetz/FactoryPlanner#195]
### Problem Description

`The mod Factory Planner (1.1.75) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_configuration_changed
__factoryplanner__/backend/data/ModuleSet.lua:120: attempt to perform arithmetic on field 'module_limit' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/ModuleSet.lua:120: in function 'count_modules'
	__factoryplanner__/backend/data/ModuleSet.lua:47: in function 'insert'
	__factoryplanner__/backend/migrations/migration_1_1_73.lua:107: in function 'convert_floor'
	__factoryplanner__/backend/migrations/migration_1_1_73.lua:90: in function 'convert_floor'
	__factoryplanner__/backend/migrations/migration_1_1_73.lua:90: in function 'convert_floor'
	__factoryplanner__/backend/migrations/migration_1_1_73.lua:133: in function 'migration_function'
	__factoryplanner__/backend/handlers/migrator.lua:57: in function 'apply_migrations'
	__factoryplanner__/backend/handlers/migrator.lua:95: in function 'migrate_player_table'
	__factoryplanner__/backend/init.lua:243: in function <__factoryplanner__/backend/init.lua:228>`

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This is a dupe with #173 actually, so we'll redirect there.
