### ISSUE TITLE
Crash when changing product values via "set product amount" 

### ISSUE THREAD

**Issue by DripThanos** [ClaudeMetz/FactoryPlanner#197]
### Problem Description

Hello. I am playing on a server with a few friends and this crash occurred when i edited a product amount via "target amount"
```
Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.75) caused a non-recoverable error.
Please report this error to the mod author.
Error while running event factoryplanner::Custom event (ID 304)
__factoryplanner__/ui/main/production_handler.lua:221: attempt to perform arithmetic on field 'percentage' (a nil value)
stack traceback:
        __factoryplanner__/ui/main/production_handler.lua:221: in function '?'
        __factoryplanner__/ui/dialogs/generic_dialogs.lua:211: in function 'dialog_close'
        __factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
        __factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
        [C]: in function 'raise_event'
        __factoryplanner__/util/raise.lua:27: in function 'close_dialog'
        __factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
        [C]: in function 'raise_event'
        __factoryplanner__/util/raise.lua:27: in function 'close_dialog'
        __factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>"
```
I tested it in singleplayer, producing the same error.
Note that i am using krastorio 2, and it seems to happen with the specific factory im using. The factory string will be included in the reproduction section of the report.

### Reproduction

1. Start a world
2. Open factory planner, and import the following string (requires krastorio 2) https://pastebin.com/g2QeYcHx
3. in the production section, right click to specify amount on "Basic Tech Card", before changing the target amount to any value other than 120 (tested with 60, and 0)

**Comment by DripThanos** [comment]
note that i have not tested it with other products, only the basic tech card

**Comment by ClaudeMetz** [comment]
Hm seems I can't reproduce it with your export string alone, probably because it's caused by something being weird in your save file. If you still have it, could you get it to me? That'd really help.

**Comment by fpvandoorn** [comment]
I got the same error. Here are steps to reproduce:
1. In a new game, make a new factory for iron chests, and make it using its only recipe
2. Now make a subfactory for this recipe, and make iron plates using its only recipe
3. Adjust the number of iron plates made in the subfactory (by right-clicking the product icon)
4. Adjust the number of iron chests made in the main factory 
5. Crash happens

**Comment by ClaudeMetz** [comment]
Thanks for the details, I'll give that a try.

**Comment by msrd0** [comment]
I also ran into this bug when changing the amount of an item with a subfactory attached.

![Screenshot_2024-01-02-13-10-44](https://github.com/ClaudeMetz/FactoryPlanner/assets/7853372/66c2c5d6-49bc-497b-8e28-d5a8562f451a)

**Comment by ClaudeMetz** [comment]
This feature was removed for 2.0, at least temporarily, so I'll mark this as stale since any reimplementation won't have the same issue. Really appreciate the detailed reports though, thank all of you.
