### ISSUE TITLE
Deleting non-selected factory deletes currently selected factory instead

### ISSUE THREAD

**Issue by nick-van-h** [ClaudeMetz/FactoryPlanner#203]
### Problem Description

When a factory (A) is selected and another factory (B) is deleted (either via RMB->Delete or Ctrl+RMB) then the currently selected factory (A) is deleted instead of the targeted factory (B)

### Reproduction

1. Select any factory
2. Delete any other factory
3. The selected factory gets deleted instead

**Comment by ClaudeMetz** [comment]
Oof that's a silly one, thanks. Same issue happened when deleting from the dialog actually. Fixed for the next release
