### ISSUE TITLE
There is no temperature for liquids and gases

### ISSUE THREAD

**Issue by Serrtt** [ClaudeMetz/FactoryPlanner#204]
### Problem Description

There is no temperature in liquids and gases for the materials of components necessary for consciousness.
At the same time, these temperatures are present in finished products and by-products. You can also select these liquids and gases with the desired temperature as a target for creation.
The lack of temperature in liquids and gases greatly complicates planning in matrix calculations

### Reproduction

Mod version 1.1.76
Game version 1.1.99

List of installed mods: in the attached file [mod-list.json](https://github.com/ClaudeMetz/FactoryPlanner/files/13530102/mod-list.json)
As an example, I give coke oven gas
Import line for factory:
eNrtV82K3DgQfpXF58jY3en5O2ZJIJAsA9nksgSjlsu2aFlyJHl+MvRp2RfYZ1nILc8weaNUSe7G9nTYgSFDAoE5jOv3q69KJfVNAledsb5oTenAJ2c3yZo7SM6SPM3T09PkSbIG5dmFdD 1X8iPYoFqmC9RwLpkyvATrUJqhw1OyN2upHVgfxRTnGMXPjPcKNIhNtI1SYYF7eQEM8wfjkzRH8XPdcC2gLF7zrvjdKDOEWqUr1MIFaFZK561c914aHXQYM0NlpeQ6Zlim9P3ij+cvw /fTEPmV0TV7qxFzbU2vS/YMy4vwF8FeoQFY1skOmDcsWg0JSH8uxcaxl0OFscA8S49Q5UwL7KMx7VA25XvzoQe++e3PBuPUzVAiked8GZEia+kJWfZrDGi51IWGy4DoJGSsuPDGXneKa73LmB5 TwlZqGRsQpavA6TlCfzfu12IorbsWhqvOGgHOSV0HVR6Sz1W15V0jhQsm2WBS9Q7Jxh7a+npQHN9RzDzzYCB12WO7dl55RGP5pbEQLbE70bSRdeNBNDvTfGw6C76YeMyUy6DswFujoG9xoJ DwfdFDXOQItJIV7MSLw14Hq9o7z7Srw9rFhLM76uVMjcOgw9nYE55jH08Pa0cI8n2Mzjg/6TbNeL5KtruZkkT+XzeJUNyR64s4aeiseUuU3P57+/n20+1/X/7+8g9KvWzBCa5QdZTh+HE 8gVdFZQEK6aGNwQbX1iBGzRxCpXPOPdQmDEClelmiqOSeFx6pRln0xkMh2w45kYAnztsetk/28ZzHCWNri8dvGo987xvuPa4n1UNnpaZDf4NMaOPDCBJj1pS98FNOzqMwqr2hDTkgaoxnXNqH VJeUUEmNe25NvrzFXUOZLHzopUXxIDlbHB1nxMX/gxJmA8zQgqy5Y6ssewx4y9XRPeERZ6PJYHn2OAjz0yyj7nvTFZUyxhKm/dgHAa5+vFgU2uJ/GHM6Bq9QEgIL3K7FvKxLblu8NHAa2G KGPXp8A/0wcbg8d+ZRQqlKnPfkrOLKAV61gs569EM3sAK05zVKkEE6iaIhgKOiXg+iuz2wDUwpj4Ix6CHeN1BXBtMXSrbS7xDh9d0rKIYnxB5DkL4Bakm0CIduizGEaVugziTJeHLuRfNoFbD 8F93fle5fZD8S2RYafAqzsL9xdf/wTHfXLACGK4GPJHwyT3m /o/sJWkBP4MntlOU/QxsC7M5cgqWfCHi/bgLuUTNmFg/tRtXTNTm6P+n78FNkhqOBVuL7cQaA4h3Mvn1g599v8e8reHX+Yg==

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This issue around fluid temps has been around for a while, and the fix is not trivial. I intend to get to it at some point, but not quite sure yet when that will be unfortunately. #95
