### ISSUE TITLE
Mod setting dissapeared?

### ISSUE THREAD

**Issue by kangzoel** [ClaudeMetz/FactoryPlanner#205]
### Problem Description

I just realized that factory planner no longer has mod setting
I need it to change the default time unit & to add recipe directly without naming it

**Comment by ClaudeMetz** [comment]
Hello, thanks for letting me know, although that's on purpose in this case. With a recent update, I unified all the mod's settings in the in-game preference pane, to make things easier. So you can just change the usual settings over there now.
