### ISSUE TITLE
factory planner NOT showing in mod settings

### ISSUE THREAD

**Issue by RubberDuck1977** [ClaudeMetz/FactoryPlanner#206]
Hello, is it just me or has someone else reported this?
when i go to settings and then mod settings there is no settings anymore for factory planner 
For now tested with the full pyanodon suite and pyblock, factorio library, factorio standard library

Very kind regards
Christophe

**Comment by ClaudeMetz** [comment]
Hello, thanks for letting me know, although that's on purpose in this case. With a recent update, I unified all the mod's settings in the in-game preference pane, to make things easier. So you can just change the usual settings over there now.
