### ISSUE TITLE
Crash [1.1.74]

### ISSUE THREAD

**Issue by USSX-Hares** [ClaudeMetz/FactoryPlanner#208]
### Problem Description

I was creating a planner for Freight Forwarding dredging setup.

```
Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:233: attempt to index field 'Product' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:233: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:394: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

### Reproduction

1. Add container of cobalt ore (requires cobalt ore & container) to the provided list
2. Add reciepe for it
3. Add reciepe for cobalt ore (requires sulfuric acid & cobalt crust, produces cobalt ore, byproducts iron ore, copper ore, stone, and cobalt crust)
4. Add stone, copper plates, and iron plate containers to the provided list
5. Select recipes for all of them (only one available -- required resource & empty container)
6. Click on the iron plates to select reciepe
7. Crash

Probably, error happens when you add a reciepe to a product that is made from a thing that is already a byproduct.

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/29100587/bf0199fc-dfb4-49de-916a-d9544cd06fa4)

**Comment by USSX-Hares** [comment]
The latest autosave was just a seconds before I made that terrible mistake. Enjoy.
https://disk.yandex.ru/d/VYXzkd_UMGObdw

(File is too large to be uploaded directly, so this is a cloud link)

**Comment by ClaudeMetz** [comment]
Thank you for the incredibly nice and detailed bug report, much appreciated! I think this one was actually fixed with the more recent releases, so please update the mod and see if that fixes it for you :)

**Comment by USSX-Hares** [comment]
> Thank you for the incredibly nice and detailed bug report, much appreciated! I think this one was actually fixed with the more recent releases, so please update the mod and see if that fixes it for you :)

yeah, i downloaded the newer version, and it was fixed, but it was already too late to write a new comment.

**Comment by ClaudeMetz** [comment]
All good, happy to hear it's working now.
