### ISSUE TITLE
Changing timescale no longer updates button labels

### ISSUE THREAD

**Issue by nick-van-h** [ClaudeMetz/FactoryPlanner#209]
### Problem Description

In previous version the buttons for switching [items/m, belts, wagons/m, items/s/factory] updated to the timescale selected on the bottom left, now they remain static while all other production numbers do change.

### Reproduction

Change the timescale on the bottom left pane

**Comment by ClaudeMetz** [comment]
Oh nicely spotted, thank you. Fixed for the next release.
