### ISSUE TITLE
Numbers of items/s/machine are incorrect

### ISSUE THREAD

**Issue by gomikuzu0010** [ClaudeMetz/FactoryPlanner#210]
### Problem Description

The numbers of items/s/machine (for estimating the numbers of inserters) are not divided by the number of machines. It's showing the numbers of items/s for the whole plan.

### Reproduction

Create a plan with multiple machines (making 1 belt of iron gear wheels for example)
items/s/assembler shows 30 plates/s & 15 wheels/s, regardless of the number of assemblers. (should be 2 plates/s/assembler & 1 wheels/s/assembler)
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/90431883/c1ffa218-f961-40c6-b712-af271694e11f)

**Comment by ClaudeMetz** [comment]
Hello, thanks for letting me know. This was reported previously as #177, and will be fixed with the next release.
