### ISSUE TITLE
Add Product UI to show products that are unlocked/researched

### ISSUE THREAD

**Issue by ajklotz** [ClaudeMetz/FactoryPlanner#214]
### Suggestion

Request toggleable setting to show only unlocked/researched products/recipes in the Add Product UI. Currently, every single product is shown to the user which can be quite a lot of items based on the mod you are playing. It would be cleaner to only show what the player has access to.

**Comment by ClaudeMetz** [comment]
I thought about this in the past, and it's not a bad idea, but it's kinda hard to implement I feel. I'll give it a go at some point though. Thanks for the suggestion.

**Comment by ClaudeMetz** [comment]
This is still something I am considering to do at some point, as part of a bigger system.
