### ISSUE TITLE
mouse-over highlighting behavior in the full GUI mode like compact view does

### ISSUE THREAD

**Issue by ajklotz** [ClaudeMetz/FactoryPlanner#215]
### Suggestion

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/9448682/1d75f9b1-7f74-45e2-88c1-38af74251fa3)

**Comment by ClaudeMetz** [comment]
I think I'll do this, but I do wonder if it could be annoying to people, and should thus be a preference. And before you say 'Yes!', mind that adding a preference is something I want to do as rarely as possible, and something needing to be a preference more often than not makes me just not add it.
