### ISSUE TITLE
Add product based on assembler speed

### ISSUE THREAD

**Issue by Wip-Sama** [ClaudeMetz/FactoryPlanner#218]
### Suggestion

Sometimes when you plan your base it's hard to have a good idea of how many items you want, in this case, the ability to select the amount of items to produce based on the speed of an assembler (or machine that can produce the item) would be really nice.

Actually, you could do this by doing some math but the point of a mod like this is exactly to avoid doing math so it defeated the purpose, tell me if you need more details or anything else.

I did some mod but I did not look at the code of this one for now so I can't tell if I can implement it myself and make pull request or not.
My profile on factorio: https://mods.factorio.com/user/Wip-Sama

**Comment by ClaudeMetz** [comment]
Hello! This has been suggested a few times in the past, and is indeed a very relevant idea. It's quite complicated to do in practice though. I have another card for this #93 with some details. I'll close this one as dupe.
