### ISSUE TITLE
LuaGuiElement API call when LuaGuiElement was invalid.

### ISSUE THREAD

**Issue by Quezler** [ClaudeMetz/FactoryPlanner#219]
### Problem Description

15946.846 Error MainLoop.cpp:1391: Exception at tick 15262462: The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 293)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/modal_dialog.lua:173: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:120: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:120: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
15946.846 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 293)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/modal_dialog.lua:173: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:120: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:120: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>"

### Reproduction

It happened during a k2 + space exploration when i was setting prod modules on an electrolysis plant. (wasn't able to reproduce it from memory right after)

**Comment by ClaudeMetz** [comment]
Hm that's a weird one, not sure I'll be able to figure it out without a reproduction. Will have a look though.

**Comment by ClaudeMetz** [comment]
This is likely related to multiplayer latency screwing with things. These are hard to find myself, and awkward to fix, but I'll definitely give it a go.

**Comment by Quezler** [comment]
yeah it's absolutely latency related, thanks for taking a look 🙂

**Comment by ClaudeMetz** [comment]
I gave fixing this a go for the next release. If anyone still runs into it, please open a new issue!
