### ISSUE TITLE
Add the ability to work simultaneously in multiplayer 

### ISSUE THREAD

**Issue by Hardnik** [ClaudeMetz/FactoryPlanner#220]
### Suggestion

Add the ability to work simultaneously in multiplayer with marks of completion, adding/removing and changing factories/floors.
Setting up shared or private factories/floors with read/write access.

**Comment by ClaudeMetz** [comment]
Thanks for the suggestion. This has been on the TODO list since the very beginning, but I still haven't gotten to it. More in issue #78
