### ISSUE TITLE
Copy paste modules sets wrong bonuses.

### ISSUE THREAD

**Issue by Joserichi** [ClaudeMetz/FactoryPlanner#221]
### Problem Description

When copying and pasting modules between different machines, with different max ammounts of modules, the bonuses the machine receives may not be correct.

### Reproduction

If you copy, for example 5 prod modules to a machine that only accepts 2, the icon will say only 2 modules, but the bonuses the calculations are based on, are the ones of the 5 prod modules, even if that's not possible. See the screenshot in case I'm not explaining myself properly:
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/11058644/e88e63ef-e592-4a17-b47a-56ea7b011cbb)

**Comment by ClaudeMetz** [comment]
Hello, have you updated to the most recent version? I addressed this recently #187 , but let me know if it still happens to you after an update!

**Comment by Joserichi** [comment]
Yeah, just checked and it's working properly after the update, sorry and thanks for this mod.

**Comment by ClaudeMetz** [comment]
No worries, better to report things twice rather than not at all!
