### ISSUE TITLE
Error on closing window

### ISSUE THREAD

**Issue by yalov** [ClaudeMetz/FactoryPlanner#224]
### Problem Description

Exception on close

The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 327)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/main_dialog.lua:147: in function 'set_pause_state'
	__factoryplanner__/ui/base/main_dialog.lua:109: in function 'rebuild'
	__factoryplanner__/ui/dialogs/preferences_dialog.lua:341: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

**Comment by ClaudeMetz** [comment]
Thanks, I'll have a look.

**Comment by ClaudeMetz** [comment]
Both of these are fixed for 2.0, thanks for the reports and the patience.
