### ISSUE TITLE
[Ultracube] crash on steam recipe with no temperature

### ISSUE THREAD

**Issue by Kaimdrol** [ClaudeMetz/FactoryPlanner#225]
### Problem Description

Ultracube is a brand new overhaul mod that has 4 steam "items" with various temperatures : unspecified, 165°, 215°, 1000°.

One of the recipes takes in unspecified steam and outputs 215° steam. When you try to add the steam ingredient as a recipe, FP crashes.

```
Error while running event factoryplanner::Custom event (ID 270)
__factoryplanner__/backend/data/Machine.lua:62: attempt to index field '?' (a nil value)
```

If you add steam with a specific temperature it doesn't crash.

See the screenshot book for more details.

https://imgur.com/a/mQYiuYc

ACTUALLY ! Just adding the unspecified steam is enough to crash FP.
Looking in recipe book, there's no recipe producing unspecified steam, but you don't get the "No existing recipe" alert...

[fp_crash_steam.txt](https://github.com/ClaudeMetz/FactoryPlanner/files/13765492/fp_crash_steam.txt)
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13765515/factorio-current.log)
[2 green science.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13765518/2.green.science.zip)

### Reproduction

Add unspeficied temperature steam to the planner
crash !

**Comment by ClaudeMetz** [comment]
Thanks, waiting on the 2.0 version of ultracube to verify whether it's still an issue.

**Comment by ClaudeMetz** [comment]
I had a look at this, and couldn't reproduce it. The temperature handling changed with 2.0 and likely fixed it. Thanks again.
