### ISSUE TITLE
Server Crash on my private server.

### ISSUE THREAD

**Issue by FlexibleGames** [ClaudeMetz/FactoryPlanner#227]
### Problem Description

115724.705 Error MainLoop.cpp:1391: Exception at tick 12610983: The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 254)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
        [C]: in function '__index'
        __factoryplanner__/ui/base/modal_dialog.lua:173: in function 'enter'
        __factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
        [C]: in function 'raise_event'
        __factoryplanner__/util/raise.lua:20: in function 'open_dialog'
        __factoryplanner__/ui/main/item_boxes.lua:11: in function 'add_recipe'
        __factoryplanner__/ui/main/item_boxes.lua:161: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
        [C]: in function 'raise_event'
        __factoryplanner__/util/raise.lua:20: in function 'open_dialog'
        __factoryplanner__/ui/main/item_boxes.lua:11: in function 'add_recipe'
        __factoryplanner__/ui/main/item_boxes.lua:161: in function 'handler'
        __factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
115724.710 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

### Reproduction

I have a custom server and game going, one of the mods I have installed is Space Exploration as well as Factory Planner. A few smaller mods, but SE is the big one. I am not sure why the server would try to run GUI stuff anyway.

**Comment by TimWeidner** [comment]
I can second this error, we also have a Space Exploration (+Krastorio) Server running. The Error is identical.

**Comment by ClaudeMetz** [comment]
Hi, thanks for the reports, and sorry for the late reply. This is the same issue as #219, so closing this as dupe.
