### ISSUE TITLE
Add products by machine number

### ISSUE THREAD

**Issue by MidnightAmethyst785** [ClaudeMetz/FactoryPlanner#228]
### Suggestion

So I was using this mod from the start of my new world. I am starting to make a basic mall and at this moment I am counting in machine number rather than items per second, items per belt, etc. It would be nice if we could add products by machine number. Had the same problem when adding my smelting columns to my factory in factory planner. Note: this is not the same as items per second per machine.

**Comment by ClaudeMetz** [comment]
Hello, this is an old suggestion that isn't as easy to implement as you'd think. To determine an item amount from a machine amount, you'd need to know which machine. And to know that, you'd need to know which recipe to even use. And so you'd end up just specifying a whole recipe line in the item picker, which doesn't make sense. You're better off using the machine limit feature, which was added for this purpose. I know that it's not very intuitive.

All that said, I have some ideas for how to address this differently: #93 
Closing this one as dupe
