### ISSUE TITLE
Force show used byproducts

### ISSUE THREAD

**Issue by MartenM** [ClaudeMetz/FactoryPlanner#229]
### Suggestion

When designing a factory, some mods heavily rely on chances and byproducts. The factory planner has the correct ratios, but it doesn't show the byproducts if they get used by the same process.

This leads users to believe that the output might be 3 belts, while it's more like 6 due to the byproducts. This leads to problems where belts get full with the finished product and byproducts. Or it might even clutter the line with unexpected products.

It would be nice if there were a button to show the byproducts, even if they get used in the same products again.

Let me know if this is something that could be implemented, or not.
Thanks for reading this!

**Comment by ClaudeMetz** [comment]
Hi, thanks for the suggestion and sorry for not getting back to you earlier. It's your lucky day, because this has been implemented for 2.0 :) #91
