### ISSUE TITLE
UI improvement and function improvement

### ISSUE THREAD

**Issue by Valoneu** [ClaudeMetz/FactoryPlanner#230]
### Suggestion

SO id like to say as i would like this mod so much but its hot pile of dogshit when playing K2SE.
1. Why cant i select all the unrestricted items i will need before i start clicking all the items in.
2. ok i fck up and then it says there are lineary dependant recipes, WHY WHY WHY WHEN i remove the last recipe it UNSELECTS ALL THE UNRESTRICTED RECIPES I HAVE SELECTED BEFORE :).
3. Also when selecting the unrestricted items let us SEARCH in there cause there is like 150 different items and it takes time to find what you need.
I am UNABLE to create a working plan for my factory AFTER 2 HOURS of trying and im losing my fcking mind.

**Comment by ClaudeMetz** [comment]
Hello, appreciate the suggestions. The matrix solver is kinda hard to improve unfortunately. I plan on rewriting it at some point, but until then I'm not sure I'll be able to solve any of these issues.
