### ISSUE TITLE
Factory Planner (1.1.78) and Ultracube steam ingredient clicking

### ISSUE THREAD

**Issue by Qon** [ClaudeMetz/FactoryPlanner#231]
### Problem Description

I tried to matrix solve first 3 science cards in mod "Ultracube" and got a crash.
Factorio 1.1.101

The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 277)
__factoryplanner__/backend/data/Machine.lua:62: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/Machine.lua:62: in function 'normalize_fuel'
	__factoryplanner__/backend/data/Line.lua:100: in function 'change_machine_to_proto'
	__factoryplanner__/backend/data/Line.lua:151: in function 'change_machine_to_default'
	__factoryplanner__/ui/dialogs/recipe_dialog.lua:94: in function 'attempt_adding_line'
	__factoryplanner__/ui/dialogs/recipe_dialog.lua:258: in function 'early_abort'
	__factoryplanner__/ui/base/modal_dialog.lua:154: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/item_boxes.lua:11: in function 'add_recipe'
	__factoryplanner__/ui/main/item_boxes.lua:161: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/item_boxes.lua:11: in function 'add_recipe'
	__factoryplanner__/ui/main/item_boxes.lua:161: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
![Screenshot from 2023-12-30 21-09-54](https://github.com/ClaudeMetz/FactoryPlanner/assets/828493/a9f3d4d9-0f65-4e1e-ac49-e87c4206007e)

### Reproduction

I'm Playing "Ultracube: Age of Cube" and just dowloaded Factory Planner to see if it could help me plan my factory with replication gel. After setting up Products of the first 3 science cards I selected the matrix solver and clicked the ingredients, for those with Matter Replication Gel recipe available I picked that. Water, Refined Rare Earth Metals and Stone as unrestricted (seems reasonable but I don't know what I'm doing. Why does the tooltip say unrestricted to the right and then moves them to the left when you unrestrict them?)
I have unlocked all techs with the first 2 science cards.
I think it was when I clicked ingredient: Steam that I got the crash.

**Comment by Qon** [comment]
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13799137/factorio-current.log)
Log file adde

**Comment by Qon** [comment]
This seems to be a dupe of https://github.com/ClaudeMetz/FactoryPlanner/issues/225

**Comment by ClaudeMetz** [comment]
Indeed, appreciate the report nonetheless!
