### ISSUE TITLE
Float numbers instead of decimal numbers in the compact view.

### ISSUE THREAD

**Issue by s0nycz3kk** [ClaudeMetz/FactoryPlanner#232]
### Suggestion

Hey there, thanks for the amazing mod.
One thing that bothers me is that the compact view doesn't show float numbers, could you please add this as a togglable option?

Thanks & happy new year!

**Comment by ClaudeMetz** [comment]
Hello, I get your issue, but I don't think it's a common enough one to warrant an option.
