### ISSUE TITLE
Matrix solver with subfactories

### ISSUE THREAD

**Issue by msrd0** [ClaudeMetz/FactoryPlanner#233]
### Suggestion

Currently, I cannot enable the matrix solver if two subfactories share a common recipe. However, it is quite common for me to place two simple recipes like iron gears into several subfactories, meaning, I want to know exactly how many machines I need per subfactory, not for the entire factory, as I usually don't put things like iron gears or copper wire on the bus. It is however extremely annoying that that means I cannot use the matrix solver.

I therefore have two suggestions:

1. Allow the user to specify that recipes in a subfactory only count towards the required amount of that particular subfactory, not the overal factory
2. Allow to enable the matrix solver only on certain (sub)factories, treating their subfactories as standalone recipes with fixed inputs/outputs, that way I can use the traditional solver for some floors and the matrix solver for other floors.

Also it would help a lot if I could tell an entire factory to produce ingredients for a set of other factories, but I could imagine that that might be harder to implement.

**Comment by ClaudeMetz** [comment]
Hello, sorry for not getting back to you earlier. This has been a somewhat common request about the matrix solver, however it is just not laid out to work with subfloors as you'd expect, and it's not an easy change. I have written down the idea in #97, but it'll have to be part of a larger rewrite if it ever comes to that.

As for the inter-factory relationships, that is something that's actually coming rather soon. The foundation is laid with the 2.0 update, and hopefully the ability to determine product amounts from other factories will follow soon after. See #82 for the card tracking this (although it isn't quite updated with my recent ideas yet).

I will close this card as its ideas are found elsewhere :)
