### ISSUE TITLE
Increasing production amount of subfloor to create item as byproduct crashes game for host.

### ISSUE THREAD

**Issue by Energeneer** [ClaudeMetz/FactoryPlanner#236]
### Problem Description

```
The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 263)
factoryplanner/ui/main/production_handler.lua:220: attempt to perform arithmetic on field 'percentage' (a nil value)
stack traceback:
  factoryplanner/ui/main/production_handler.lua:220: in function '?'
  factoryplanner/ui/dialogs/generic_dialogs.lua:211: in function 'dialog_close'
  factoryplanner/ui/base/modal_dialog.lua:187: in function 'exit'
  factoryplanner/ui/event_handler.lua:216: in function <factoryplanner/ui/event_handler.lua:189>
  [C]: in function 'raise_event'
  factoryplanner/util/raise.lua:27: in function 'close_dialog'
  factoryplanner/ui/event_handler.lua:54: in function 'special_handler'
  factoryplanner/ui/event_handler.lua:133: in function <factoryplanner/ui/event_handler.lua:114>
stack traceback:
  [C]: in function 'raise_event'
  factoryplanner/util/raise.lua:27: in function 'close_dialog'
  factoryplanner/ui/event_handler.lua:54: in function 'special_handler'
  factoryplanner/ui/event_handler.lua:133: in function <factoryplanner/ui/event_handler.lua:114>
```

Logfile: [factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13853380/factorio-current.log)

Mods: [mod-list.json](https://github.com/ClaudeMetz/FactoryPlanner/files/13853382/mod-list.json)

Rename to mod-settings.dat: [mod-settings.dat.txt](https://github.com/ClaudeMetz/FactoryPlanner/files/13853385/mod-settings.dat.txt)

Save File: [Vales SaLANi Extended.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/13853392/Vales.SaLANi.Extended.zip)

Screenshot of action before crash: Value was changed to 200, error occured on pressing Confirm
![Screenshot 2024-01-07 131519](https://github.com/ClaudeMetz/FactoryPlanner/assets/62573455/3d930a50-8be7-4091-9a42-a871e5760641)

### Reproduction

1. Plan a factory for tech cards that require rocket fuel
2. Plan rocket fuel in subfloor
3. Increase automatically calculated amount of fule to create it as byproduct
4. Game Crashes for Host, Kicking all players

**Comment by ClaudeMetz** [comment]
Hello, appreciate the very nice bug report, and sorry for the late reply. This feature was actually (temporarily probably) removed for 2.0, so I'll consider this resolved, as a future implementation will be all-new.
