### ISSUE TITLE
Machine count set to 0 after cancelling the Module popup

### ISSUE THREAD

**Issue by HopefullyICanChangeThatNameLaterOn** [ClaudeMetz/FactoryPlanner#237]
### Problem Description

The machine count is set to 0, after cancelling the Module popup and switchting factories back and forth. 
See attached video. 

### Reproduction

https://github.com/ClaudeMetz/FactoryPlanner/assets/40071710/237acd9f-2bc9-40fa-8e29-92ea40dfce74

**Comment by ClaudeMetz** [comment]
Thanks for the report, this was actually fixed for 2.0 as part of some other changes.
