### ISSUE TITLE
Crash when clicking different button

### ISSUE THREAD

**Issue by yoshi879** [ClaudeMetz/FactoryPlanner#238]
### Problem Description

Hi, I'd appreciate any help or insight you can give me and thank you so much for your time! The save file is titled "space BATO practice 2" 

Sorry it's 500+ MB....

So my Factorio crashes when I click on different buttons in Factory Planner.

When I click the Tutorial button I get this back:
The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 269)
__factoryplanner__/backend/calculation/solver.lua:275: attempt to index local 'line' (a nil value)
stack traceback:
	__factoryplanner__/backend/calculation/solver.lua:275: in function 'set_line_result'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:157: in function 'update_line'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:241: in function 'update_floor'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:196: in function 'update_floor'
	...ctoryplanner__/backend/calculation/sequential_engine.lua:269: in function 'update_factory'
	__factoryplanner__/backend/calculation/solver.lua:211: in function 'update'
	__factoryplanner__/ui/dialogs/tutorial_dialog.lua:24: in function 'dialog_open'
	__factoryplanner__/ui/base/modal_dialog.lua:171: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/title_bar.lua:113: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/title_bar.lua:113: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

When I click the little icon of the constant combinator next to where it says Ingredients I get back:
The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
Unknown signal type: entity
stack traceback:
	[C]: in function 'set_blueprint_entities'
	__factoryplanner__/util/cursor.lua:10: in function 'set_cursor_blueprint'
	__factoryplanner__/util/cursor.lua:106: in function 'set_item_combinator'
	__factoryplanner__/ui/main/item_boxes.lua:217: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

When I click on one of the buttons designating resources under the "Product" column (In between Power and Byproducts) I get back:
The mod Factory Planner (1.1.73) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:233: attempt to index field 'Product' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:233: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:392: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

``
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13855002/factorio-current.log)

**Comment by ClaudeMetz** [comment]
Thanks, those are indeed quite a few issues. Will have a look.

**Comment by ClaudeMetz** [comment]
These are pretty old now, and I think they should have been addressed. Please open a new issue if you run into any further problems.
