### ISSUE TITLE
Crash to desktop when opening factory planner

### ISSUE THREAD

**Issue by SMuffatti** [ClaudeMetz/FactoryPlanner#239]
### Problem Description

In an ongoing game that's kept up to date, clicking to open factory planner crashes the game. The issue can only be executed by one user and the other users can open Factory Planner without issue. 
[factorio-current (1).log](https://github.com/ClaudeMetz/FactoryPlanner/files/13863409/factorio-current.1.log)

I'll include the save file in the google drive and label it as smuffatiCTD

### Reproduction

1. Load into saved multiplayer game. (Also impacts saved game).
2. Try and open Factory Planner.

**Comment by ClaudeMetz** [comment]
Sorry for not getting to this before, but I can't reproduce this, and 2.0 might address it. Please open a new issue should this happen again.
