### ISSUE TITLE
Py Coke Oven Gas Not Recognized by Factory Planner

### ISSUE THREAD

**Issue by ttyler3** [ClaudeMetz/FactoryPlanner#241]
### Problem Description

Pyanodons mods: "No existing recipe produces this item" for coke oven gas, which is a byproduct of advanced coke processing from raw coal in the high pressure furnace.

### Reproduction

    Download and enable Factory Planner
    Run mod in step 1 with pycoalprocessing (or in my case, the full py suite)
    Unlock the coke recipe in the high pressure furnace
    Observe that the byproduct of this recipe is "coke oven gas", which is used to warm up stone bricks for hot air
    Open Factory Planner
    Tell it to make "coke oven gas"
    a. Select a recipe with hot air
    b. Click on "coke oven gas"
    Message appears saying "No existing recipe produces this item"

**Comment by ClaudeMetz** [comment]
Thanks, waiting on the 2.0 version of Py's to verify whether it's still an issue.

**Comment by ClaudeMetz** [comment]
This works on 2.0, was probably related to fluid temperature issues.
