### ISSUE TITLE
Missing recipe from exotic industries

### ISSUE THREAD

**Issue by AardNaricain** [ClaudeMetz/FactoryPlanner#247]
### Problem Description

Exotic industries just added a new building, an excavator, that only mines stone with no ability to select a recipe. There are already a couple other buildings like that, stone quarries, but this new one doesn't show up in the list of possibilities when choosing where stone comes from within factory planner.

[Here is where the new prototype file was committed](https://github.com/PreLeyZero/exotic-industries/commit/b48e57adf593140bcd31151d2ced93c14b2c5725#diff-f25fdbd3bd51846bc84519cabb56c40d6bd0142b163b3ba0fe9b5506a626bf47)

### Reproduction

1. Install exotic industries 0.5.7
2. Open factory planner and create a new factory to produce stone, any amount
3. Choose how to produce stone. Make sure hidden recipes and unresearched recipes are enabled.
There are three recipes producing stone primarily that show up, and three that produce stone as a byproduct. The production using  an excavator is missing.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. With 2.0 around the corner, I'll wait until I can test it there and see if it's still an issue.

**Comment by ClaudeMetz** [comment]
I had a look at this, seems like EI uses some scripting for this entity, which I currently can't support in Factory Planner. I'll consider this issue closed then.
