### ISSUE TITLE
[pyanodon] Crash with floating point fluid tempature

### ISSUE THREAD

**Issue by notnotmelon** [ClaudeMetz/FactoryPlanner#248]
### Problem Description

Hi friends.

Crashing on game start for the following recipe:
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/30201457/8a3ed06b-202e-4529-92bc-9eaf73e3fd49)

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/30201457/d1cbf02a-01fc-46ba-ac0e-820f0684e22e)

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/13980594/factorio-current.log)

**Comment by ClaudeMetz** [comment]
Huh that's weird. Not sure if that's actually related though. I will close this for now, as a lot changed around this logic for 2.0. Should it happen again, let me know!
