### ISSUE TITLE
Choosing wrong unrestricted item leads to 'linearly dependent recipes' stuck state

### ISSUE THREAD

**Issue by robeady** [ClaudeMetz/FactoryPlanner#250]
### Suggestion

In matrix mode, if you choose the wrong item to make unrestricted, this can result in 'linearly dependent recipes detected'.

The way you want to resolve this situation is to revert the selection of the last unrestricted item.

But you cannot do this. Instead, you must either
- remove an entry from the planner to make the recipe not linearly dependent any more - not what you want to do because maybe this is not the problem, and also it may be hard to find the problematic line
- switch from matrix back to traditional mode - but then you lose any lines in the planner that handle byproducts.

This is very frustrating. In the linearly dependent recipes scenario, the player should be able to change the unrestricted items to solve the error.

**Comment by xlenstra** [comment]
One thing that makes it slightly less bad is that instead of removing recipes you can also disable them. Still not ideal, but at least it's easier to enable them afterwards again

**Comment by ClaudeMetz** [comment]
Isn't this solved with the new matrix settings UI, where you can change things without the dialog popping up?

**Comment by ClaudeMetz** [comment]
If this is still an issue, please open a new issue, thanks.
