### ISSUE TITLE
Crashes when adding a module on kovarex enrichment process 

### ISSUE THREAD

**Issue by BM123499** [ClaudeMetz/FactoryPlanner#251]
### Problem Description

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/14018505/factorio-current.log)
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/48841672/13ad2f41-165c-4310-8c11-5e7de60d3c53)

It crashes the game when I click to add a module on the kovarex enrichment process using a centrifuge.

### Reproduction

1. Added the mod into an existed gameplay.
2. Planned the following recipe requesting 60 uranium-235 and 60 uranium-238 per minute
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/48841672/545256cf-6741-4815-acae-8f3d17892104)
3. Clicked on "add module" for the kovarex enrichment process.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This one will be hard to replicate without the exact modset. Seeing as 2.0 is around the corner and so much changed, I'll close this report for now, and if you run into this again, please let me know.
