### ISSUE TITLE
Freezes when accidentally typing in any of the letters "æøå"

### ISSUE THREAD

**Issue by Andreasfv** [ClaudeMetz/FactoryPlanner#254]
### Problem Description

Ive had this happen twice. The UI locks up for an ungodly amount of time whenever I accidentally type in Æ Ø or Å into the naming of a factory. The game is still running fine in the background, stuff is animated and working just fine. I on the other hand are completely deadlocked in the UI. I cannot close the Factory Planner or do anything. I am writing this while its being locked for the moment, but last time it happened it stopped maybe 15 minutes later, I'm not entirely sure as for how long its going on.

### Reproduction

I believe you can just start up a game and type in any of the Æ Ø or Å letters into the factory planners create new factory naming input.

**Comment by ClaudeMetz** [comment]
Thanks for the report. I can't seem to reproduce this unfortunately, and if I could I think it would be a game bug, not mine. Closing the issue, if it happens again feel free to open up a new issue.
