### ISSUE TITLE
Crash when specifying quantity of ingredient

### ISSUE THREAD

**Issue by ahp378** [ClaudeMetz/FactoryPlanner#259]
### Problem Description

```
The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 213)
__factoryplanner__/ui/main/production_handler.lua:220: attempt to perform arithmetic on field 'percentage' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:220: in function '?'
	__factoryplanner__/ui/dialogs/generic_dialogs.lua:211: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
```

### Reproduction

While attempting to specify a manual value for a recipe ingredient, a crash occurs.

Other mods installed:
Afraid of the Dark
Better Roboport
Bottleneck
Constructoin Planner
Expand Tooltip
Factorio Library
Factorio Reach
Factory Planner
Infinite Technologies
LTN - Logistic Train Network
Rate Calculator
Squeak Through
Text Plates
Train Log
VehicleSnap
Waterfill

**Comment by Aghanimoff** [comment]
Same problem (version 1.1.78)

https://github.com/ClaudeMetz/FactoryPlanner/assets/81116726/9a329042-b3ce-4ef9-b390-309b7f294dca

**Comment by Windsinger1985** [comment]
Same problem, Bobs mod, adjusting the value of a product crashed it now a few times.
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/13313548/6a41a028-91d7-477e-9776-00d423982c6f)

**Comment by ClaudeMetz** [comment]
Hello, appreciate the reports. This feature was removed for 2.0 (temporarily), so any new implementation isn't likely to have the same issue.
