### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aplyde** [ClaudeMetz/FactoryPlanner#260]
### Problem Description

When I entered a manual value for a recipe output I crashed (possibly after messing up the production line earlier? The clip is a bit longer to show what I did)

https://cdn.discordapp.com/attachments/848015118373486592/1207078092900933652/Factorio_2024.02.13_-_22.23.47.02.DVR_-_Trim_-_Trim.mp4?ex=65de5613&is=65cbe113&hm=039206b2d74caee4e14f608677c61e504884ae9b381712e86a5a05658f276d98&

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. The Discord link is unfortunately no longer visible. Still, I think I know what you are referring to, and the issue has been addressed for 2.0
