### ISSUE TITLE
Crash in a hosted MP game, was editing a production line

### ISSUE THREAD

**Issue by VzioNARY** [ClaudeMetz/FactoryPlanner#262]
`
The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 286)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/modal_dialog.lua:173: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:120: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:120: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
`

**Comment by saqneo** [comment]
+1 similar crash, did not get stack, but it occurs pretty often when two or more people are using the mod at the same time. We all thought it was a result of our own click (we clicked at the same time apparently), so maybe there is a synchronization issue in some function

**Comment by ClaudeMetz** [comment]
Hi, this is the same issue as #219, so closing as dupe. Thanks for the reports.
