### ISSUE TITLE
In py mod, some fluid recipes with temperature cannot be found.

### ISSUE THREAD

**Issue by ksimple** [ClaudeMetz/FactoryPlanner#264]
During the process of generating heat, the recipe for producing temperature-bearing coke oven gas cannot be found, and thus cannot be quantified.

**Comment by ksimple** [comment]
helmod works on this

**Comment by ksimple** [comment]
I used a localized py version in Chinese

**Comment by ClaudeMetz** [comment]
Hi, yeah temperature stuff is problematic at the moment. I am very close to a solution though, which will hopefully be out shortly after 2.0. It's described a bit in #95, so closing as dupe.
