### ISSUE TITLE
In py mode, when the mining beast digs natural blue corundum, the machine's speed calculation is abnormal.

### ISSUE THREAD

**Issue by ksimple** [ClaudeMetz/FactoryPlanner#266]
### Problem Description

when the mining beast digs natural blue corundum, the machine's speed calculation is abnormal.

**Comment by ksimple** [comment]
I used a localized py version in Chinese

**Comment by ClaudeMetz** [comment]
Hi, thanks for the report. This seems like an issue with Py doing scripted stuff, which I don't have a solution for yet. I might have a long-term one in #332 though, so I'll be closing this for now.
