### ISSUE TITLE
Matrix solver only works on individual levels and not whole production line

### ISSUE THREAD

**Issue by protocol-1903** [ClaudeMetz/FactoryPlanner#268]
### Suggestion

My idea is that the matrix solver would work on a per-level basis, i.e. you can use the matrix solver to create blue circuits and nest each circuit level, and then copper wire assemblers will only apply to that specific level on the planner. This can be achieved with the normal planner in this case, but for any mod with circular recipes that are nested, this becomes impossible. If it's too much work to do at the minute, i can make a pull request and take a look.

**Comment by ClaudeMetz** [comment]
Hi, this is quite a complex topic unfortunately, that won't be easily changed. It's on my TODO list to address at some point, but it'll not be soon. See #233 for a similar proposal.
