### ISSUE TITLE
non-recoverable error,  tried to calculate how much sulphuric 

### ISSUE THREAD

**Issue by Utilka** [ClaudeMetz/FactoryPlanner#272]
### Problem Description

The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 221)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
  [C]: in function 'index'
  __factoryplanner/ui/base/modal_dialog.lua:173: in function 'enter'
  factoryplanner/ui/event_handler.lua:209: in function <factoryplanner/ui/event_handler.lua:189>
  [C]: in function 'raise_event'
  factoryplanner/util/raise.lua:20: in function 'open_dialog'
  factoryplanner/ui/main/production_handler.lua:245: in function 'handle_item_click'
  factoryplanner/ui/main/production_handler.lua:423: in function 'handler'
  factoryplanner/ui/event_handler.lua:157: in function <factoryplanner/ui/event_handler.lua:114>
stack traceback:
  [C]: in function 'raise_event'
  factoryplanner/util/raise.lua:20: in function 'open_dialog'
  factoryplanner/ui/main/production_handler.lua:245: in function 'handle_item_click'
  factoryplanner/ui/main/production_handler.lua:423: in function 'handler'
  factoryplanner/ui/event_handler.lua:157: in function <factoryplanner/ui/event_handler.lua:114>

### Reproduction

we tried to calculate how much sulphuric acid is needed for the recipe

**Comment by ClaudeMetz** [comment]
Hello, thanks, duplicate of #219
