### ISSUE TITLE
Ability to group factories and move them aorund more easily

### ISSUE THREAD

**Issue by xlenstra** [ClaudeMetz/FactoryPlanner#275]
### Suggestion

So, I create a lot of factory plans using this mod, resulting in my current playthrough of seablock having over 200 different factories, which are also ordered roughly by the type of product they are making. This has resulted in me seeing space for improvement in both the sorting and movement of factories in the list on the left, as well as recipes inside a factory. I'll discuss these proposed improvements here, including how the UI could be implemented.

1) Allow for moving factories and recipes by dragging instead of clicking on tiny arrows, which can only move exactly 5 steps at the same time. Similarly to how you can drag stations & conditions inside the train schedule manager, I propose replacing the arrows with surfaces that allow for dragging the recipes/factories with sections of vertical striped lines. These could either be on the left as they currently are, or on the right. I'm personally more favourable to the left, so that the factory names can still expand of the screen to the right.

2) Allow for grouping factories together. The idea is to allow factories to be placed together in a kind of 'factory group'. This factory group has a name, and can be folded in to hide all the factories contained inside, displaying only the name. Adding or removing factories to and from this group can than be done using the drag-and-drop mentioned in idea 1). It should of course still be possible to have factories outside of groups.
The UI I see is having a little arrow between the drag/drop section and the names of these 'factories', which points down if it the 'factory group' is unfolded, with all names being slightly indented to signify membership of the group. Clicking the arrow would instead make it point to the right and hide all the factories inside.

3) Some of the feature requests mentioned in https://mods.factorio.com/mod/factoryplanner/discussion/637cd9983efc5fe1294a1941 can also be more easily implemented using the ideas described above. If you also make subfloors simply a header that can be folded out individually, and allow recipes/subfloors to be dragged and dropped everywhere, that would easily implement the first two requests. The last request can be implemented by, for example, allowing cross-copy-pasting of factories and subfloors: copying a factory from the list and pasting it in the recipe section of the factory could create a subfloor containing exactly those recipes.

**Comment by xlenstra** [comment]
As an additional request: ctrl+click on the 'duplicate factory' button should insert the duplicated factory right beneath the currently open factory, similarly to how ctrl+click works in other places

**Comment by ClaudeMetz** [comment]
Hi, thanks for the detailed suggestions!

1. Dragging is unfortunately not possible within the API, it'd otherwise be the obvious choice.
2. This is something that's been suggested before, it's sort of like having folders for factories. It's a good idea, but the UI is challenging without drag and drop. What the 2.0 release will have however is a slightly different way to group factories together, maybe that one will work for you.
3. Yep, but no dragging, :(

The duplicate factory thing is a good idea, implemented for 2.0
