### ISSUE TITLE
Resizing the entirety of the factorio window decreases the amount of rows in the planner

### ISSUE THREAD

**Issue by xlenstra** [ClaudeMetz/FactoryPlanner#276]
### Problem Description

I don't like playing Factorio in fullscreen mode, so I just have a maximized window. However, when dragging the map I sometimes accidentally resize the entire window. If I happen to have the factory planner open, this reduces the amount of rows in the factory planner. However, when resizing the window again to its original size, the reduced number of rows stays, and I have to manually go into the preferences menu and change it.

Playing on Kubuntu 22.04

### Reproduction

1. Start Factorio
2. Disable fullscreen mode
3. Open the factory planner
4. Set the number of rows in the preferences to something high, for example 22
5. Resize the window, making it smaller
6. Resize the window, making it larger
7. Note how the number of rows in the planner is now permanently reduced to 14

**Comment by ClaudeMetz** [comment]
Hello, appreciate the report. This isn't quite a bug, it's an intended feature to avoid the main window being too big to interact with. I do see how it can be annoying that this happens. I think I'll just disable that feature, why not.
