### ISSUE TITLE
Widen Comment Section of Recipe Comments

### ISSUE THREAD

**Issue by udkudk** [ClaudeMetz/FactoryPlanner#277]
### Suggestion

Currently Recipe Comments Sections are really small. It's really hard to write long sentences. See below:
![Screenshot 2024-03-19 202859](https://github.com/ClaudeMetz/FactoryPlanner/assets/164061079/2b8af858-3963-4879-a38e-a72c0e6df6bf)
It would be better to make it either;
1- Adding a new setting to manual adjusting of Recipe Comments Section Length by Players.
2- auto-adjust Recipe Comments Section Length depending on Resolution and/or GUI scale.

1st one would be much better and easier in implementation both as Author and Players.

If possible Height Modifications to Text Box would be awesome as well.

Thanks for this awesome mod.

-udkudk

**Comment by ClaudeMetz** [comment]
Hello, thanks for the suggestion. Adjusting it dynamically is really difficult, there's not a good way to know how much empty space there is. Adding adjustability is just too much, this is a very niche feature, so I'll have to leave it as-is as a good middle ground.
