### ISSUE TITLE
Hidden recipes

### ISSUE THREAD

**Issue by radoslavkarlik** [ClaudeMetz/FactoryPlanner#280]
### Suggestion

Hi, can you add option to show hidden recipes like in Recipe Book? I would like to calculate and compare various energy production recipes. The energy is like an item itself in the mod. The mod is Nullius.

**Comment by ClaudeMetz** [comment]
Hello, this is tricky because hidden recipes are used to hide all kinds of crap that is not actually usable. This is something that needs specific mod compatibility, which I have a long-term plan for at #332. Thanks for the report, but I can't really do anything about it for the moment.
