### ISSUE TITLE
A nuclear reactor as a machine, that creates "Used up fuel cell"

### ISSUE THREAD

**Issue by yalov** [ClaudeMetz/FactoryPlanner#283]
### Suggestion

* add support of "Uranium fuel cell" -> "Used up uranium fuel cell" in the Nuclear reactor.

expecially useful for all atomic/nuclear overhauls.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the suggestion. This would indeed be neat to have, but adding support for all the various ways to make power is a huge undertaking, and not core to the mod in my opinion. Not saying I'll never do it, I have #81 as a note for this, so I'll be closing this card for now.
