### ISSUE TITLE
Crash when interacting with module on specific recipe

### ISSUE THREAD

**Issue by mihaild** [ClaudeMetz/FactoryPlanner#285]
### Problem Description

Crash message:
The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/util/clipboar
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/14937816/factorio-current.log)
d.lua:27: attempt to index local 'object' (a nil value)
stack traceback:
	__factoryplanner__/util/clipboard.lua:27: in function 'copy'
	__factoryplanner__/ui/main/production_handler.lua:176: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
[crash.log](https://github.com/ClaudeMetz/FactoryPlanner/files/14937823/crash.log)
[sandbox - se.18.space rail14.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/14937830/sandbox.-.se.18.space.rail14.zip)

### Reproduction

1. Load the save.
2. Open the factory planner, factory with beryl ingots (second from the end)
3. On iron plate production, right click on machine, or right click/shift-right click/ctrl-right click on module.
Game crashes with error above.

Observation: if before doing this I try to edit anything - reorder recipes, change machine for other step or even for different factory, and after that try to edit recipe for iron plate - it doesn't crash.

**Comment by ClaudeMetz** [comment]
Hi, thanks for the report. This is an oversight from my side that I've fixed for 2.0 actually, which'll be out soon!
