### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AMAURY-Emilien** [ClaudeMetz/FactoryPlanner#286]
### Problem Description

when I right click where I draw the square red, one sec before I do the same but I fast cancel the operation by presh echap I think
![12-04-2024-02h20m](https://github.com/ClaudeMetz/FactoryPlanner/assets/115998830/2da26ca1-141c-453d-98fe-f03062f71a60)

### Reproduction

when I right click where I draw the square red, one sec before I do the same but I fast cancel the operation by presh echap I think
It's the second times that I have this bug with factory planner, but the first I forgette to screen the error, and I don't remember if it was with the same thing

**Comment by AMAURY-Emilien** [comment]
[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/14952630/factorio-current.log)
One log of factorio

**Comment by ClaudeMetz** [comment]
Thanks for the report, this is a long-running issue I fixed for 2.0, due out soon :)
