### ISSUE TITLE
Perhaps just a visual bug?

### ISSUE THREAD

**Issue by npuldon** [ClaudeMetz/FactoryPlanner#287]
tooltip states 'per second' as does the preferences (this is brand new factory), yet the rate button says 'item/m'.  Perhaps I am in some corner case that wasn't accounted for where a factory was started with 'per minute', preferences were changed to per second, and a new factory was created yet the visual bug persists.

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/11417724/28e10886-775d-4e48-84a8-84630285a984)
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/11417724/4744ad64-0485-484c-9122-ccd87f11fd39)

**Comment by ClaudeMetz** [comment]
Appreciate the details, and sorry for the late reply. This system was partially reworked for 2.0, so I am pretty sure this was fixed as part of that. If it happens again once 2.0 drops, please open up a new report.
