### ISSUE TITLE
Dragging feature

### ISSUE THREAD

**Issue by LetsOffBrains** [ClaudeMetz/FactoryPlanner#288]
### Suggestion

I'd like the ability to drag around recipes and factories to arrange them to my liking.

I've read that you have hard time finding place for more buttons. So there i suggest to replace those extremely tiny up-down arrows to drag-bars like train stops have.

I hope it's not a hard and time consuming task and will be implemented soon.

**Comment by curiosity-a** [comment]
Factorio modding API does not allow for dragging like that. So "hard" would be putting it lightly.

**Comment by ClaudeMetz** [comment]
Yeah like curi said, dragging isn't really possible. I'd love to have that over the silly up and down buttons. We'll see, maybe the API gets the feature at some point. Closing as impossible for now.
