### ISSUE TITLE
Exotic Industries - Deep drill fuel

### ISSUE THREAD

**Issue by torquadon** [ClaudeMetz/FactoryPlanner#290]
### Problem Description

Exotic Indusries mod pack - Deep Drill needs Drill Fluid, but in planner it claims it does not use any fuel.

### Reproduction

Any recipe with Deep Drill seems to have that issue. I suspect Advanced Deep Drill will have the same issue.

**Comment by torquadon** [comment]
It also seems to be showing a number of drills needed incorrectly. Hellmod shows twice as many and I believe this is correct

**Comment by ClaudeMetz** [comment]
Hi, let's wait until exotic industries makes it to 2.0 and see if the issue persists.

**Comment by ClaudeMetz** [comment]
Fueling of stuff is overhauled in 2.0, so I expect this to be resolved.
