### ISSUE TITLE
Gui Click => Crash on Leaching plant 1

### ISSUE THREAD

**Issue by LoupAndSnoop** [ClaudeMetz/FactoryPlanner#292]
### Problem Description

In seablock, I clicked on the icon to modify a leaching plant 1 to a different tier in the planner. Instead of openning the little menu, it crashed with this message:

The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:84: attempt to index local 'machine' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:84: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

In seablock, I clicked on the icon to modify a leaching plant 1 to a different tier in the planner. Instead of openning the little menu, it crashed with this message. It happens every time I try to click on the leaching plant 1.

**Comment by ClaudeMetz** [comment]
Thanks for the report, I'll try to reproduce once Seablock hits 2.0.

**Comment by ClaudeMetz** [comment]
Quite a bit of stuff around this changed with 2.0, so I'll consider this closed until another instance of it occurs. Thanks again,
