### ISSUE TITLE
Target item quantity bonus

### ISSUE THREAD

**Issue by Shadaris** [ClaudeMetz/FactoryPlanner#293]
### Suggestion

When you right click on an item to adjust your target amount would it be possible to add in a secondary box.

The First box (Target) would be the target the same as is currently. Ideally a slider would be added here (similar to buildings) "OFF" would function as default and auto update based on preceding recipes (locking the input box). "ON" would hard set to the number you specify.

The Second Box (Bonus/Extra) would be for additional items and would be a flat amount which would be added into the target amount. You could add items here while allowing the target to freely scale based on what is required.

**Comment by ClaudeMetz** [comment]
Hi, thanks for the suggestion. This would be nice, but it's not really feasible unfortunately. This whole way of scaling amounts is already kind of a hacky way to do it, and can't be extended in these ways. Hopefully I can come up with other ways to improve the way amounts can be specified so this is not necessary.
