### ISSUE TITLE
Crash when manually editing amount of an 

### ISSUE THREAD

**Issue by nbd1982** [ClaudeMetz/FactoryPlanner#294]
### Problem Description

I was manually editing the products figure for a recipe and received the following crash to the main menu:

Error while running event factoryplanner::Custom event (ID 298)
__factoryplanner__/ui/main/production_handler.lua:220: attempt to perform arithmetic on field 'percentage' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:220: in function '?'
	__factoryplanner__/ui/dialogs/generic_dialogs.lua:211: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:187: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:216: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:27: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:285: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

I'm running 1.1.107 build 62234 win 64. 

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/15269518/factorio-current.log)

I've uploaded my save at the link below under the name nbd1982CTD.zip. 

### Reproduction

Open Factory planner. Find the factory called "Processing Unit" - it also has the processing unit icon in the name. On the top floor, right click the electronic circuit products button. and change the figure to 50400. Type E or click Confirm to reproduce the crash.

**Comment by ClaudeMetz** [comment]
Hi, thanks for the report. This functionality was (temporarily probably) removed for 2.0, so any new implementation won't have this same issue.
