### ISSUE TITLE
Crash with full PY stack 

### ISSUE THREAD

**Issue by avpas** [ClaudeMetz/FactoryPlanner#295]
### Problem Description

I was using FP to build a setup for one of the intermediates, and as soon as the game completed an autosave, it crashed with this error.
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/56444368/5f0ecc3c-44a4-480f-a3d2-280319574f00)

It did not generate a factorio-current.log output file, and the game did not crash but exited to the main menu.

### Reproduction

Could not reproduce. :-(

**Comment by ClaudeMetz** [comment]
Hi, thanks. Same issue as #219, so closing as dupe.
