### ISSUE TITLE
Bug when grabbing the machine with recipe in it. Repeatable happens whenever i grab the machine even after loading save

### ISSUE THREAD

**Issue by ds769exe** [ClaudeMetz/FactoryPlanner#297]
The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:84: attempt to index local 'machine' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:84: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

**Comment by ClaudeMetz** [comment]
Hi, this unfortunately doesn't really have enough information to go off of. Let me know should it happen again.
