### ISSUE TITLE
Game Crashed when playing pyanodon

### ISSUE THREAD

**Issue by tobbsis** [ClaudeMetz/FactoryPlanner#302]
### Problem Description

Hello!
I was playing the pyanodon mods.
I had a building as a product in the planner. One of the ingredients for the building needed a fluid input. But also a fluid fuel. Yesterday I was switching between the fuel fluids and chose one. Later i saved the game and closed the game. 

Today when i started the game, i opened the planner, and i wanted to change the fluid fuel. I just opened the planner and pressed on the ingredient button that was the fluid fuel. And it crashed. So by just pressing the button the game crashed. But it seemed to work yesterday.

Here is the error i got in the game

The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:291: attempt to index local 'fuel' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:291: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

[factorio-current.log](https://github.com/ClaudeMetz/FactoryPlanner/files/15443371/factorio-current.log)

[Pyanodon.zip](https://github.com/ClaudeMetz/FactoryPlanner/files/15443372/Pyanodon.zip)

### Reproduction

1. Load the save file. 
3. Open the planner and select the "Random 2" "folder"
4. There are 2 recipes, 1 one is a building, second one is glass, 
5. The second item has 2 ingredients it needs. One is white (molten glass), the other is the fluid fuel that the building needs to run.
6. Press on the green/yellow icon which is one of the ingredients of the glass
7. game crashes

**Comment by ClaudeMetz** [comment]
Appreciate the very nice bug report! This is unfortunately quite old now, and I won't be able to fix 1.1 bugs anymore. Let's see if it still happens with Py on 2.0

**Comment by ClaudeMetz** [comment]
Indeed still an issue, fixed for the next release. Thanks again.

**Comment by ClaudeMetz** [comment]
I had a look and can't reproduce this issue in 2.0. A lot of code around fluid fuels changed in the meantime, so I'll consider it resolved. If you run into this again, please open another issue. Thanks.
