### ISSUE TITLE
Add a calculation based on ingredient input?

### ISSUE THREAD

**Issue by milklizard88** [ClaudeMetz/FactoryPlanner#303]
### Suggestion

Helmod seems to have broken this functionality which is a real shame, so I decided to try out your mod and it seems super intuitive compared to H.

The only issue is there's no calculate by input which is super useful when you want to turn one belt of ingredients into an unknown number of products. The best I can think of is turning 1 belt of iron into underground pipes. The recipe needs pipes and iron plates. The pipes also need iron plates, so the math gets complicated on how many assemblers you need for the pipes, and how many you need for the undergrounds to consume a full belt

I'm sure you get this request all the time so I'd imagine it might be complicated otherwise you'd have already implemented it!

Thank you

**Comment by ClaudeMetz** [comment]
Hi, glad you like the mod! I agree calculation by input is a real missing feature. It's unfortunately not super straightforward to add, as you surmised. But I do have sort of a plan to get it going at some point. The card for it is #87, so we'll centralize there.
