### ISSUE TITLE
Error ID: 270 LUA GUI ELEMENT API call

### ISSUE THREAD

**Issue by abccba193** [ClaudeMetz/FactoryPlanner#305]
### Problem Description

The game runs smooth 7 hours with no issues and then all of a sudden: 
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/61704852/b8009dbf-1a76-4f27-9314-f48373daf297)

**Comment by ClaudeMetz** [comment]
Hello, unfortunately this is a common issue I've yet to address, see #219
