### ISSUE TITLE
Feature request: Add support for always rounding UP

### ISSUE THREAD

**Issue by rpdelaney** [ClaudeMetz/FactoryPlanner#306]
As an engineer using Factory Planner for capacity planning, I want to find out if I have more machines than I can supply with the given logistics (whether it's belts, wagons per minute, etc). 

It appears that Factory Planner rounds down to the nearest integer, which is problematic. Consider the following factory plan, a sub-floor for LDS to hit an arbitrary target of yellow science packs:

![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/1139517/933c89d4-aaad-42ea-bea8-086c3b25ade7)

Since Factory Planner reports that I need `0.5` belts of copper ore, I might think that a half-belt of ore would be sufficient. But if I hover the cursor, I see that I actually need `0.567` belts of copper ore. If I hadn't checked, I might have continued with a design that didn't meet the requirements.

To address this problem, Factory Planner should either round up to the nearest integer, or it should provide an option to configure rounding behavior.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the feedback. You are totally right of course, this is an issue. Unfortunately I can't influence the rounding on the numbers on buttons directly, it's a limitation of the game. I have a plan for fixing it #55, but I've just not gotten to it yet.
