### ISSUE TITLE
GUI crash when frenzly navigating the GUIs

### ISSUE THREAD

**Issue by RedRafe** [ClaudeMetz/FactoryPlanner#310]
### Problem Description

Game crashed while quickly opening/closing windows of Factory Planner. I guess it tried to reference a tab that was no longer open at https://github.com/ClaudeMetz/FactoryPlanner/blob/fdb119863dd62a7a99869eaf362f63856c3fda47/modfiles/ui/main/production_handler.lua#L168.

```
Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/main/production_handler.lua:168: attempt to index field 'parent' (a nil value)
stack traceback:
	__factoryplanner__/ui/main/production_handler.lua:168: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
11829.926 Info BlueprintShelf.cpp:724: Saving blueprint storage.
```

Log file: [fp_crash.log](https://github.com/user-attachments/files/15986401/fp_crash.log)

### Reproduction

I was probably editing the modules to select, closed the window, reopened the whole planner, and crash.

**Comment by ClaudeMetz** [comment]
I think this is fixed with 2.0, so I'll consider it as such for now. If anything breaks again, please let me know.
