### ISSUE TITLE
Crash when right clicking product and setting product amount

### ISSUE THREAD

**Issue by ProfounDisputes** [ClaudeMetz/FactoryPlanner#311]
### Problem Description

When I right click a product and try to set the advanced circuits product amount to 646 game crashes:
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/110345786/8b50346f-5d87-4c76-822a-457d4a967678)

Reproduce by loading save file. Should load into open Factory Planner for Main Bus --> sub production on Advanced Circuits. Right click the advanced circuit under the production column and set to 646 and submit.
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/110345786/1857ec42-fff1-4806-87a2-8f7c4ee8efac)

[factorio-current.log](https://github.com/user-attachments/files/16024242/factorio-current.log)
[_autosave1 Factory Planner Error.zip](https://github.com/user-attachments/files/16024225/_autosave1.Factory.Planner.Error.zip)

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This feature was removed for 2.0 (temporarily), so any reimplementation won't have this exact issue.
