### ISSUE TITLE
"send to top" on subfloor replaces that subfloor's final product

### ISSUE THREAD

**Issue by jtaseff** [ClaudeMetz/FactoryPlanner#312]
### Problem Description

Usually the subfloor is restricted to produce its original product, that product is locked at the top and can't be moved down. 
However, using ctrl+click to move another product to the very top will replace it and change what the subfloor is trying to produce. Only way to fix it is to move the original product down farther and then send it to the top.

**Comment by fgardt** [comment]
I just encountered the same issue in version 1.1.78

**Comment by ClaudeMetz** [comment]
Fixed by mattnotmitt's PR, thanks for the reports!
