### ISSUE TITLE
Ultracube: Steam

### ISSUE THREAD

**Issue by LoupAndSnoop** [ClaudeMetz/FactoryPlanner#313]
### Problem Description

I was planning out a factory in Ultracube: Age of Cube. I set a recipe for "Basic Matter Unit". Then I clicked on the icon for "Steam" (which is an input), as that should bring up the UI for different recipes to make steam (or otherwise automatically pick the one recipe to make steam). Clicking that icon causes a crash with the following report. Save attached: 
[factorio-current.log](https://github.com/user-attachments/files/16041503/factorio-current.log)
[factorio-previous.log](https://github.com/user-attachments/files/16041504/factorio-previous.log)

The mod Factory Planner (1.1.78) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 286)
__factoryplanner__/backend/data/Machine.lua:62: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/Machine.lua:62: in function 'normalize_fuel'
	__factoryplanner__/backend/data/Line.lua:100: in function 'change_machine_to_proto'
	__factoryplanner__/backend/data/Line.lua:151: in function 'change_machine_to_default'
	__factoryplanner__/ui/dialogs/recipe_dialog.lua:94: in function 'attempt_adding_line'
	__factoryplanner__/ui/dialogs/recipe_dialog.lua:258: in function 'early_abort'
	__factoryplanner__/ui/base/modal_dialog.lua:154: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:245: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:423: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:245: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:423: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

1. Start game in ultracube
2. Open factory planner
3. Set recipe target to Matter Replication Gel.
4. Click on "Steam" input to try to bring up UI for different recipes to make steam.
5. Crash

**Comment by Soul-Burn** [comment]
+1 on this issue exactly the same place.

**Comment by corwinburdick** [comment]
Same error and cause for me as well. This is happening for me on the latest version of Ultracube (0.5.6)

**Comment by ClaudeMetz** [comment]
Hello, thanks for the reports. Same issue as #240, so we'll centralize there.
