### ISSUE TITLE
upgrading from factory planner 1.1.10 to 1.1.78 fails on index into global.installed_mods, which is nil

### ISSUE THREAD

**Issue by SpaceCat-Chan** [ClaudeMetz/FactoryPlanner#314]
most likely the code which creates the global if it doesn't exist was removed in some inbetween version, or it runs after the code that causes the crash

image of error:
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/49094338/0b189510-8971-4411-8b67-3703ecc4c19f)

**Comment by SpaceCat-Chan** [comment]
circumventing that crash by code patching causes another later for the same reason
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/49094338/71bf7b42-eae7-4bd9-b62a-929697a05b2b)

**Comment by SpaceCat-Chan** [comment]
after patching that crash as well, the save loads, and yeah now i see the message in the chatbox, i'll be doing as it says
![image](https://github.com/ClaudeMetz/FactoryPlanner/assets/49094338/25055744-68a6-4471-abac-ff38bc34d850)

**Comment by ClaudeMetz** [comment]
Thanks for the details, saves that old were indeed dropped from support. One could still save their factories by exporting them to string and importing them in an updated game, that should work no problem.
