### ISSUE TITLE
Crash on right clicking module slot

### ISSUE THREAD

**Issue by RedCMD** [ClaudeMetz/FactoryPlanner#317]
Add modules to a recipe and confirm
right click modules
clear module slot
[ESC] to cancel
right click modules again
crash

![image](https://github.com/user-attachments/assets/c7366ec5-cea6-46e2-a41d-8ff1ad11b763)

**Comment by ClaudeMetz** [comment]
Hello, thanks, I ran into this myself while working on 2.0, so it should hopefully be fixed once that drops.
