### ISSUE TITLE
Adding Py Module causes crash on "utilities" click

### ISSUE THREAD

**Issue by johnbrian** [ClaudeMetz/FactoryPlanner#320]
### Problem Description

Currently playing with Py Mods, which include a "module" that gives a significant speed increase. Was able to incorporate this into the planner, but when I click "utilities", it crashes the game, presumably because that "module" can't be built.

Here's the crash info:

Error while running event factoryplanner::Custom event (ID 222)
__factoryplanner__/ui/dialogs/utility_dialog.lua:149: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/ui/dialogs/utility_dialog.lua:149: in function 'refresh_component_flow'
	__factoryplanner__/ui/dialogs/utility_dialog.lua:165: in function 'components'
	__factoryplanner__/ui/dialogs/utility_dialog.lua:377: in function 'dialog_open'
	__factoryplanner__/ui/base/modal_dialog.lua:171: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:209: in function <__factoryplanner__/ui/event_handler.lua:189>
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_box.lua:295: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:20: in function 'open_dialog'
	__factoryplanner__/ui/main/production_box.lua:295: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:157: in function <__factoryplanner__/ui/event_handler.lua:114>

### Reproduction

Start a game using the full Py suite and Factory Planner
Research the Seaweed T.U.R.D. upgrade
Select the "Improved Pathfinding" option
Create a plan that involves Seaweed
Add the "Improved Pathfinding" module to the Seaweed Farm
Hit the "utilities" button

https://i.imgur.com/BfPi6Mq.png

**Comment by ClaudeMetz** [comment]
Thanks for the report. Let's wait for Py's on 2.0 and check if it still happens then.

**Comment by ClaudeMetz** [comment]
Yeah you're spot on, it's because it tries to look at modules that can't be crafted. I think the solution is to disallow those special modules, since they aren't really modules in the traditional sense. Supporting TURDs like that will need some special interface, since it's all scripted by Py.

**Comment by ClaudeMetz** [comment]
Fixed for the next release.
