### ISSUE TITLE
Invalid output amount calculation with one tick recipes

### ISSUE THREAD

**Issue by FluffyDiscord** [ClaudeMetz/FactoryPlanner#324]
### Problem Description

Having machine sped up so much that it crafts the recipe within one tick makes the planner confused. It correctly stops using more items than recipe/machine can consume within one tick, but the output amount keeps rising. The output amount should also be limited to one tick

### Reproduction

Unrealistic vanilla scenario (can easily happen modded):

1. Pick rails item
2. Select 25 blue belts as amount of items
3. Add recipe for it
4. Limit to only one assembler machine
5. Add 5000 beacons with speed 3 module
6. Change to 10 000 beacons

Observe the input amount of items not changing (good/correct) but the output keeps rising to infinity (invalid)

**Comment by ClaudeMetz** [comment]
Hm I thought we had this all figured out, but the machine limit might be throwing a spanner into the works. Either way, the 1 craft/tick limit goes away with 2.0, so too does this issue :)

**Comment by FluffyDiscord** [comment]
Not really, because it would be the opposite issue. Input item amount will be the same (invalid), but the output would keep increasing (correct). Would it be possible to release a fix for factorio 1.1, and then 2.0?

**Comment by ClaudeMetz** [comment]
I'll not be doing any more 1.1 releases. I am not sure if will be the same? The whole special logic around this was dropped, so it should just work the same as any other craft right?
