### ISSUE TITLE
crash when setting a floor's output to empty string

### ISSUE THREAD

**Issue by wchristian** [ClaudeMetz/FactoryPlanner#327]
### Problem Description

i deleted the value i had previously set in a floor's output and clicked ok, and this crash happened

[factorio-current.log](https://github.com/user-attachments/files/16829148/factorio-current.log)

**Comment by ClaudeMetz** [comment]
I am not quite sure what you mean by floor's output here, could you clarify?

**Comment by ClaudeMetz** [comment]
I'll close this as non-reproducible. If anyone has the same crash, please open a new issue.
