### ISSUE TITLE
Support formulas in amount fields

### ISSUE THREAD

**Issue by ALoTron** [ClaudeMetz/FactoryPlanner#328]
### Suggestion

When specifying the amount of an item, e.g. when right clicking an item in the `Products` tab, the player might want to perform simple calculations. I often have the use case, where I want to calculate the throughput of `n` yellow belts and use that as the desired output of the factory. While it is possible to specify a belt type and then the amount of belts I think it is more convenient to simply type e.g. `15*6` into the amount box.

Therefore I propose adding support for simple formulas in boxes where a number is needed. The Factory Planner would then calculate the solution for the formula and use that as the number.

**Comment by ClaudeMetz** [comment]
Well it's your lucky day, because exactly this was implemented for the 2.0 release, see #62 :)
