### ISSUE TITLE
Crash when trying to add recipe

### ISSUE THREAD

**Issue by floerps** [ClaudeMetz/FactoryPlanner#329]
### Problem Description

When I try to add recipe for steam from ingredient list at the top of the planner, I get this crash.
Happens in both matrix and traditional solver. Haven't found other recipes where this happens yet (only steam)
I'm using the Ultracube mod.
![image](https://github.com/user-attachments/assets/4be4a381-358b-4512-a5cc-4b830f507ab4)

### Reproduction

Go to factory planner
Add main recipe (no problem)
Add some underlying recipes (no problem)
Add steam production - crash

**Comment by ClaudeMetz** [comment]
Thanks for the detailed report. This is a duplicate of #240, so let's centralize there.
