### ISSUE TITLE
Add support for matrix subfactories

### ISSUE THREAD

**Issue by DeadMG** [ClaudeMetz/FactoryPlanner#333]
### Suggestion

When playing more complex mods like Space Exploration, I'm often running into a slight problem with planning my factories when composing them of isolated units (e.g. planets, city blocks, whatever). You can see a simplified example with a vanilla system. 

- Create a new factory plan and switch to matrix mode
- Add products of 100 blue, 100 red, and 100 green chip
- Expand green chip into a subfactory, and add copper wires- so far so good.
- Expand red chip into subfactory and try to add copper wires. Receive linearly dependent recipe error.

The basic problem is that the player is forced into one of two options, neither of which works quite as desired. If you use one plan for all your planets/blocks/whatever, you can see stuff like "how much copper total do I need", but you can't see how many copper wire assemblers you need for each production line (great for figuring out direct insertion), and additionally extra large plans lag a bit. If you use one plan for each, you can get a figure for how many assemblers, but not how much total input is needed, and additionally any dependencies must be manually synchronised between the plans. This is best exemplified by SE's Thermofluid- I need to centralise production of warm thermo, but localise the cooling loop (this necessitates matrix mode). The player ends up with duplicating their plans in both ways to get the different information they need.

The Traditional mode subfactories seem to work well here, but as soon as any loop occurs anywhere in the factory, it falls over.

Therefore I'd like to propose an improvement where the player can group plans together. Essentially the player creates a graph (acyclic per material) where different plans are linked to each other for specific materials- like "Plan A imports copper plate and exports green chips". In the matrix sense each plan would be resolved independently, so several plans can make their own copper wires/whatever locally. Hopefully several smaller solves is faster than one huge solve, matrix-wise, and some plans may be able to go back to traditional. The production amounts for the plan would be whatever the player has set and also what they need to export, so if the player doubles their science plan's output, the plan that exports LDS for yellow science would be updated automatically. This graph structure would match import/export relationships better than either unified or disparate plans.

I understand that this is probably either a "pretty big" or "too big" ask, but with the expansion coming soon, it's a good time to at least consider what features may offer better support for it.

**Comment by ClaudeMetz** [comment]
Hi, thanks for the suggestion. As it happens, this is exactly what I've wanted for a long time, and what I implemented for 2.0 :) You pretty much nailed it of how it would work. It's more basic than I want it to be at the moment, as I ran out of time, but the idea is there. You can't take input from another factory atm, for example, but expanding the system is something I will work on after 2.0 for sure. Got many good ideas I think, see #82 (to be updated still)

**Comment by DeadMG** [comment]
Ah very nice, thanks very much!
