### ISSUE TITLE
Bring back reset to default 

### ISSUE THREAD

**Issue by sferg8** [ClaudeMetz/FactoryPlanner#351]
### Suggestion

Now the defaults are difficult to use unless im not seeing something, they are missing in Preferences, and i have to manually change each machine after the fact because I cant set them in advance.

I do like alot of the other changes tho

**Comment by ClaudeMetz** [comment]
Hi, appreciate the message. You can set the defaults in the machine/beacon dialogs now, not sure if you noticed. It does mean that you can't set them before adding the very first recipe, but that's pretty rare I feel. The new way is more flexible, it can save the module configuration too for example. So I suggest giving it the new way a try for a bit :)

**Comment by sferg8** [comment]
hmm, after yesterday, the copy paste is a little slower, than the mod+rightclick but i can live with it. Overall great updates.
cheers!
