### ISSUE TITLE
Crash on opening a factory-plan

### ISSUE THREAD

**Issue by KnochenMarkSaege** [ClaudeMetz/FactoryPlanner#355]
### Problem Description

Hello, really enjoying the new update for the Factory Planner, but sadly it crashes every time I try to open one of my factory-plans.

Description of the setup:
Currently I only have 2 plans inside the factory planner. One containing the plans for iron plate and one for copper plates.
The other plan is for green and red science.

Clicking on the first plan always results in a crash (see error message below).
Clicking on the second plan seems fine.
Switching the positions of the plans still results in only crashing on the iron/copper plate plan.
Trying to delete / edit the plan results in the same error message

Possible causes for the error:
I think what could be causing the problem, is the way how the new default machines get set.
I don't remember exactly what it was, but I think the standard machine for smelting / assembling selected was a foundry.
When i switched to the assembler / basic smelter for all categories, I think something got damaged, as I cant select the foundry anymore (as it should be, since im at the start of the game). But maybe the problem is that the crashing plan got updated in a weird way and tries to access something that's not accessible (hence the nil value exception on the object I suppose)

What I tried so far:
- Changing positions of the plans -> It seems like it has nothing to do with the plans
- Enabling / Disablind the "Pause game" function -> doenst change anything
- Editing / Deleting the Plan -> results in the same crash
- Recreating the same setup to see if it will result in a crash -> It didnt crash so far
- Turning off item icons -> doesnt change anything

My Factory Planner Preferences:
- Attach Factory product icons
- Fold out subfloors
- Mark recipe as done
- percentage
- recipe comments

Error Message:
The mod Factory Planner (2.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/util/context.lua:88: attempt to index local 'object' (a nil value)
stack traceback:
	__factoryplanner__/util/context.lua:88: in function 'set'
	__factoryplanner__/ui/main/factory_list.lua:100: in function 'handler'
	__factoryplanner__/ui/base/modal_dialog.lua:354: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

Screenshots of the setup:
This Plan still works fine
![image](https://github.com/user-attachments/assets/acc52a2a-3640-4d7e-979b-30b8d6861959)

This Plan is an exact copy of the First Plan
![image](https://github.com/user-attachments/assets/29b1ee12-dcd3-4772-9991-b689d45b9b2a)

Clicking on the first created Plan will result in the crash
![image](https://github.com/user-attachments/assets/0d107f68-e7ac-40cd-9d9e-7d43fbd82b3e)

All other mods currently enabled:
- Elevated Rails
- Quality
- Space Age
- AAI Containers & Warehouses
- Auto Deconstruct
- Bullet Trails
- Cleaned Concrete
- Creative Mod
- Disco Science
- Even Distribution
- Factorio Library
- Factory Planner
- Fill4Me
- Fluid Wagon Color Mask
- Fox TODO
- Honk
- Infinity Invo
- InformaTron
- Jetpack
- Quality of Life Research
- Rate Calculator
- Robot Attrition
- Shield Projector
- Soundpack Alerts and Sirens Updated
- Stats GUI
- Text Plates
- Tree Collision
- VehilceSnap

If I can provide any more Information that could be helpful for finding the bug please let me know,
and thank you for bringing your mod to 2.0 so quickly, it really adds so much convenience to the game :)

### Reproduction

Clicking on the first factory Plan I added results in a crash.
It doesnt matter if I try to select, edit or remove the plan.

Recreating an exact copy of the Plan seems fine and interacting with it doesnt result in a crash.
As mentioned above, I think the way default machines get updated seem to have an unwanted Side-effect.
Sadly I only roughly remember what it was, but I remember sawing a foundry set as a default machine for an item, even though it wasnt set before, and I cant choose the foundry on any other plan, since I dont have it unlocked yet.

**Comment by KnochenMarkSaege** [comment]
Update:

- I unloaded the mod. 
- Loaded my save game.
- Saved the game without the mod. 
- Added the Mod again

I tried to recreate the plans I already had. When adding a plan for green Science, it chooses the Foundry as the basic machine for the transport belt (see pictures)
![image](https://github.com/user-attachments/assets/ad0bc933-4e8a-40f4-b1d3-ba54de46d062)

![image](https://github.com/user-attachments/assets/ff61e024-564a-42c8-a817-8d2df0bfa624)

I now have the same setup as I did before, but until now no crash occured.
Im not sure if maybe clicking on "Set for all categories" is what causes the porblem.
This time I  only used "Set as default" and it seems fine for now.

**Comment by ClaudeMetz** [comment]
Hello, thanks for the incredible bug report. It's the same issue as #362, and even with your very detailed descriptions, I can't quite replicate it. It gets into a bad state somehow, which is automatically repaired by changing anything about the installed mods, which makes it hard to replicate.

I think unfortunately I can't do anything about this until someone figures out a reproduction from scratch, sorry about that. Closing this for now.
