### ISSUE TITLE
Mod is not loaded despite being activated

### ISSUE THREAD

**Issue by tvardero** [ClaudeMetz/FactoryPlanner#357]
### Problem Description

Fresh Factorio install (v2.0.8, just installed).
Fresh new save file.
No other mods are installed, except for factory-planner and flib.

Mod is not active (no shortcuts, no keybinds in settings, no mod settings menu), despite being activated in mod list.

FP v2.0.1, v2.0.2
[factorio-current.log](https://github.com/user-attachments/files/17476441/factorio-current.log)
[save file.zip](https://github.com/user-attachments/files/17476443/spaaace.zip)
![game screenshot](https://github.com/user-attachments/assets/af150881-62da-4dd3-a9f6-e0def9601a0e)
![mod list](https://github.com/user-attachments/assets/895918a6-cd8b-4350-841d-e241c7be26ff)

### Reproduction

1. Start a game and create/load save file.

**Comment by tvardero** [comment]
Creating a new save file fixed a problem. Something was wrong with a save file

**Comment by ClaudeMetz** [comment]
Okay I'll consider this solved then until someone runs into the same issue again. Thanks a lot for the very nice report though!
