### ISSUE TITLE
Scroll bar overlaps content

### ISSUE THREAD

**Issue by stefanenthoven** [ClaudeMetz/FactoryPlanner#359]
### Problem Description

The horizontal scrollbar overlaps the bottom recipe

![image](https://github.com/user-attachments/assets/4c062737-3128-4f0f-a10f-6da3491ed361)

**Comment by ClaudeMetz** [comment]
Ugh this is just an eternal problem, will try to fix it, thanks for the report.

**Comment by ClaudeMetz** [comment]
I honestly don't know how to fix this properly. I tried to improve it a bit for the next release.
