### ISSUE TITLE
You cannot reset the productivity bonus back to zero when you have researched a productivity research.

### ISSUE THREAD

**Issue by Dutch0903** [ClaudeMetz/FactoryPlanner#364]
### Problem Description

Once you have researched a productivity research liking mining productivity, you can not reset the productivity bonus back to 0 in the Utilities Dialog. The Factory Planner wont update the recipe.

I have taken a look at it and I think the problem is here: https://github.com/ClaudeMetz/FactoryPlanner/blob/master/modfiles/backend/data/Machine.lua#L105 

It will only the update the recipe if the productivity is above zero. 

I have create a new PR (https://github.com/ClaudeMetz/FactoryPlanner/pull/363) that will also update the recipe effects when the productivity is zero. 

Feel free to ask question or alter my PR.

### Reproduction

1. Start a new world using the mod scenario `Editor Extension` (https://mods.factorio.com/mod/EditorExtensions). This will create a new world with already some productivity researches done.
2. Create a new factory and add the recipe 'Plastic Bar'. Since Factorio 2.0 there is a productivity research for this recipe.
3. Open the utility dialog 
4. Change the productivity back to 0
5. Hover over the Assembling Machine button. It will still so 10% productivitiy.

**Comment by ClaudeMetz** [comment]
You're spot on, appreciate the nice report and PR! :)
