### ISSUE TITLE
Deleting all but one recipe in a subfloor results in inconsistent view

### ISSUE THREAD

**Issue by svr8450** [ClaudeMetz/FactoryPlanner#368]
### Problem Description

Deleting all but the topmost recipe in a level 2 subfloor results in the recipes/subfloors below this subfloor in the level 1 list being shown in the level 2 subfloor list, until you return to level 1.

The expected behavior is either (like previous version) we remain on level 2 subfloor and see only the top recipe, or maybe we are returned to level 1, but not to see an inconsistent mix of both.

### Reproduction

Factorio 2.0.10
Factory Planner 2.0.2

1. Create a floor with three recipes: iron chest, transport belt, inserter
2. Create a subfloor on the transport belt and add iron gear recipe
3. Delete iron gear recipe
4. Observe that the UI remains on "Level 2" and it displays two recipes: transport belt and inserter.

**Comment by ClaudeMetz** [comment]
Thanks for the report, this was indeed just a bug, fixed for the next release.
