### ISSUE TITLE
Crash when selecting Screen option

### ISSUE THREAD

**Issue by Harvus00** [ClaudeMetz/FactoryPlanner#369]
### Problem Description

[factorio-current.log](https://github.com/user-attachments/files/17530733/factorio-current.log)
The mod Factory Planner (2.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 264)
__factoryplanner__/backend/data/District.lua:114: attempt to perform arithmetic on field 'emissions' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/District.lua:114: in function 'refresh'
	__factoryplanner__/ui/main/districts_box.lua:75: in function 'build_district_frame'
	__factoryplanner__/ui/main/districts_box.lua:187: in function 're
[factorio-current.log](https://github.com/user-attachments/files/17530727/factorio-current.log)
fresh_districts_box'
	__factoryplanner__/ui/main/districts_box.lua:295: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:325: in function <__factoryplanner__/ui/event_handler.lua:302>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:13: in function 'refresh'
	__factoryplanner__/ui/main/district_info.lua:63: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>
[_autosave1.zip](https://github.com/user-attachments/files/17530738/_autosave1.zip)

### Reproduction

Selected top menu option

**Comment by ClaudeMetz** [comment]
Appreciate the report, was able to fix it for the next release!

**Comment by Harvus00** [comment]
Welcome
