### ISSUE TITLE
Power as a product

### ISSUE THREAD

**Issue by AllenJB** [ClaudeMetz/FactoryPlanner#370]
### Suggestion

It would be useful to have power as a product for setting up power plants (eg. how much fuel or water does the power plant need, how many burners can you put on 1 belt, or how many solar panels to produce x amount of power)

(For vanilla, in Factorio 1.1 you could do this for basic steam power plants using steam as a product, but in 2.0 Factory Planner only recognizes the acid neutralization recipe for steam as a product)

**Comment by ClaudeMetz** [comment]
Thanks for the suggestion. This has been on the todo list for a long time, but it's a lot of work to add power-production recipes and the like. The old card for this is #81, but it's probably not really current anymore. Either way, this is a long while off, there's a lot of other tasks to get to unfortunately.
