### ISSUE TITLE
Crash when "reset values to previous state" while editing agricultural tower

### ISSUE THREAD

**Issue by Gabanyic** [ClaudeMetz/FactoryPlanner#374]
### Problem Description

The mod Factory Planner (2.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/ui/dialogs/machine_dialog.lua:118: attempt to index field 'limit_textfield' (a nil value)
stack traceback:
	__factoryplanner__/ui/dialogs/machine_dialog.lua:118: in function '?'
	__factoryplanner__/ui/base/modal_dialog.lua:377: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

I know there is nothing to edit in this window so you will never need to press it, but it being located in the top left traditionally reserved for X to close in most other windows (outside this mod) I found myself accidently pressing it and crashing out. its is consistent 10/10 attempts with multiple recipes. I assume its attempting to reset something that has no data to index and there is no exception to that in the function. 

### Reproduction

set some sort of Gleba factory chain using the agricultural tower
Edit agricultural tower machine
click to reset values to their default state
click Are you sure
Say F to your unsaved progress

**Comment by ClaudeMetz** [comment]
Appreciate the report, this is fixed for the next release!
