### ISSUE TITLE
Crash when clicking on almost any button

### ISSUE THREAD

**Issue by goalaleo** [ClaudeMetz/FactoryPlanner#376]
### Problem Description

Clicking on almost any button causes the followng error. Using version 2.0.1

![image](https://github.com/user-attachments/assets/a5f13afd-f7b5-4cf7-aea3-2a40e9b43938)

**Comment by ClaudeMetz** [comment]
Hello, please update your mod as this issue was resolved in 2.0.2. If you still encounter it after updating, let me know!
