### ISSUE TITLE
Crash when opening Utility Dialog

### ISSUE THREAD

**Issue by Kyoj1n** [ClaudeMetz/FactoryPlanner#377]
### Problem Description

![image](https://github.com/user-attachments/assets/2660cc35-9de8-48d6-ba6e-370fa4c8c2d8)

Many hours into a 2.0 Space Age save and I am making my first plan with the mod. 
I choose purple science fill the product menu out then when I press the cogwheel to run the utility it crashes.

**Comment by ClaudeMetz** [comment]
Could you provide me with the save file for this?

**Comment by Kyoj1n** [comment]
[SPACEdot.zip](https://github.com/user-attachments/files/17541690/SPACEdot.zip)
Let me know if that doesn't work. 
I've also got some other mods going on there.

**Comment by ClaudeMetz** [comment]
Thank you

**Comment by ClaudeMetz** [comment]
This was related to the mods you used to avoid spoilers, which the mod didn't deal with properly. Fixed for the next release, thanks again.
