### ISSUE TITLE
Close district picker when selecting one

### ISSUE THREAD

**Issue by DeadMG** [ClaudeMetz/FactoryPlanner#379]
### Suggestion

When having several districts, changing district is just a little clunky. When the player opens the district picker, they see the list of districts and they select it, but they then have to click again to close the picker to actually see the district. The expected result is that the district picker closes itself, so when the player selects the district, they immediately see that district.

**Comment by ClaudeMetz** [comment]
This is something I thought about a fair bit. It's a similar situation when having district view open and manipulating the factory list on the right. Yes, it does feel intuitive to see the factory when clicking it. But then also, it's kinda nice that you can manage your factories from the district view. At least that was my thinking.

Thinking about it again now, maybe there should be situations where it closes the districts view. I'll put it on the list to think about, but it's not super urgent. Thanks for the suggestion.

**Comment by DeadMG** [comment]
Maybe it could be some kind of dual-pane or nested list view, so the districts are listed on the left either separately or inline?

**Comment by ClaudeMetz** [comment]
I made more common actions close the District view for the next release, which should make the whole interaction feel smoother.
