### ISSUE TITLE
Received an error when tried to switch parameter

### ISSUE THREAD

**Issue by serjevski** [ClaudeMetz/FactoryPlanner#380]
### Problem Description

![image](https://github.com/user-attachments/assets/3ba3b369-791c-403d-8610-dcfb92771241)

=====
Error while running event factoryplanner::on_gui_switch_state_changed (ID 160)
__factoryplanner__/backend/calculation/solver.lua:153: attempt to index field '?' (a nil value)
stack traceback:
	__factoryplanner__/backend/calculation/solver.lua:153: in function 'determine_satisfaction'
	__factoryplanner__/backend/calculation/solver.lua:174: in function 'update_ingredient_satisfaction'
	__factoryplanner__/backend/calculation/solver.lua:232: in function 'determine_ingredient_satisfaction'
	__factoryplanner__/ui/dialogs/preferences_dialog.lua:259: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

[Uploading _autosave1.zip…]()
[Uploading factorio-current.log…]()

**Comment by ClaudeMetz** [comment]
I'm sorry but I can't reproduce this issue. Your save didn't upload either unfortunately. Do you have any more details on this? Or a reliable reproduction?
