### ISSUE TITLE
Server crash while planner not in use

### ISSUE THREAD

**Issue by ConstructionZombie** [ClaudeMetz/FactoryPlanner#381]
### Problem Description

I am playing with one other person that would be very unlikely to use the factory planner, and I had not opened or interacted with it when a server crash occurred. The crash log points toward factory planner with an ID. Crash log and last autosave before crash included in files.
[_autosave1.zip](https://github.com/user-attachments/files/17551933/_autosave1.zip)
[factorio-previous.log](https://github.com/user-attachments/files/17551935/factorio-previous.log)

**Comment by ClaudeMetz** [comment]
Hi, thanks for the report, sorry for the issues. This is supposedly fixed in 2.0.4, so please give it an update and let me know if it happens again!
