### ISSUE TITLE
Crash when entering decimal into # of beacons

### ISSUE THREAD

**Issue by virginblack** [ClaudeMetz/FactoryPlanner#382]
### Problem Description

Admittedly, I didn't read the instructions about entering integers for beacon amounts. Regardless, the game crashes when you try to enter one.

The mod Factory Planner (2.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_text_changed (ID 2)
__factoryplanner__/backend/data/Beacon.lua:66: attempt to perform arithmetic on local 'profile_mulitplier' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/Beacon.lua:66: in function 'summarize_effects'
	__factoryplanner__/backend/data/ModuleSet.lua:108: in function 'normalize'
	__factoryplanner__/ui/dialogs/beacon_dialog.lua:175: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

### Reproduction

Enter any decimal into the Amount on the Edit Beacon screen

**Comment by ClaudeMetz** [comment]
Thanks for the report. Please update the mod to 2.0.4, which should fix this issue!
