### ISSUE TITLE
Crash when resetting mining drill

### ISSUE THREAD

**Issue by EliaValkyr** [ClaudeMetz/FactoryPlanner#385]
### Problem Description

Hi, I was trying to create a Factory for the Vulcanus science when I got a crash. I was editing the mining drill for Calcite and clicked twice on the red button in the top right. 

[Picture](https://i.imgur.com/Kf7hlBy.png)

[Log file](https://github.com/user-attachments/files/17577239/factorio-current.log)

[Save file](https://github.com/user-attachments/files/17577241/Space.Age.2.zip)

**Comment by ClaudeMetz** [comment]
Thanks for the report with all the relevant files, very helpful! This issue should have been fixed with a recent release, so try updating the mod and let me know if it happens to you again.

**Comment by ClaudeMetz** [comment]
I'll consider this solved, please feel free to open a new issue if there's anything else.
