### ISSUE TITLE
Crash after closing edit machine window on burner assembling machine in Pyanodons

### ISSUE THREAD

**Issue by Ecoround** [ClaudeMetz/FactoryPlanner#391]
### Problem Description

[factorio-current.log](https://github.com/user-attachments/files/17606992/factorio-current.log)
[crash_savefile.zip](https://github.com/user-attachments/files/17606999/crash_savefile.zip)

The mod Factory Planner (2.0.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_player_display_resolution_changed (ID 106)
The mod Factory Planner (2.0.4) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 246)
__factoryplanner__/backend/calculation/solver.lua:351: attempt to perform arithmetic on local 'fuel_value' (a nil value)
stack traceback:
	__factoryplanner__/backend/calculation/solver.lua:351: in function 'determine_fuel_amount'
	__factoryplanner__/backend/calculation/matrix_engine.lua:646: in function 'get_line_aggregate'
	__factoryplanner__/backend/calculation/matrix_engine.lua:515: in function 'get_lines_metadata'
	__factoryplanner__/backend/calculation/matrix_engine.lua:484: in function 'get_factory_metadata'
	__factoryplanner__/backend/calculation/matrix_engine.lua:170: in function 'get_matrix_solver_metadata'
	__factoryplanner__/ui/main/production_box.lua:21: in function 'refresh_solver_frame'
	__factoryplanner__/ui/main/production_box.lua:208: in function 'refresh_production_box'
	__factoryplanner__/ui/main/production_box.lua:391: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:325: in function <__factoryplanner__/ui/event_handler.lua:302>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:13: in function 'refresh'
	__factoryplanner__/ui/dialogs/machine_dialog.lua:296: in function 'dialog_close'
	__factoryplanner__/ui/base/modal_dialog.lua:188: in function 'exit'
	__factoryplanner__/ui/event_handler.lua:229: in function <__factoryplanner__/ui/event_handler.lua:202>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:26: in function 'close_dialog'
	__factoryplanner__/ui/base/modal_dialog.lua:410: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>
stack traceback:
	[C]: in function '__newindex'
	__factoryplanner__/ui/base/main_dialog.lua:107: in function 'rebuild'
	__factoryplanner__/ui/base/main_dialog.lua:41: in function 'shrinkwrap_interface'
	__factoryplanner__/ui/base/main_dialog.lua:219: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:325: in function <__factoryplanner__/ui/event_handler.lua:302>****

### Reproduction

1. Open the Factory planner
2. Left-click on any Burner Assembly Machine in the Automation Science Pack Section
3. Click on cancel/press escape in the "Edit Machine" Window.
4. Game crashes with the Log above

**Comment by ClaudeMetz** [comment]
Thanks for the report. While investigating, I did find and fix 2-3 other bugs, so thanks for that! What I did however not do is reproduce your issue. Your reproduction steps don't seem to line up with the crash log either unfortunately.

Sooo has this happened to you again by chance? Otherwise I'm not really sure how to fix this.

**Comment by Ecoround** [comment]
Its fine, thank you for trying. I didnt have the crash in other situations. I'm using YAFC now, as its been made 2.0 compatible recently, and I was just using factory planner as a stop gap.
