### ISSUE TITLE
Planner Doesn't Support Mix-Matched-Quality Modules

### ISSUE THREAD

**Issue by ridesdragons** [ClaudeMetz/FactoryPlanner#392]
### Problem Description

when setting up a production line using modules, you can include the quality of those modules, which the menu supports. you can also choose to split the type of module, such as 2 speed module 2s and 2 production module 2s. however, if you choose to set in multiple of the same module type but split between different qualities, such as for example, 1 uncommon speed module 2 and 1 rare speed module 2, the menu will at first show it properly lined up [like so](https://puu.sh/KhUEg/d2233c4eba.png), but as soon as you click "submit", [the first module you entered into the production line disappears](https://puu.sh/KhUEn/6689b490bd.png)

as for "why you would even want to do this", during the midgame, before you have access to infinite rerolling of qualities, you'll be using whatever quality stuff you have on hand, as you can't exactly plan to have 20 blues - if you only have 7 blues and 13 greens, then you'll have to make do with the greens. for example: normally module production is done in a 1:2 ratio - 2 assemblers making module 1s can feed 1 assembler making module 2s. however, if your module 2 assemblers are stuffed with quality modules and your module 1 assemblers are stuffed with speed modules, and increase the quality of the speed modules, you can reduce that ratio until you eventually get a 1:1 ratio. 2 green modules doesn't _quite_ reach a 1:1, while 2 blues is overkill, and I don't have many blues. 1 green and 1 blue will suffice, and is much easier to equip my assemblers with, but the planner breaks when attempting to mix and match different qualities in the assembler.

now, in the case of module 2s, it's not that big of an issue - 2 greens is _basically_ enough to make them run 1:1, but modules aren't the only production line that has weird ratios that I'd like to make more sane, and being economical with my modules is pretty important before rerolling becomes reasonable/possible, which means often only using enough higher quality modules to fix ratios. it'd be nice to know if a given production line only needs a 50:50/33:67 split in quality to achieve desired ratios.

### Reproduction

1. set up a production line with a building that can accept 2+ modules
2. set a module of a given quality, and set it to only fill 1 slot (e.g. uncommon speed module 2)
3. set another module of the same type but of a different quality (e.g. rare speed module 2) and hit submit
4. module setting breaks, only last set module is saved, other slot(s) remains empty

**Comment by ClaudeMetz** [comment]
Appreciate the well-reasoned report. Your use-case is definitely a legitimate one. I actually kind of knew this was a problem, but thought I addressed it. It's awkward in the UI because I don't have control over the module-picking window, so I can't really do it how it'd be best for users. I might have to re-implement it myself instead of using the vanilla one.

Anyways, I'll try to come up with a solution for now.

**Comment by ClaudeMetz** [comment]
Had a look at it, turns out everything handled this correctly, except the sorting function to get everything into a consistent ordering. That one silently dropped these half-duplicate modules. Fixed for the next release, thanks again.
