### ISSUE TITLE
Space science recipe can't be use

### ISSUE THREAD

**Issue by Fr-Dae** [ClaudeMetz/FactoryPlanner#393]
### Problem Description

	when i try find the number of eletrical smelter i need for my iron (for make 150u/m) i have just "0" 

### Reproduction

![Capture d’écran du 2024-11-08 16-36-35](https://github.com/user-attachments/assets/9ac5b4f3-21f0-450d-9b35-2fb86d54bb7e)

**Comment by thorin87** [comment]
@Fr-Dae You need to manually change the planet you are on to Space Platform, in top left corner of the window. It took me some time to find this too ;)
![Uploading obraz.png…]()

**Comment by Fr-Dae** [comment]
-_-

**Comment by Fr-Dae** [comment]
basically, we use your mod because it's supposed to be user friendly compared to helmod which is unreadable. 
please, can you add a popup or something to signal this in-game?

**Comment by ClaudeMetz** [comment]
The tooltip of the space science recipe is red to indicate this issue. But I can add an additional message when adding an incompatible one, you're not the first one to be confused by this.

**Comment by Fr-Dae** [comment]
th, have a nice day

**Comment by Fr-Dae** [comment]
s

**Comment by Fr-Dae** [comment]
i have close, but you want maybe ope a branch from this one here

**Comment by ClaudeMetz** [comment]
Yeah I'll keep it around so I don't forget, thanks

**Comment by Fr-Dae** [comment]
I was taught that linking a PR to an issue allows better tracking and also allows you to use the autochangelog (or release update) function. 
with my team i have write this md file for give tips about github projet and auto-adding issue on it.

https://github.com/UnionRolistes/Documentation/blob/main/Template-Git/Auto-issue_EN-GB.md
you can see here a exemple of use of this template, very usefull to organise and make clean  github project (new feature from 2-3 year now)

https://github.com/orgs/UnionRolistes/projects/1

**Comment by ClaudeMetz** [comment]
Added a warning for the next release, thanks again.

**Comment by Fr-Dae** [comment]
> Added a warning for the next release, thanks again.

np, have a nice day =)
the template help you ?

**Comment by ClaudeMetz** [comment]
Looks nice! I have my own system that I use though, and I'm pretty happy with it at the moment :)

**Comment by ClaudeMetz** [comment]
I'm okay with the project board I have, thanks though.
