### ISSUE TITLE
[Suggestion] Show ingredients when pinned

### ISSUE THREAD

**Issue by Nevrai** [ClaudeMetz/FactoryPlanner#396]
### Suggestion

When you pin the Factory Planner window, you miss out on seeing the ingredients. I find it’s useful to know the ingredients when building, so I keep having to unpin the window. It would be fantastic if you could see the ingredients when the window is pinned.

![image](https://github.com/user-attachments/assets/0b6e00e1-d143-4b74-8469-105ecd3c9325)

**Comment by ClaudeMetz** [comment]
Hi, thanks for the suggestion. This has been suggested before in #180, and I'll definitely add this at some point!

**Comment by Nevrai** [comment]
Thank you so much for finally adding this! 💙

**Comment by ClaudeMetz** [comment]
You're welcome :)
