### ISSUE TITLE
Planning space sience with Space Age disabled.

### ISSUE THREAD

**Issue by dekallt** [ClaudeMetz/FactoryPlanner#397]
### Problem Description

Planning space sience with Space Age disabled doesn't work.
In another issue #393, the solution was to "manually change the planet you are on to Space Platform".
But there is no way to do that with Space Age disabled.

**Comment by ClaudeMetz** [comment]
Are you sure it's not possible? Seems to work on my side.

![Image](https://github.com/user-attachments/assets/b9b81098-847d-4d40-aef4-5572237cfa33)

**Comment by dekallt** [comment]
Yes, but should it not count for the recipe of the satelitte aswell? When doing this in 1.1 it did. 
Or am i missing something very obvious? :S

**Comment by ClaudeMetz** [comment]
Oh jeez of course, I thought you meant it didn't work at all. I'll fix the satellite not showing up!
