### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Siberius1er** [ClaudeMetz/FactoryPlanner#398]
### Problem Description

Le mod Factory Planner (2.0.4) a engendré une erreur non récupérable.
Merci d'informer l'auteur de cette erreur.

Error while running event factoryplanner::Custom event (ID 306)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__index'
	__factoryplanner__/ui/base/modal_dialog.lua:174: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:222: in function <__factoryplanner__/ui/event_handler.lua:202>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:19: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:178: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:165: in function <__factoryplanner__/ui/event_handler.lua:121>

**Comment by ClaudeMetz** [comment]
Hello, thanks. Same issue as #219, which I'll fix soon.
