### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Siberius1er** [ClaudeMetz/FactoryPlanner#399]
### Problem Description

Le mod Factory Planner (2.0.6) a engendré une erreur non récupérable.
Merci d'informer l'auteur de cette erreur.

Error while running event factoryplanner::on_gui_elem_changed (ID 76)
__factoryplanner__/ui/components/module_configurator.lua:66: attempt to index a nil value
stack traceback:
	__factoryplanner__/ui/components/module_configurator.lua:66: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

**Comment by ClaudeMetz** [comment]
Can you tell me what steps you took to have this crash happen?

**Comment by Siberius1er** [comment]
I modified the quality of a factory's modules

**Comment by ClaudeMetz** [comment]
You'll have to be more specific, this crash doesn't happen in vanilla when changing a normal module. Any mods? Any specific setups?

**Comment by Siberius1er** [comment]
im with mod but its happen with the prod module in the Electromagnetic plant

**Comment by ClaudeMetz** [comment]
I'll need some exact steps, screenshots, or a save file, I can't reproduce it otherwise.
