### ISSUE TITLE
Crash when clicking gear icon next to "Production"

### ISSUE THREAD

**Issue by Silv3rDragon** [ClaudeMetz/FactoryPlanner#401]
### Problem Description

All i do is open the planner window and click the gear icon next to "Production".  It happens on any factory large or small.  Please ask what other information is needed if any, and i will post back with it.

The mod Factory Planner (2.0.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 260)
__factoryplanner__/ui/dialogs/utility_dialog.lua:92: attempt to index local 'main_inventory' (a nil value)
stack traceback:
	__factoryplanner__/ui/dialogs/utility_dialog.lua:92: in function 'refresh_component_flow'
	__factoryplanner__/ui/dialogs/utility_dialog.lua:132: in function 'components'
	__factoryplanner__/ui/dialogs/utility_dialog.lua:432: in function 'dialog_open'
	__factoryplanner__/ui/base/modal_dialog.lua:171: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:222: in function <__factoryplanner__/ui/event_handler.lua:202>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:19: in function 'open_dialog'
	__factoryplanner__/ui/main/production_box.lua:351: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

**Comment by ClaudeMetz** [comment]
Thanks for the report. I think you might have the editor open or similar? Will have a look.

**Comment by Silv3rDragon** [comment]
Yes i do most of the time, and testing just now with editor off does not cause the crash.

**Comment by ClaudeMetz** [comment]
Turns out it even happens when you just have the map open. Fixed for the next release, thanks again.
