### ISSUE TITLE
Error when pasting a recipe to a subfloor

### ISSUE THREAD

**Issue by ThisIsSP4RTAN** [ClaudeMetz/FactoryPlanner#403]
### Problem Description

I'm not sure if this is what was supposed to be fixed in the last update or if this is a new copy/paste bug but yeah, if you try to paste a recipe in a subfloor you crash. 
[factorio-current.log](https://github.com/user-attachments/files/17771036/factorio-current.log)

### Reproduction

1. Copy a recipe
2. Paste it into a subfloor

**Comment by ClaudeMetz** [comment]
Thanks for the report! I actually just noticed this one myself, funnily enough. Will have a look for the next release.

**Comment by ClaudeMetz** [comment]
Fixed for the next release.
