### ISSUE TITLE
Crashing on Utilities tab green checkmark

### ISSUE THREAD

**Issue by Xevion** [ClaudeMetz/FactoryPlanner#404]
### Problem Description

I modified my Steel Plate productivity on a factory changing it from my currently researched 50% to 0%. Upon pressing the confirm/checkmark button, it immediately crashed.

It appears I misunderstood that the checkmark is for the import settings function, not for confirming my changes in productivity.
Note, this crash log contains multiple attempts as I tested this and confirmed how it worked.

[factorio-current.log](https://github.com/user-attachments/files/17779031/factorio-current.log)

Apologies if this is already submitted, I gotta believe it is, but I can't find an issue titled anything immediately relevant at the moment.

### Reproduction

1. I was working on checking my iron ore to steel plate ratio in a factory. Red belts, electric furnaces, 50% steel plate productivity researched by default.
2. I changed my Steel plate productivity to 0%.
3. I pressed the green checkmark button in the top right.
4. The game crashes.
![image](https://github.com/user-attachments/assets/a79ab306-13af-4ed9-b16a-31ef79e16137)

**Comment by ClaudeMetz** [comment]
Thanks for the nice report, fixed for the next release!
