### ISSUE TITLE
Crash on selecting recipe "Space Science Pack"

### ISSUE THREAD

**Issue by LadySmith** [ClaudeMetz/FactoryPlanner#405]
### Problem Description

Thanks for the amazing mod.
Currently, when I try to select **Space Science Pack** and click on it, the game crashes. Please check the reproduction video.
The only mods installed are Factory Planner and game packs.

### Reproduction

Logs:
[factorio-current.log](https://github.com/user-attachments/files/17779658/factorio-current.log)

Video:
https://github.com/user-attachments/assets/d20c27c9-da32-4f56-8086-187599e29f99

**Comment by ClaudeMetz** [comment]
Thanks for the report, this is fixed for the next release.
