### ISSUE TITLE
Toggle switch for showing 'actual recipe requirements/output'

### ISSUE THREAD

**Issue by ThisIsSP4RTAN** [ClaudeMetz/FactoryPlanner#408]
### Suggestion

This would basically work the same way as setting an exact limit for a machine in a recipe that, for example needs 1.5 assemblers to use 2 but be done automatically and adjust itself based on the amount of items you want to produce, modules used, etc. as a toggle switch next to the solver switch or something.

Basically just automatically show a recipe that looks like this:
![1](https://github.com/user-attachments/assets/9077ff3d-0d88-4e4b-a537-c49314a450c2)

As something like this:
![2](https://github.com/user-attachments/assets/d829a1cd-3f83-41d8-a739-3db4f6cad920)

This toggle would automatically be disabled if you manually set a limit for a machine

**Comment by ClaudeMetz** [comment]
Thanks for the suggestion. Do you only care about the machine amounts, or do you also want it to scale all the other stuff as when setting the machine limit?

**Comment by ThisIsSP4RTAN** [comment]
Everything else too, same as when you set a limit

**Comment by ClaudeMetz** [comment]
What's your usecase for wanting to have this mode? Why is it useful to you?

**Comment by ThisIsSP4RTAN** [comment]
Well, for example you can't use 2.5 machines when actually building a factory, so you have to use 3. Then you end up with byproducts you didn't account for or maybe the output becomes too high for that kind of belt. So I usually set an exact limit for any machine that isn't an exact number and round it up like you see in the screenshot.

The problem is, if you change anything in the recipe like how much of the item you want to make, modules you use, the type of machine etc. you have to go back through and change the limits manually, which in bigger factories can be kind of annoying. So having this automatically do that would be very helpful.

**Comment by ClaudeMetz** [comment]
Thanks for explaining. I'm sorry but that use case is too niche to warrant a whole setting for it, so I won't be implementing it.
