### ISSUE TITLE
Beacons cannot be put into factory planner

### ISSUE THREAD

**Issue by Sbmhawk** [ClaudeMetz/FactoryPlanner#409]
### Problem Description

Multiplayer save, worked last Sunday, however I am now unable to put beacons into factory planner.
I can configure the beacons, however when I click submit, the beacon does not get included in the factory plan.

### Reproduction

Start a game, (might have to be hosted on steam)
Plan a factory
try to add a beacon to the plan
See issue

**Comment by ClaudeMetz** [comment]
That's a rough one, thanks for the report. Fixed with the new release!
