### ISSUE TITLE
planet.hidden still shows up as a selectable location

### ISSUE THREAD

**Issue by Quezler** [ClaudeMetz/FactoryPlanner#410]
### Problem Description

![Screenshot 2024-11-17 at 20 18 49](https://github.com/user-attachments/assets/baad7fab-d72e-4203-8f71-ede6761a3479)

### Reproduction

1) have a planet with hidden = true in the prototypes
2) see it show up

**Comment by ClaudeMetz** [comment]
Huh you're right, my boolean logic was off there, thanks. Fixed for the next release.
