### ISSUE TITLE
non-recoverable error when attempting to edit machine

### ISSUE THREAD

**Issue by Acouya** [ClaudeMetz/FactoryPlanner#412]
### Problem Description

Game kicks me back to main menu when attempting to open the edit menu for any recipe using a biochamber.

The mod Factory Planner (2.0.11) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 225)
__factoryplanner__/backend/handlers/defaults.lua:230: attempt to index field 'quality' (a nil value)
stack traceback:
	__factoryplanner__/backend/handlers/defaults.lua:230: in function 'generate_tooltip'
	__factoryplanner__/ui/dialogs/machine_dialog.lua:38: in function 'refresh_defaults_frame'
	__factoryplanner__/ui/dialogs/machine_dialog.lua:65: in function 'add_defaults_frame'
	__factoryplanner__/ui/dialogs/machine_dialog.lua:277: in function 'dialog_open'
	__factoryplanner__/ui/base/modal_dialog.lua:171: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:222: in function <__factoryplanner__/ui/event_handler.lua:202>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:19: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:107: in function 'handler'
	__factoryplanner__/ui/base/modal_dialog.lua:354: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

### Reproduction

1. Enable Space Age, Factory Planner and all requirements
2. Load Save
3. Open Factory Planner
4. Create Factory producing recipe that requires biochamber
5. right click and edit biochamber

**Comment by ClaudeMetz** [comment]
Thanks for the report, you're on of the unlucky 50 people that downloaded that release before I pulled it because I noticed it had a few issues, this included 😅 I'll get an update out tomorrow at the latest.
