### ISSUE TITLE
White Science Calculations Not Including Launch Sattelite?

### ISSUE THREAD

**Issue by WillHops01** [ClaudeMetz/FactoryPlanner#413]
### Suggestion

I have this massive science build I'm working on. I'm almost finished, just need to do white science. I'm realizing however that the factory planner doesn't seem to account for the satellite needed to do an actual launch aka the bit that needs radars and solar power etc.
Am I missing something? I haven't checked yet but I'm worried these extra resources are going to throw off my entire build.. :(
Thanks for this great tool, it otherwise has been extremely helpful!

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report. This was indeed an issue a few versions ago, but should be fixed with 2.0.5, so updating the mod should fix you right up.

**Comment by WillHops01** [comment]
> Hello, thanks for the report. This was indeed an issue a few versions ago, but should be fixed with 2.0.5, so updating the mod should fix you right up.

Ok that did it, thank you so much!

**Comment by ClaudeMetz** [comment]
You're welcome!
