### ISSUE TITLE
Beacon calculation

### ISSUE THREAD

**Issue by davidnnnn** [ClaudeMetz/FactoryPlanner#414]
### Suggestion

Currently, the calculator does not take the beacon's diminishing return into account, I Already have a problem when calculating 8 speed beaconed green circuits. Shows 250+ speed, but it is around 200 in the current version.

**Comment by davidnnnn** [comment]
![image](https://github.com/user-attachments/assets/a99894b9-377a-4adc-8754-df56cc3ceb2d)
Beacon Setup
![image](https://github.com/user-attachments/assets/54ad575e-037f-4851-b639-7aa1a88894cd)
In lane mod
![image](https://github.com/user-attachments/assets/8c4f15fa-5fef-4a39-83ca-b7547d279521)
Calculator, 255%
![image](https://github.com/user-attachments/assets/a5066043-c1b5-4f10-a9c9-7ca767404ec7)
6.1 speed, 205 bonus for 8
![image](https://github.com/user-attachments/assets/11d86d61-c7c5-4f75-a688-f0b483cd304f)
Just to show it is indeed 8 beacon

**Comment by davidnnnn** [comment]
[Factorio production planner.pdf](https://github.com/user-attachments/files/17835942/Factorio.production.planner.pdf)
I did my own calculation with python

**Comment by Xevion** [comment]
Hmm, I see why you're confused, but I am still not 100% certain that this affects actual calculations, you know?

![image](https://github.com/user-attachments/assets/425cd3a4-08d4-484d-b4a0-c723005889a8)
![image](https://github.com/user-attachments/assets/fedaadc8-0b62-48c2-82b7-6a2034ea0ae6)

Sure, the 'Beacon effects' tab on the left is definitely weird and doesn't seem to account for diminishing effects, but the 'Line effects' tab on the right? It's accurate. For me, 364% both in the Factory Planner UI _and_ in-game. Same for you, it says 205% as expected.

The only concern here is that - was it wrong about the number of required machines?

**Comment by davidnnnn** [comment]
> Hmm, I see why you're confused, but I am still not 100% certain that this affects actual calculations, you know?
> 
> ![image](https://private-user-images.githubusercontent.com/44609630/388244738-425cd3a4-08d4-484d-b4a0-c723005889a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzMyMzksIm5iZiI6MTczMjEzMjkzOSwicGF0aCI6Ii80NDYwOTYzMC8zODgyNDQ3MzgtNDI1Y2QzYTQtMDhkNC00ODRkLWI0YTAtYzcyMzAwNTg4OWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDIwMDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZTQxZWVkYzI5ZjQ0NDdiZDg1MzVjNzdlMzcwMDBkZGViMmM0YmE1NzEzMjlmNTA2MmZhYjFkZjUyMzcxNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.quBt-OrgFVZiQkN8O_cbMVgvFipOc-9qU7gF5-vsxbs) ![image](https://private-user-images.githubusercontent.com/44609630/388244819-fedaadc8-0b62-48c2-82b7-6a2034ea0ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMzMyMzksIm5iZiI6MTczMjEzMjkzOSwicGF0aCI6Ii80NDYwOTYzMC8zODgyNDQ4MTktZmVkYWFkYzgtMGI2Mi00OGMyLTgyYjctNmEyMDM0ZWEwYWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDIwMDIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZmQ4NGFiYWQ5ZWRmOGM1MmI3YmI5YWI5YTNiYTA1MDAwYTJkZGQ4MGYzMmY1M2FkY2Q5ZDAzMzY2ZDhlYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QiCHcsEuDhp0HKCN7053CHTsdKERS4zFtI5u0f4IWYo)
> 
> Sure, the 'Beacon effects' tab on the left is definitely weird and doesn't seem to account for diminishing effects, but the 'Line effects' tab on the right? It's accurate. For me, 364% both in the Factory Planner UI _and_ in-game. Same for you, it says 205% as expected.
> 
> The only concern here is that - was it wrong about the number of required machines?

Wait I get it now. I’ve mistaken lane for belt. I thought 1 lane is full belt, but belt option is really it. But the beacon total speed bonus is still misleading. No problem in the final calculation.
