### ISSUE TITLE
Negative beacon amounts induces crash

### ISSUE THREAD

**Issue by Xevion** [ClaudeMetz/FactoryPlanner#415]
### Problem Description

I was editing the Beacon amount to test the mathematical expression evaluations (because I can't type floats, because not all my refineries get an equal amount of beacons), and somehow typed _something_ that crashed it.

The last thing I had typed in the box was 18-21.

![image](https://github.com/user-attachments/assets/35a8cdea-7ac9-4af1-9c86-ca6c5d659929)

[factorio-current.log](https://github.com/user-attachments/files/17835841/factorio-current.log)

**Comment by Xevion** [comment]
Apparently, any negative number typed in the box is an instant crash, so... yeah.

Not that I have much knowledge of Factorio modding, Lua programming or can really judge, but shouldn't a lot of these functions be validating input properly? This feels like something I would account for in my own projects naturally. Maybe if I'm making a comment like this, perhaps I should be willing to contribute though...

**Comment by ClaudeMetz** [comment]
Thanks for the report. This whole thing is kind of tricky on the backend, and the validation needs to be done manually in a sense. I missed the negative part. Will have a look at fixing it.

**Comment by ClaudeMetz** [comment]
Fixed for the next release.
