### ISSUE TITLE
Crashes when pasting modules from Assembler 2 to another Assembler 2, via shift clicking.

### ISSUE THREAD

**Issue by sferg8** [ClaudeMetz/FactoryPlanner#421]
### Problem Description

Shift right click copied and pasted t1 speed modules into a tier 2 assembler.

The mod Factory Planner (2.0.12) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/backend/data/Module.lua:125: attempt to index field 'parent' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/Module.lua:125: in function 'validate'
	__factoryplanner__/util/clipboard.lua:48: in function 'paste'
	__factoryplanner__/ui/main/production_handler.lua:124: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:173: in function <__factoryplanner__/ui/event_handler.lua:121>

**Comment by ClaudeMetz** [comment]
Hello, thanks for the report! This issue is fixed (#417) for the next release, which is due out soon.

**Comment by sferg8** [comment]
Thank you for your hard work, please enjoy this picture of a handsome frog.

![image](https://github.com/user-attachments/assets/87403b98-e200-46a6-84da-c9b60bce4c8f)

**Comment by ClaudeMetz** [comment]
Thanks, I appreciate the frog. Mesmerizing eyes on that fella.
