### ISSUE TITLE
Crash on copying modules

### ISSUE THREAD

**Issue by LoredRaven** [ClaudeMetz/FactoryPlanner#422]
### Problem Description

The mod Factory Planner (2.0.12) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/backend/data/Module.lua:125: attempt to index field 'parent' (a nil value)
stack traceback:
	__factoryplanner__/backend/data/Module.lua:125: in function 'validate'
	__factoryplanner__/util/clipboard.lua:48: in function 'paste'
	__factoryplanner__/ui/main/production_handler.lua:124: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:173: in function <__factoryplanner__/ui/event_handler.lua:121>
[factorio-current.log](https://github.com/user-attachments/files/17879041/factorio-current.log)

### Reproduction

1. Fulgora, electromagnetic-science-pack chain
2. Build the chain for the different ingredients
3. Defines the modules for the first line
4. copy the module def from the the line
5. try to paste the module def onto another factory (also electro magnetic plant)
6. Crash

**Comment by ClaudeMetz** [comment]
Hello, thanks for the nice report! This issue should be addressed in 2.0.13, so please try updating the mod to fix this one.
