### ISSUE TITLE
Non-recoverable error when attempting to change machine

### ISSUE THREAD

**Issue by DataBeaver** [ClaudeMetz/FactoryPlanner#423]
### Problem Description

Most of my factories from Factory Planner 2.0.2 were marked as broken and many of them had their machines reset to defaults when repaired with the button.  I was trying to fix one of them by hand and when trying to change the machine of a recipe which had been assigned to a biochamber I got this error:

The mod Factory Planner (2.0.13) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::Custom event (ID 225)
__factoryplanner__/ui/dialogs/machine_dialog.lua:104: attempt to index field 'fuel' (a nil value)
stack traceback:
	__factoryplanner__/ui/dialogs/machine_dialog.lua:104: in function 'refresh_fuel_frame'
	__factoryplanner__/ui/dialogs/machine_dialog.lua:169: in function 'add_fuel_frame'
	__factoryplanner__/ui/dialogs/machine_dialog.lua:262: in function 'dialog_open'
	__factoryplanner__/ui/base/modal_dialog.lua:171: in function 'enter'
	__factoryplanner__/ui/event_handler.lua:226: in function <__factoryplanner__/ui/event_handler.lua:206>
stack traceback:
	[C]: in function 'raise_event'
	__factoryplanner__/util/raise.lua:19: in function 'open_dialog'
	__factoryplanner__/ui/main/production_handler.lua:107: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:169: in function <__factoryplanner__/ui/event_handler.lua:121>

It would be great if the machines didn't get reset at all, but at the very least the mod should survive trying to manually change them.

[factorio-current.log](https://github.com/user-attachments/files/17879951/factorio-current.log)
[2024-10 planning.zip](https://github.com/user-attachments/files/17879952/2024-10.planning.zip)

### Reproduction

1. Load the save attached above
2. Click the repair button on one of the rocket factories in the Vulcanus district
3. Click on the biochamber for one of the oil cracking recipes
4. Error dialog pops up

**Comment by ClaudeMetz** [comment]
Thanks for the report, this was very helpful. I fixed the issue where opening the migrated machine crashes, as well as the issue where it mistakenly resets machines in the first place. Release is due out soon, sorry about the issues caused.
