### ISSUE TITLE
Restore functionality of copy-pasting modules with machines

### ISSUE THREAD

**Issue by DataBeaver** [ClaudeMetz/FactoryPlanner#424]
### Suggestion

I'm uncertain if this is due to migration from Factory Planner 2.0.2, but copy-pasting a machine between recipes no longer brings modules with it.  See #423 for a save where this happens.

**Comment by ClaudeMetz** [comment]
Hm well this is sort of tricky. I was aware I was making this change, but I'm not sure if it's the right one. I can see the case for both situations, one where it copies modules and fuel, and one where it only copies the machine itself. I'll have to think about it for a bit.

**Comment by ClaudeMetz** [comment]
I thought about it, and decided it makes more sense for it to bring everything along. Thanks for the suggestion, implemented for the next release.
