### ISSUE TITLE
Close District selection window after selcting a new District

### ISSUE THREAD

**Issue by apaksl** [ClaudeMetz/FactoryPlanner#425]
### Suggestion

I just think it would save a step of having to click the down arrow after swapping districts, but I get this is a passion project of yours, and I don't want to burden you :)

**Comment by ClaudeMetz** [comment]
Hi, this is what #379 describes, and I'll probably implement it like you suggest. No worries about bothering me, I'm always happy to hear suggestions! Closing this one as duplicate.
