### ISSUE TITLE
Right click ingredient and put into cursor crash

### ISSUE THREAD

**Issue by Seawolf159** [ClaudeMetz/FactoryPlanner#426]
### Problem Description

Right click ingredient and put into cursor crash:

The mod Factory Planner (2.0.14) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_gui_click (ID 1)
__factoryplanner__/util/cursor.lua:146: attempt to perform arithmetic on local 'amount' (a nil value)
stack traceback:
	__factoryplanner__/util/cursor.lua:146: in function 'add_to_item_combinator'
	__factoryplanner__/util/cursor.lua:253: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:234: in function 'handle_item_click'
	__factoryplanner__/ui/main/production_handler.lua:343: in function 'handler'
	__factory
planner__/ui/base/modal_dialog.lua:354: in function 'handler'
	__factoryplanner__/ui/event_handler.lua:173: in function <__factoryplanner__/ui/event_handler.lua:121>

[factorio-current.log](https://github.com/user-attachments/files/17893091/factorio-current.log)

### Reproduction

Right click ingredient and put into cursor crash

**Comment by ClaudeMetz** [comment]
Thanks for the report. Can you tell me what the setup was that you clicked on? Maybe a screenshot would help.
