### ISSUE TITLE
Crash when loading save

### ISSUE THREAD

**Issue by TRN-Noodle** [ClaudeMetz/FactoryPlanner#428]
### Problem Description

The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_configuration_changed
__factoryplanner__/backend/handlers/generator.lua:1041: attempt to compare number with nil
stack traceback:
	__factoryplanner__/backend/handlers/generator.lua:1041: in function <__factoryplanner__/backend/handlers/generator.lua:1040>
	[C]: in function 'sort'
	__factoryplanner__/backend/handlers/prototyper.lua:65: in function 'apply'
	__factoryplanner__/backend/handlers/prototyper.lua:86: in function 'convert_and_sort'
	__factoryplanner__/backend/handlers/prototyper.lua:115: in function 'build'
	__factoryplanner__/backend/init.lua:244: in function <__factoryplanner__/backend/init.lua:229>

**Comment by AndrewD22** [comment]
I got same error after update. 
Get it when when I load a save, which prevents me from loading that save.

**Comment by dexblokdijk** [comment]
Getting this same error when I try to make a new save. Happened first with Ultracube enabled, but getting the same error without it.

**Comment by SolMill** [comment]
Also getting this error when loading save.
