### ISSUE TITLE
Crash when loading factory planner after update from 2.0.4(-ish) to 2.0.15

### ISSUE THREAD

**Issue by seasox** [ClaudeMetz/FactoryPlanner#429]
### Problem Description

The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::fp_toggle_interface (ID 215)
__factoryplanner__/ui/components/item_views.lua:239: attempt to index local 'view' (a nil value)
stack traceback:
	__factoryplanner__/ui/components/item_views.lua:239: in function 'func'
	__factoryplanner__/ui/components/item_views.lua:222: in function 'run_on_all_views'
	__factoryplanner__/ui/components/item_views.lua:248: in function 'rebuild_interface'
	__factoryplanner__/ui/base/main_dialog.lua:105: in function 'rebuild'
	__factoryplanner__/ui/base/main_dialog.lua:116: in function 'toggle'
	__factoryplanner__/ui/base/main_dialog.lua:235: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:330: in function <__factoryplanner__/ui/event_handler.lua:307>

### Reproduction

Probably something like this:

1. Plan your factories in 2.0.4 (might have been 2.0.6)
2. Update FactoryPlanner to 2.0.15
3. After update, open the factory planner.
4. Observe the call stack posted above.

**Comment by xor50** [comment]
Trying to open it after latest update:

![grafik](https://github.com/user-attachments/assets/f42a72a9-3e55-4c81-9ea5-1a23d9529f56)

**Comment by MorithK** [comment]
The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_player_display_resolution_changed (ID 106)
__factoryplanner__/ui/components/item_views.lua:239: attempt to index local 'view' (a nil value)
stack traceback:
	__factoryplanner__/ui/components/item_views.lua:239: in function 'func'
	__factoryplanner__/ui/components/item_views.lua:222: in function 'run_on_all_views'
	__factoryplanner__/ui/components/item_views.lua:248: in function 'rebuild_interface'
	__factoryplanner__/ui/base/main_dialog.lua:105: in function 'rebuild'
	__factoryplanner__/ui/base/main_dialog.lua:41: in function 'shrinkwrap_interface'
	__factoryplanner__/ui/base/main_dialog.lua:219: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:330: in function <__factoryplanner__/ui/event_handler.lua:307>
	
[factorio-current.log](https://github.com/user-attachments/files/17921647/factorio-current.log)

updated to 2.0.15 this morning. Have also included log file

**Comment by hjtroteclaser** [comment]
Maybe related #431 Crash when changing UI scale or on loading Save with different UI scaling "on_player_display_scale_changed"

```lua
The mod Factory Planner (2.0.15) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_player_display_scale_changed (ID 107)
__factoryplanner__/ui/components/item_views.lua:239: attempt to index local 'view' (a nil value)
stack traceback:
	__factoryplanner__/ui/components/item_views.lua:239: in function 'func'
	__factoryplanner__/ui/components/item_views.lua:222: in function 'run_on_all_views'
	__factoryplanner__/ui/components/item_views.lua:248: in function 'rebuild_interface'
	__factoryplanner__/ui/base/main_dialog.lua:105: in function 'rebuild'
	__factoryplanner__/ui/base/main_dialog.lua:41: in function 'shrinkwrap_interface'
	__factoryplanner__/ui/base/main_dialog.lua:224: in function 'registered_handler'
	__factoryplanner__/ui/event_handler.lua:330: in function <__factoryplanner__/ui/event_handler.lua:307>
```

**Comment by TommyC81** [comment]
Same error/crash. I don't use any scaling, if it matters.
