### ISSUE TITLE
non recoverable error on game load

### ISSUE THREAD

**Issue by RichoDemus** [ClaudeMetz/FactoryPlanner#433]
### Problem Description

The mod Factory Planner (2.0.16) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factoryplanner::on_configuration_changed
__factoryplanner__/backend/migrations/migration_2_0_16.lua:15: table index is nil
stack traceback:
	__factoryplanner__/backend/migrations/migration_2_0_16.lua:15: in function 'migration_function'
	__factoryplanner__/backend/handlers/migrator.lua:67: in function 'apply_migrations'
	__factoryplanner__/backend/handlers/migrator.lua:105: in function 'migrate_player_tables'
	__factoryplanner__/backend/init.lua:240: in function <__factoryplanner__/backend/init.lua:229>

### Reproduction

from factorio-current:

Error while running event factoryplanner::on_configuration_changed
__factoryplanner__/backend/migrations/migration_2_0_16.lua:15: table index is nil
stack traceback:
	__factoryplanner__/backend/migrations/migration_2_0_16.lua:15: in function 'migration_function'
	__factoryplanner__/backend/handlers/migrator.lua:67: in function 'apply_migrations'
	__factoryplanner__/backend/handlers/migrator.lua:105: in function 'migrate_player_tables'
	__factoryplanner__/backend/init.lua:240: in function <__factoryplanner__/backend/init.lua:229>
  49.874 Info IDWithQuality.cpp:304: fixing missing qualityID for id rail
  49.874 Info Blueprint.cpp:52: when loading blueprint ""
  49.874 Info SimulationWidget.cpp:34: save __base__/menu-simulations/menu-simulation-train-junction.zip
  49.874 Info IDWithQuality.cpp:304: fixing missing qualityID for id rail-ramp
  49.874 Info Blueprint.cpp:52: when loading blueprint ""
  49.874 Info SimulationWidget.cpp:34: save __base__/menu-simulations/menu-simulation-train-junction.zip
  59.973 Info IDWithQuality.cpp:304: fixing missing qualityID for id signal-blue
  59.973 Info Blueprint.cpp:52: when loading blueprint "ALL"
  59.973 Info SimulationWidget.cpp:34: save __base__/menu-simulations/menu-simulation-artillery.zip
  59.973 Info IDWithQuality.cpp:304: fixing missing qualityID for id signal-F
  59.973 Info Blueprint.cpp:52: when loading blueprint "Factorio"
  59.973 Info SimulationWidget.cpp:34: save __base__/menu-simulations/menu-simulation-artillery.zip
  59.973 Info IDWithQuality.cpp:304: fixing missing qualityID for id signal-W
  59.973 Info Blueprint.cpp:52: when loading blueprint "Wube"
  59.973 Info SimulationWidget.cpp:34: save __base__/menu-simulations/menu-simulation-artillery.zip
  59.974 Info IDWithQuality.cpp:304: fixing missing qualityID for id rail
  59.974 Info Blueprint.cpp:52: when loading blueprint ""
  59.974 Info SimulationWidget.cpp:34: save __base__/menu-simulations/menu-simulation-artillery.zip
  59.974 Info IDWithQuality.cpp:304: fixing missing qualityID for id rail-ramp
  59.974 Info Blueprint.cpp:52: when loading blueprint ""
  59.974 Info SimulationWidget.cpp:34: save __base__/menu-simulations/menu-simulation-artillery.zip

**Comment by ClaudeMetz** [comment]
Thanks for the report. Not sure how that part of the code can crash, but I put a mitigation in place for the next release.
