### ISSUE TITLE
non-recoverable error on putting offshore pump into cursor

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [ClaudeMetz/FactoryPlanner#438]
### Problem Description

It appears you forgot to disable "put into cursor" for offshore pumps in compact mode :)

![image](https://github.com/user-attachments/assets/fe4cb4a4-4476-4b82-9cf5-c0251bf5df53)
[factorio-current.log](https://github.com/user-attachments/files/17965378/factorio-current.log)

### Reproduction

1. create a factory with an offshore pump
2. put FP into compact view
3. click on offshore pump

**Comment by ClaudeMetz** [comment]
Well I actually implicitly wanted to put them into the cursor, with them showing their placement guide as well. But a later change screwed it up again. Anyways, thanks, fixed for the next release.
