### ISSUE TITLE
Incompability with Platformer

### ISSUE THREAD

**Issue by Quazaka** [ClaudeMetz/FactoryPlanner#446]
### Problem Description

My mod is incompatible with Factory planner because you expect that at least one cargo wagon exists. I have hidden trains and is therefore null for some reason. 

I would love for it to be compatible as the mod we are making is a overhaul mod with different ratios and recipes. 
I think it might be a bug on your end.

![image](https://github.com/user-attachments/assets/a96cc8b3-235f-44ff-ad23-026d575d6d54)

**Comment by ClaudeMetz** [comment]
Hello, thanks for the heads-up, looks like an issue from my side for sure. This report is a duplicate of #441, so closing it as such.
