### ISSUE TITLE
Add inserters/timescale and stacks/timescale view_states

### ISSUE THREAD

**Issue by ClaudeMetz** [ClaudeMetz/FactoryPlanner#71]
The inserters one should probably replace the items/machine/s one

**Comment by ClaudeMetz** [comment]
Added for 2.0.

**Comment by fxposter** [comment]
> Added for 2.0.

@ClaudeMetz can you clarify what does it mean? number of inserters and which ones I should choose is the only feature I miss in factory planner compared to helmod.

**Comment by ClaudeMetz** [comment]
Sorry yeah I should have mentioned, the inserters one isn't in because it's kinda nonsensical. There's so many different setups for inserters that all have different throughputs that I don't see how to really make it work. Open to suggestions though.

**Comment by Brumes-Wolf** [comment]
> Sorry yeah I should have mentioned, the inserters one isn't in because it's kinda nonsensical. There's so many different setups for inserters that all have different throughputs that I don't see how to really make it work. Open to suggestions though.

Wouldn't taking the output of a machine divided by the throughput of an inserter combined with UI to pick the preferred type of inserter like there already is for belts be good enough?

**Comment by fxposter** [comment]
Yes, I guess simply taking into account current inserter capacity bonus + "Turns per Game-second" from https://wiki.factorio.com/inserters gives you more-or-less adequate estimate. It will not be 100% correct, but adequate enough to be useful

**Comment by Brumes-Wolf** [comment]
> Yes, I guess simply taking into account current inserter capacity bonus + "Turns per Game-second" from https://wiki.factorio.com/inserters gives you more-or-less adequate estimate. It will not be 100% correct, but adequate enough to be useful

Just rounding up to 1 decimal every step of the calculation should create plenty of margin. Or just manually adding a fudge factor of 10 percent or so.
The worst possible thing would be underestimating the amount, so that should be avoided at all cost

**Comment by fxposter** [comment]
well, you can *always* underestimate :) for example, if you are outputting to the belt which already has some items - the inserters will need to wait and sometimes it forces you to switch to faster inserters than "the calculation" requires. So there is no 100% correct answer.
But showing something (ie: if you know that you need 4.5 yellow inserters to put copper into 5 assemblers - you probably need 1 inserter per assembler) in this case is better that nothing, IMHO.

**Comment by Brumes-Wolf** [comment]
Agreed, having a ballpark idea if you need 1 yellow or 3 blue inserters for output on an assembler is really usefull. 
And making sure the belt is fast enough/has enough capacity should be on the player imo. I personally wouldn't expect the planner to take that into account.

**Comment by ClaudeMetz** [comment]
The thing is the differences in estimation will be much more different than you expect. And if I always show the minimum, it'll be wildly lower than the actual throughput in 90% of cases. There's not really a way to win I feel.

Like just to give more context, inserter throughput depends on: Inserter swing speed, inserter capacity, belt stacking size, origin type (chest, belt), target type (chest, belt), when targeting belts it depends on belt speed, belt direction. Not to mention the effect of the inserter hunting algorithm etc.

It's just incredibly variable. With that combinatoric explosion of possible situations, any number I show on a button will just be sorta random. I feel it's better to get an inserter throughput mod that shows you what the throughput of any particular inserter in the world is, and compare that to the numbers FP shows. I know that's not easy or satisfying, but it's the only way to be correct.

**Comment by fxposter** [comment]
Well, I used to use helmod and I can tell you that one number, even if it's slightly off - can be useful. Regarding source and destination - for input items you know the destination - it would be an assembler - and for output ones the source would also be the assembler as well. So the main thing that you need to account for is current capacity bonus, which does make a huge difference.

Also, regarding the new stack inserter in Space Age - IDK the mechanics for it, so that might be a problematic one to calculate...

**Comment by ClaudeMetz** [comment]
Yeah maybe I'm wrong about it. I'll consider it in the future.
